### ISSUE TITLE
Upload brakes on Opera 10 with lates jquery.forms.js.

### ISSUE THREAD

**Issue by neochief** [jquery-form/form#1]
100 Ms is not enought to opera 10 to understand that post was posted. This fix adds flexible approach to add time on post processing:

<pre>
                 doc = io.contentWindow ? io.contentWindow.document : io.contentDocument ? io.contentDocument : io.document;
 
-                if ((doc.body == null || doc.body.innerHTML == '') && !nullCheckFlag) {
+                if ((doc.body == null || doc.body.innerHTML == '') && ($.browser.opera) && (nullCheckFlag < 1000000)) {
                     // in some browsers (cough, Opera 9.2.x) the iframe DOM is not always traversable when
                     // the onload callback fires, so we give them a 2nd chance
-                    nullCheckFlag = 1;
-                    cbInvoked--;
+                    nullCheckFlag++;
+                    cbInvoked = 0;
                     setTimeout(cb, 100);
                     return;
                 }
</pre>

**Comment by malsup** [comment]
Thanks very much for this info.  Finally updated the plugin!
