### ISSUE TITLE
Maintainance?

### ISSUE THREAD

**Issue by kevindb** [jquery-form/form#1]
_From @whimsicaldreamer on September 7, 2016 13:14_

Is this plugin no longer actively maintained? If no then why is there no new updates to this plugin?

_Copied from original issue: malsup/form#508_

**Comment by kevindb** [comment]
_From @alienintheheights on January 11, 2017 18:2_

It hasn't been updated in three years. It looks very dead. Last release has issues with IE Edge. We're in the process of removing it from our products.

**Comment by kevindb** [comment]
_From @federicovilla on January 12, 2017 16:30_

Would be great to see this library updated and maintained...it's one of the best around here

**Comment by kevindb** [comment]
_From @alienintheheights on January 12, 2017 17:56_

agree! Migrating is a pain. We're looking at Fine Uploader, btw.

**Comment by kevindb** [comment]
I have forked the repo to an organization so that we can maintain the plugin as a community. I'll try to do some work cleaning up and examining pull requests this weekend.
https://github.com/jquery-form/form

**Comment by federicovilla** [comment]
Great kevin! Well done

**Comment by whimsicaldreamer** [comment]
Great work.
