### ISSUE TITLE
Suggested enhancement - how identify AJAX submission?

### ISSUE THREAD

**Issue by BilboUK** [jquery-form/form#10]
To avoid duplicating code, I use the same script to process form submissions whether it is via ajax or not (e.g. if user has JS disabled).  It is necessary in this case to separate ajax posts so that only the relevant sub-page can be sent back to the browser.  I normally inject a form field prior to the ajax submission to do this.  I could pick up the form object in a pre-submission callback but it may be easier to simply mod the plug-in - perhaps a small enhancement: e.g. insert before L473:
    a.push({name: 'jqueryForm', value: 'true'});

This will add an input field which I can then detect in the server script and adjust the processing accordingly.
Thx,
Geoff

**Comment by malsup** [comment]
You can use the request header to determine if the request came from ajax or not.  Details here:  http://www.learningjquery.com/2010/03/detecting-ajax-events-on-the-server

**Comment by BilboUK** [comment]
Thanks for the info.  I'm new to JQ (though not new to JS etc.) and haven't seen this header before.  Is this passed through all servers? - I know some server programs "filter out" headers they don't recognise!

**Comment by malsup** [comment]
This should work fine in any server-side lang that lets you get at the request object.  Alternatively, you can use the 'data' option to pass additional data on the submit:

```
$('#myForm').ajaxForm({
    data: { jqueryForm: true } // adds 'jqueryForm param to request
});
```

**Comment by BilboUK** [comment]
Ah yes... this plug-in is really rather good  :)   Note to self: must RTFM   ;)
Thanks for your help
