### ISSUE TITLE
Using iframe option changes GET method to POST

### ISSUE THREAD

**Issue by chosak** [jquery-form/form#101]
I have a page with multiple forms, all of which I want to submit using the form plugin. Because some of these may include file uploads, I would prefer to have the iframe option always set to true, and code my server-side script to always return JSON wrapped in a <textarea>. With forms of type GET, there's no need to use an iframe, but I'd prefer to handle all of them the same way.

In version 2.81, line 285 (doSubmit), the form method is set to POST if it isn't already -- this is presumably to support IE requirements. However, if the form method is already set to GET (or some other method, like DELETE), this will break expected behavior. It seems like this line could be changed to set the value to POST only if it isn't set to something else already. The following logic about using 'multipart/form-data' encoding could also be changed to allow for GETs with 'application/x-www-form-urlencoded'.

Is there a reason why the code couldn't be changed in this way? When using the plugin, can iframe submissions be used with non-POST forms? It would be nice if the documentation reflected this limitation if it is indeed the case.

**Comment by malsup** [comment]
Fixed in v2.82.

**Comment by chosak** [comment]
Thanks very much for the quick response!
