### ISSUE TITLE
IE-compatibility: response Content-Type should always be text/html when using iframe technique

### ISSUE THREAD

**Issue by costa** [jquery-form/form#104]
This is just something very well worth mentioning in the docs. Even when dataType: 'script' is specified, and the server is actually responding with some javascript to a multipart form submission, the response's Content-Type header should be forced to text/html, otherwise IE will try to prompt and download a "file".

**Comment by TwistedLogic** [comment]
+1 on this issue. I've just tested it

**Comment by azilberbaum** [comment]
+1 I also just tested this! - thank you

**Comment by compwright** [comment]
+1 for adding this to the documentation. This solution worked for me also.

**Comment by malsup** [comment]
Docs updated.  Thanks, guys.
