### ISSUE TITLE
Provide access to underlying deferred

### ISSUE THREAD

**Issue by malsup** [jquery-form/form#105]
yeah.

**Comment by rekna1** [comment]
is this coming ? it would be nice to be able to use the new api's for success / error / when / etc

**Comment by malsup** [comment]
Example:  http://jquery.malsup.com/form/deferred.php

**Comment by DavidVotrubec** [comment]
Great work, man!
You have just made my day:)
I've been trying to bend your plugin to return xhr object, but it only returned xhr for standart submit without any files. And I did not know how to workaround it. Thanks a lot. 

PS: Is there somewhere a 'Donate' button? I want to buy you a beer.

**Comment by malsup** [comment]
Donate link at bottom of:  http://jquery.malsup.com/

Thanks!

**Comment by rumadas** [comment]
Hi Good day.. I am facing issue in IE all versions

 Object doesn't support property or method 'Deferred'

Can you please help?
