### ISSUE TITLE
Error callback is ignored on file upload forms.

### ISSUE THREAD

**Issue by webinarium** [jquery-form/form#107]
Hello,

When I specify "error" callback function to handle server-side errors, it works fine on any form, which doesn't contain file upload controls. But when file upload is present on the form - "success" callback is run for server-side errors, and the error code is lost there.

Let's assume the following simplified form page (regular one, w/out file uploads):

```
<html>
<head>
<script type="text/javascript" src="jquery.js"></script>
<script type="text/javascript" src="jquery.form.js"></script>
<script type="text/javascript">

$(document).ready(function() {

    $('#myForm').ajaxForm({

        success: function(responseText, statusText, XMLHttpRequest) {
            alert('SUCCESS\n' +
                  'responseText: '                + responseText                + '\n' +
                  'statusText: '                  + statusText                  + '\n' +
                  'XMLHttpRequest.status: '       + XMLHttpRequest.status       + '\n' +
                  'XMLHttpRequest.statusText: '   + XMLHttpRequest.statusText   + '\n' +
                  'XMLHttpRequest.responseText: ' + XMLHttpRequest.responseText);
        },

        error: function(XMLHttpRequest) {
            alert('ERROR\n' +
                  'XMLHttpRequest.status: '       + XMLHttpRequest.status       + '\n' +
                  'XMLHttpRequest.statusText: '   + XMLHttpRequest.statusText   + '\n' +
                  'XMLHttpRequest.responseText: ' + XMLHttpRequest.responseText);
        }
    });
});

</script>
</head>
<body>

<form name="myForm" id="myForm" action="handler.php" method="post">
<input type="text" name="mycontrol">
<input type="submit" value="Submit" />
</form>
</body>
```

If "handler.php" returns success, like following:

```
<?php
header('HTTP/1.0 200 OK');
echo('This is a response from server.');
?>
```

then "success" callback is executed and it can reach response text with no problems. In case of errors on the server:

```
<?php
header('HTTP/1.0 500 Internal Server Error');
echo('This is an error message from server.');
?>
```

the "error" callback is executed, having access to both error code (500) and response text.

But if we use file upload control, like following:

```
<form name="myForm" id="myForm" action="handler.php" method="post"
    enctype="multipart/form-data" encoding="multipart/form-data">
<input type="hidden" name="MAX_FILE_SIZE" value="100000">
<input type="file" name="mycontrol">
<input type="submit" value="Submit" />
</form>
```

then only "success" callback is executed no matter what server returns. The response from server is received in both cases - success and error - but in case of error, the "success" callback receives "success" as a "statusText", so there is absolutely no way to understand is it a successful response or failure one. Also, error code from the server is needed too.

I'm not sure, but maybe the real status is lost somewhere in iframe, which is used for file uploads. In any case, is it possible to hand-off actual server status back to caller, and to execute correct callback function?

This is great plugin anyway, thank you for it. :)

Best regards,
Artem

**Comment by webinarium** [comment]
Forgot to mention:
jQuery = 1.6.2
Form plugin = 2.82

**Comment by malsup** [comment]
The current implementation does not allow you to drive success/error handling via response headers because the headers are not available (because the response is sent to an iframe).  I plan to implement FormData based file uploads pretty soon but that will only be supported by the very latest browsers.

**Comment by webinarium** [comment]
Seems like I have no choice but to make a workaround in my own code, passing error information in a normal response to "success" callback. Ok, thank you for the response.
