### ISSUE TITLE
bug: multiple success callbacks when target provided

### ISSUE THREAD

**Issue by snozwoz** [jquery-form/form#108]
it took me the whole day to get to the bottom of this.

I have multiple forms on the page, all using your ajax form plugin (very good thanks) version 2.82 (upgraded to try and resolve without luck).
when initialising them i used target param and also success, typically
someform.ajaxForm({
                success:somefunction
                ,target:"#somediv"
            });

i found the "success: functions" where building up into an array after each submit.
so if one form was submitted this is fine, and the success function of this was called, and target updated.
if another form was submitted, on success it would call the "success: function" of the first form, and then the 2nd form.
if a 3rd form was then submitted it would run the 1st, the 2nd and finally the 3rd form success. 
I had different on success functions for each form, the result was a right mess, after a few form submits i had many on success functions being called.

The solution was to remove "target" from my setup and add my own code in the success function  to do this.

this code use to work fine, i think it might be a result of the changes jQuery made in version 1.5 or 1.6.
I am not sure, the issue was very bizzar. 
If you dont wish to fix this, i recommend you update the documentation to not use 'target' in conjunction with 'success'.

**Comment by kevindb** [comment]
Resolved by #463
