### ISSUE TITLE
dataType is not working

### ISSUE THREAD

**Issue by denoww** [jquery-form/form#111]
dataType is not working, always request text/html regardless if i configure -> dataType: 'json'

**Comment by shelhamer** [comment]
Are you sure it isn't the server ignoring the header? I just did some tests and the Accept header is set correctly with each request I have tried.

**Comment by tomds** [comment]
Do you have a file field on your form? If you have a file field and you have a browser that requires the plugin to submit the form via a hidden iframe e.g. Internet Explorer, you can't change the accept headers because it's just a standard form submission.
