### ISSUE TITLE
Success doesn't get triggered in FF 3.5 on file uploads

### ISSUE THREAD

**Issue by TwistedLogic** [jquery-form/form#115]
Browser Version: Mozilla Firefox 3.5.19
OS: Linux 2.6.38-10-generic-pae #46-Ubuntu SMP Tue Jun 28 16:54:49 UTC 2011 i686 i686 i386 GNU/Linux

Params used:
  dataType: 'json'
  success: function(response) {}

Server code is executed correctly (file upload is succesful) and it returns a json string.
I tried different content types for the server response: application/json , text/html , text/javascript

[Using text/html solved an issue on IE9]

Success callback is never called and jQuery form console output is:
  [jquery.form] state = undefined
  [jquery.form] Server abort: TypeError: state is undefined (TypeError)
  [jquery.form] aborting upload... aborted

**Comment by asgh** [comment]
For file uploads with a json result, the content type has to be text/html and the json needs to be wrapped in textarea tags. This is because it uses a hidden iframe, and there is no direct way to send json to an iframe.

**Comment by TwistedLogic** [comment]
I think this issue isn't related to textarea tag because the output above is displayed istantly, even before file upload starts.
BTW, without wrapping response into a textarea tag, following browsers handle very well the response:
Chrome, Firefox 3.6+, IE9 (with content-type: text/html), Opera 11.50, Safari

**Comment by TwistedLogic** [comment]
I found the bug, on line 321, instead of
  if (state.toLowerCase() == 'uninitialized')
we need a check on state:
  if (state && state.toLowerCase() == 'uninitialized')

**Comment by kevindb** [comment]
Are you still experiencing this issue?
