### ISSUE TITLE
File upload not executed in IE8 & Iceweasel

### ISSUE THREAD

**Issue by scraze** [jquery-form/form#116]
(I hope this is the correct place to post issues without having much of a clue what the underlying problem is, nor a reliable test sample  - if not, my apologies!)

Synopsis:
Using the latest jquery.form.js (2.83), IE8 and Iceweasel (based on FF3.5.19) won't upload files. 

Test case:
A page containing only a div and a simple form with one input element of type 'file', and one input element of type 'submit', initialized by $( function( ) { $( 'form' ).ajaxForm( { target : '#idofdiv' } ) } ) - i.e., the simplest of cases. 

Tested with:
Windows Vista : IE 8.0.6, FF5.0
Debian Wheezy: Chromium, Iceweasel (based on FF3.5.19)

Description IE8:
IE8 seems to submit the form without attempting to upload the file, even though the name & value of the input element are included in serialization & submission. The response is successfully placed into the target div. No errors occur, yet no file has been uploaded.

Description Iceweasel:
Iceweasel errors on submission with Firebug giving the following message:
[jquery.form] state = undefined
[jquery.form] Server abort: TypeError: state is undefined (TypeError)
[jquery.form] aborting upload... aborted

Problem tracking:
I ran a git bisect for both browsers, but came up with some unexpected results, probably due to my lack of distinguishing good from bad (I have the logs if needed). So I traversed the commits manually, and came up with this:

Iceweasel's 'Server abort':
Appears at commit b36e07abefb5edfa6bb6 (v2.81 - add detection for server-side aborts) 
works with previous commit ee5e4a4a6583da7f50cb (fixed for: https://github.com/malsup/form/issues/40)

IE8's blissful unawareness of files to upload:
Appears at commit 8a88948b8e826364b35b (v2.77 - support status/statusText attrs on file upload response (thanks kares!))
works with previous commit e2c3fd8d4e2f927e562c (merge from kares)

Commit e2c3fd8d4e2f927e562c works with all browsers I tested. I haven't reviewed aforementioned commits yet in an effort to fix the problems I'm having, as I wanted to inform you first. 
Thanks!

**Comment by joekarl** [comment]
I'm seeing this too, ie8 on xp. The form is created correctly, just doesn't try to upload the file.

**Comment by joekarl** [comment]
After some digging, it turned out that I didn't have a method set on my form. I guess at some point the default changed from post to get. After setting my method to post things work fine in ie. 

@scraze, you might check your method type for your form.

**Comment by chuanjiabao1981** [comment]
@joekarl 
i have the same problem in ie8
https://github.com/malsup/form/issues/123

**Comment by Lethea** [comment]
How did you use the plugin ? 
for ex sometime , i use it
$("#ajaxForm").ajaxForm({
type: ... ,
success: function(data){},
beforeSubmit : etc,
})
if u do sth wrong here , so u can see lots of repeating error Like 
status ...
status ...
then Try it .
use ajax form like Classic ajax

this is your form id myForm
then here is your code

$("#myform").ajaxForm(function(msg){

```
if(msg === ".."){
```

   Do that 
}
else {
do that}

});
here is your parameter or u can override them
<form action = "ur action page" method="get or post" enctype="multipart/form-data">

if u dont use enctype u cannot sende image *

the plugin takes the values in form 
for action , url , method
but if u wanna change
u can give it as parameter to plugin .
use it like classic ajax so its easy ;) then I thought u get rid of errors
