### ISSUE TITLE
$_POST deleted because of curly quotes

### ISSUE THREAD

**Issue by danoc** [jquery-form/form#118]
I've noticed that form.js is rejecting the curly single and double quotes. For example, "This can’t be true" results in nothing being sent via $_POST while "This can't be true" works totally fine. I believe the problem is because of the character encoding.

The console.log in the following code below generated the string below it: 

```
console.log(options.data);

// fire 'notify' event
this.trigger('form-submit-notify', [this, options]);
return this;
```

And this is the what it outputted:

```
item=This+can%E2%80%99t+be+true&list_id=30&submit=submit
```

When it gets to the PHP file, however... 

```
$this->firephp->log($_POST);
```

outputted....

```
array(
  ['item'] =>
  ['list_id'] => 30
  ['submit'] => 'submit'
)
```

What is going wrong here?

**Comment by kevindb** [comment]
Are you still experiencing this issue?
