### ISSUE TITLE
The 'type' option is no  effect in ie8 if the method  of the form is not set!

### ISSUE THREAD

**Issue by chuanjiabao1981** [jquery-form/form#123]
hi,malsup:
I am very glad to use your plugin.It is very help for me.
 Below is my question. The plugin version is 2.83.

=======script================
`

```
<script type="text/javascript">
    $(document).ready(function() { 
        var options = { 
            type:       'POST',
            url:        '/uploadimage',
    dataType:    'json',
    success:       showResponse
        }; 

    $('#submit_post_button').click(function(){
            $('#demopost').ajaxSubmit(options);
            return false;
        });
}
</script>
```

`

=======html=======================
`
    <form id="demopost"> 
    some html code
     <input id='submit_post_button' type='submit' name='submit_post' style="height:22px;font-size:12px;"></input>
    </form>
`
=======question===================

When I submit the form , Ie8 always send 'GET' method Not 'POST',which I set in the options.
At last ,I find these code do it.

`
    if ($.browser.msie && method == 'get') { 
            var ieMeth = $form[0].getAttribute('method');
            if (typeof ieMeth === 'string')
                options.type = ieMeth;
        }
`

I think the form should use the type that user set in the options.

thanks a lot

**Comment by mkurz** [comment]
I can confirm this bug.
I had to explicitly set the method of the form to "POST".

**Comment by joekarl** [comment]
Yeah had same issue. perhaps the form plugin should set the method on the form before the submit and then change it back to what it originally was afterwards?

**Comment by marcus** [comment]
+1 Having the same problem.

**Comment by bedney** [comment]
I'm experiencing this in other browsers besides IE. When I used an older version (version: 2.28) it worked perfectly, but it no longer does.

**Comment by Anahkiasen** [comment]
Having the same problem on latest Chrome.

**Comment by kevindb** [comment]
Are you still experiencing this issue?

**Comment by bedney** [comment]
@kevindb - It's been a very long time since I looked at this for the client, so I couldn't really say. Thanks for checking back.
