### ISSUE TITLE
options.error callback does not work

### ISSUE THREAD

**Issue by ghost** [jquery-form/form#124]
When I upload file, response status code=HTTP/1.1 500 Internal Server Error, options.error callback does not work, but I get success with status == 'success'. In Firefox browser. In IE9 all ok, but responseText == null

**Comment by quadracik** [comment]
I've just run into the same issue and I think the info from following link (one of comments the link directs to) should be included somewhere in the documentation since this is prpbably not obvious for many...
http://stackoverflow.com/a/7019723
