### ISSUE TITLE
Chrome & File Upload, 422 is reported as a success

### ISSUE THREAD

**Issue by evdevdev** [jquery-form/form#125]
I am not sure whether this is a problem with Chrome or with the form plugin, but if you use ajaxSubmit on a form with a file upload, the success callback always gets triggered. 

Chrome developer tools confirms that the status is 422. However, getDoc(io).readyState returns "complete" and this happens only once, before it calls success. 

In firefox, the console shows:

[jquery.form] state = uninitialized
[jquery.form] Server abort: Error: Permission denied for http://localhost:3000 to get property Window.document (Error)
[jquery.form] cannot access response document: Error: Permission denied for http://localhost:3000 to get property Window.document
[jquery.form] aborting upload... aborted

Has anyone encountered this? Any ideas for a work around?

**Comment by kevindb** [comment]
Are you still experiencing this issue?
