### ISSUE TITLE
Enhancement : we should be able to change the "Accept" header before sending the form.

### ISSUE THREAD

**Issue by ronhanson** [jquery-form/form#126]
Hi,
It would be useful for example to specify the Accept header to "application/json" to get a Rest server response in the good format. I can't find any easy way to change the accept header before submitting, it would be cool to have an option to do that.
Thanks for your great work btw.
Cheers,
Ronan

**Comment by shelhamer** [comment]
This is currently supported. You need to pass the 'dataType' option in the call to $.ajaxForm(). Like so:

``` javascript
$('#your-form').ajaxForm({
  dataType: 'json',
  success: function() {
  },
  .... etc ....
});
```

Refer to the [options reference](http://jquery.malsup.com/form/#options-object) for more.

**Comment by ronhanson** [comment]
Thanks shellhamer,
Still, tried again and from what I saw, on Google Chrome (v15) at least, the Request header "Accept" seems not changed and is still "text/html,application/xhtml+xml,application/xml;q=0.9,_/_;q=0.8" which is the browser default I think. I would like it to be something like "application/json".
From what I understand, the datatype looks at the Response header and parse it accordingly or you can override the way the result is parsed specifying a dataType value.
But my problem is related to the request header and not the final parsing of the response. And I can't do a "req.setRequestHeader("Accept", "application/json");" on beforeSubmit as I haven't got access to the req object at this point.
Maybe I miss something, sorry to bother you with that.
Cheers,
Ronan

**Comment by ronhanson** [comment]
I tried to use ajaxSetup prior to do my call to ajaxForm, doing:

```
                jQuery.ajaxSetup({
                  accepts: {
                    json: "application/json"
                  },
                  beforeSend: function(xhr) {
                    xhr.setRequestHeader("Accept", "application/json");
                  } 
                });
```

does not work either. The function beforeSend(xhr) is called but, from what I understand of the jQuery Form code, it seems that the xhr object is a mocked object and that setRequestHeader dont do anything.

Is this related to the use of iFrames?
Would there be a way or a hack to set the accept header myself?

Thanks again in advance.
Ronan

**Comment by kevindb** [comment]
When using iframes, the content-type header should be left as as text/html or text/plain.
https://github.com/jquery-form/form/issues/302#issuecomment-15300045
