### ISSUE TITLE
input type="submit" value and "fileUpload" function

### ISSUE THREAD

**Issue by freddez** [jquery-form/form#127]
Hi,
I want to emulate the <input type="submit" value="thevalue" />  in my "jquery.jframe" plugin : http://garage.pimentech.net/scripts_doc_jquery_jframe/

So I've added the submit value in 
beforeSubmit: function(formData, theform, options) { formData.push({ name:"submit", value: jQuery(input).attr("value") });
(where input is the submit button element)

But that breaks the fileUpload function of jquery.forms :

function fileUpload(a) {
        var form = $form[0], el, i, s, g, id, $io, io, xhr, sub, n, timedOut, timeoutHandle;
                var useProp = !!$.fn.prop;

```
    if (a) {
        // ensure that every serialized input is still enabled
        for (i=0; i < a.length; i++) {
            el = $(form[a[i].name]);  <==================================== here
            el[ useProp ? 'prop' : 'attr' ]('disabled', false);
        }
    }
```

Is it possible to catch that type of error (it only occurs in that function) ?

Thanks,
Fred

**Comment by freddez** [comment]
The problem is that form.submit is defined as a function, but I need to pass "submit" key in the request, as in "classic" http request

**Comment by vicary** [comment]
I guess the "beforeSerialize" option is the one you are seeking.

**Comment by freddez** [comment]
If I understand, beforeSerialize function permits to modify the DOM before form serialization. So if I want to pass an extra param, instead of doing

beforeSubmit: function(arr, theform, options) { arr.push({ name:"myparam", value: "myvalue" });

(wich works with regular post form)

I have to modify the DOM to add  an <input name="myparam" value="myvalue">

to deal with **enctype="multipart/form-data"** forms.

Ok, but it would be better to have the same behavior in regular and multipart forms :P
(I don't understand why you have to iterate to the corresponding form inputs of array in fileUploadIframe(a))

Anyway, thanks for your work and sorry for my limited English.

**Comment by vicary** [comment]
As long as the current security standard prevents XHR from uploading files, **multpart/form-data** has to be submitted at least from an iframe, DOM manipulation seems inevitable. This action is just automated in the plugin.

This looks very likely to be an extension to the already fixed [issue](https://github.com/malsup/form/issues/155), in another data manipulation point.
