### ISSUE TITLE
Issues with jQuery forms plugin - only when form contains <option> element

### ISSUE THREAD

**Issue by ints99** [jquery-form/form#13]
Hi,
I am using latest jQuery (v1.4.2) and form plugin (v2.43/2.45) versions. 

The plugin seems to have issue, i.e. when form contains option element, even commented out using , it starts to accept ajax submit only every 2nd time.

**Comment by ints99** [comment]
sorry for messy code sample, but otherwise html was not shown not at all...

**Comment by malsup** [comment]
Please provide a link that demonstrates the problem.
