### ISSUE TITLE
Upload content type confusion

### ISSUE THREAD

**Issue by jackysee** [jquery-form/form#130]
I'm using 2.84 version of the plugin and use it in an upload form. 

Originally, I expect when I post with accept `text/html`, the server response with `text/plain` and with `<textarea>` wrapped. 

But turn out that it does not work and cause file download in browser. If I change the response content type to `text/html`, in the options's `success` callback, the first argument is a string like `<textarea>{success:true}</textarea>`. And I have to strip off those tag (or just remove it from response) and do `JSON.parse()` to work.

So what's the correct content type? Should it be wrapped with `<textarea>`? It's quite confusing to me.

**Comment by kevindb** [comment]
Are you still experiencing this issue?
