### ISSUE TITLE
Using 'for in' to iterate over extended arrays breaks execution on IE 7

### ISSUE THREAD

**Issue by dot2code** [jquery-form/form#134]
# Summary

Using 'for in' to iterate over extended arrays breaks execution on IE 7. Simply replace them by normal for loops and the problem will be fixed.
# How do we found the problem
- Environment: Drupal 7 site (jquery.form.js 2.52 included in the core) using AJAX to submit some FAPI forms using IE 7. Twitter JS (http://widgets.twimg.com/j/2/widget.js) is included in the page.
- The problem: on Drupal form submit, $.fn.ajaxSubmit is executed (line ~46) and an exception raised on $.param(a) (line 109). 
- Explanation: when adding extra options to the array 'a' iterating over options.data[n](for loop on line ~91) some functions are added to the array (the Twitter JS library adds a couple of functions to the array prototype: filter & indexOf). Later, these functions break the $.param(a) statement. The problem is that using a 'for in' for these operation is wrong according to the JS reference (
  http://www.w3schools.com/js/js_loop_for_in.asp).
- Solution: replace the 'for in' loop by a normal for loop.

```
for (var k = 0, max = options.data[n].length; k < max; k++) {
```

Thank you!

**Comment by kevindb** [comment]
Are you still experiencing this issue?
