### ISSUE TITLE
XML content returned to iframe w/ file upload un-cases nodes

### ISSUE THREAD

**Issue by leeoniya** [jquery-form/form#137]
while trying to integrate the taconite plugin with the form plugin i ran into an interesting issue.

i was returning taconite xml into the iframe with `Content-Type: text/xml` as usual and setting up ajaxForm to handle the XML response via taconite as shown in the samples.

```
$('#form').ajaxForm({
  dataType: 'xml',
  success: $.taconite
});
```

doing this resulted in a taconite processing error that i traced to the fact that in XML extracted from the iframe every node returns an all-uppercase `.tagName`, regardless of the original case used and all `<replaceContent>` nodes were trying to invoke `REPLACECONTENT`.

for now i have worked around the issue by simply setting the `Content-Type: text/plain` on the server if any files were uploaded and setting up the handler to pass the XML as a string to `$.taconite`.

```
$('#form').ajaxForm({
  dataType: $("#form").find("input:file").length > 0 ? "text" : "xml",
  success: $.taconite
});
```

this seems to be okay as a workaround.

**Comment by kevindb** [comment]
When using iframes, the content-type header should be left as as text/html or text/plain.
#302 (comment)
