### ISSUE TITLE
If an error occurs when using ajaxSubmit and uploading a file, error & completed handlers aren't called.

### ISSUE THREAD

**Issue by scompt** [jquery-form/form#14]
This is happening because the DOM isn't available in the iframe after checking 100 times. When that happens, the code simply returns out of the 'cb' method without reaching the bottom where the callbacks are called. The consequence of this is that if an error occurs while uploading something, the spinner (or whatever in-progress signal is in use) never stops and the user doesn't know what's going on.

**Comment by scompt** [comment]
My fork (http://github.com/scompt/form) fixes this issue.

**Comment by malsup** [comment]
Good catch, thank you.
