### ISSUE TITLE
isDirty() check?

### ISSUE THREAD

**Issue by back-2-95** [jquery-form/form#142]
Can form plugin check is form is "dirty"? Meaning that something has changed in the form after
initial rendering.

If not, that would be nice feature. Then you could inform user, if he/she is leaving the page with modified information
which could be lost...

**Comment by mcka** [comment]
That will be a great feature

**Comment by malsup** [comment]
```
var dirty = false;

$('form').find(':input').change(function() {
    dirty = true;
});
```
