### ISSUE TITLE
ajaxForm + file input + disabled button beforeSubmit = missing button

### ISSUE THREAD

**Issue by peterpham** [jquery-form/form#144]
I have a form that containing a file input. When I use option "beforeSubmit" to disable the submit button, that disabled button will not be sent to the server.
Example code:

[CODE]
&lt;form id="uploader1" method="post"  &gt;
    &lt;input type=hidden name="myvar1" value=myvalue /&gt;
    &lt;input type=file name=myfile1 /&gt;
    &lt;button id="upload1" name="upload1" type="submit" value="Upload"&gt;Upload&lt;/button&gt;
&lt;/form&gt;

&lt;form id="uploader2" method="post"  &gt;
    &lt;input type=hidden name="myvar2" value=myvalue /&gt;
    &lt;input type=file name=myfile2 /&gt;
    &lt;button id="upload2" name="upload2" type="submit" value="Upload"&gt;Upload&lt;/button&gt;
&lt;/form&gt;

&lt;script type="text/javascript" src="scripts/jquery-1.6.1.min.js"&gt;&lt;/script&gt;
&lt;script type="text/javascript" src="scripts/jquery.form-2.63.js"&gt;&lt;/script&gt;

&lt;script language="javascript" type="text/javascript"&gt;
$('#uploader1').ajaxForm();

$('#uploader2').ajaxForm({
    beforeSubmit: function(arr, form, options) {
        $('#upload2').attr('disabled', true);
    }
});
&lt;/script&gt;
[/CODE]

In this example"
when pressing the submit button upload1, form fields  sent to the server include:
form.myvar1
form.myfile1
form.upload1

however, in second example, after pressing submit button, form fields sent to server only include
form.myvar2
form.myfile2

It appears that form.upload2 is missing.

Note: if there is no file input on the form, both examples behave the same, that is, in both cases, button name is sent along with other form fields.

**Comment by malsup** [comment]
That's a very old version of the plugin you're using.  Try with the latest.
