### ISSUE TITLE
doc.location.href is Protected variable on Opera?

### ISSUE THREAD

**Issue by talamaska** [jquery-form/form#145]
Uncaught exception: ReferenceError: Security error: attempted to read protected variable on line 395
Error thrown at line 339, column 3 in cb(e) in http://localhost/js/jquery.form.js
if (!doc || doc.location.href == s.iframeSrc) {

iframe mode
latest version of plugin + latest version of opera

**Comment by grapo** [comment]
This error occurs in my page but not always.

Linux, Opera 11.52, plugin version v2.92

**Comment by talamaska** [comment]
Yest it seems it's not always. This problem occurs only on my homepage "/", I've tested with same forms submitted on index page and other internal page.

**Comment by MalithRox** [comment]
hi guys.. I have the same issue, did you find any workarounds or solutions to this problem? I've been stuck with this issue for days now..

**Comment by kevindb** [comment]
Are you still experiencing this issue?
