### ISSUE TITLE
Some files do not upload using ajax method given

### ISSUE THREAD

**Issue by aslamdoctor** [jquery-form/form#147]
Some files do not upload using ajax method given and return null in $_FILES
Can you please resolve this? I tried the same files on your site here & there also same thing happened
http://jquery.malsup.com/form/#file-upload

**Comment by malsup** [comment]
What files? Maybe you're exceeding a size limit on the server.  For example, my page rejects files larger than 100K.

**Comment by aslamdoctor** [comment]
no that's not issue. I have maximum 50MB upload limit on my server. Some big files upload even larger than 1MB & some files do now. Those are .pdf format. I will send you the files in few hours.

**Comment by aslamdoctor** [comment]
Here is the file that is not getting uploaded
http://www.welancers.com/not_uploading.pdf

and please re-open this issue.
Thanks.

**Comment by behzadev** [comment]
Hello,

I also have the same problem, this is not related to file sizes, some files with allowed file size could be uploaded and some files couldn't!

I appreciate if anybody could help, also please kindly consider to reopening this issue.

Thanks

**Comment by malsup** [comment]
Are you sure about that?  The reason that file doesn't upload to my server is because it's too big.  The form plugin does a _native_ browser submit when uploading files.

**Comment by behzadev** [comment]
Yup, I'm kind of sure that this problem has nothing to do with file sizes,
I tested many files, and some smaller files also could not be uploaded.

I can also give you access to my test files which I have uploaded.

Please let me know.

Kind regards,
Behzad

On Mon, Nov 21, 2011 at 6:17 AM, Mike Alsup <
reply@reply.github.com

**Comment by malsup** [comment]
Can you provide a link to a _simplified_ test page that shows the problem?

**Comment by aslamdoctor** [comment]
Hi Malsup, we just tested the script again & found that someone added the below code in the form

http://pastebin.com/jANDS4Wa

And because of that, it was not uploading the files. So your code is correct.
