### ISSUE TITLE
xhr.setRequestHeader() for file upload

### ISSUE THREAD

**Issue by jamieorc** [jquery-form/form#148]
Wondering how to set request header to "Accept", "text/javascript" when doing a file upload. fileUpload() creates a mock xhr object, and wondering how to pass this along.

**Comment by malsup** [comment]
You can't set headers with the current implementation (for file uploads).

**Comment by jamieorc** [comment]
Not being familiar with the internals of jQuery myself, how simple or difficult would it be to add? I might give it a shot, but would love a pointer as to what to expose/add/whatever.

**Comment by malsup** [comment]
It's not possible with the current implementation of my plugin because when uploading files it does not use ajax, it performs a native browser submit (it simulates ajax).
