### ISSUE TITLE
Handle inputs without names correctly.

### ISSUE THREAD

**Issue by KendallHopkins** [jquery-form/form#149]
A form will not fully ignore files without names and will attempt to submit the form using `fileUpload`. I believe this is due to an incorrect selector @ line #154 (`var fileInputs = $('input:file', this).length > 0;`). It should probably be `$('input[name!=""]:file', this).length > 0;`.

```
<form>
    <input type="hidden" name="key" value="value"/> // submitted
    <input type="file"/> // not submitted, but still causes form to submit using fileUpload
</form>
```

**Comment by malsup** [comment]
It is.

**Comment by KendallHopkins** [comment]
@malsup Sorry, I found a bug that is a bit more specific and just assumed this feature was missing. I've updated my question.

**Comment by malsup** [comment]
That's intentional.  If there is a file input then the plugin uses it's fileUpload logic, regardless of whether or not a file is actually being uploaded.

**Comment by KendallHopkins** [comment]
But if the name is `""` there should be no case where it would be uploaded, even if it has a selected file. So why trigger `fileUpload`?

**Comment by malsup** [comment]
Why have that element on the form at all?

**Comment by KendallHopkins** [comment]
I'm using `$.wrap( "<form>" )` and `onchange` to create an inline subform that submits on selection of a file and then fills in the path to the file into a text field. I give the text field a name of `""` to prevent it from being submitted w/ the global form.

I could also see cases where you would change the name to `""` with jQuery for a `<input type=file>` so that it wouldn't be submitted.
