### ISSUE TITLE
ajaxSubmit doesn't work after hiding ("display:none") the form

### ISSUE THREAD

**Issue by ghost** [jquery-form/form#15]
On document.ready, bind a form to send ajax submissions with ajaxForm, and then submit it. 

After that,  using an element of your choice, eg: a button or a link, toggle the visibility of that form so that you can hide it and show it. 

Try to submit the form again, the form is not ajax anymore, it behaves like a normal form.

**Comment by malsup** [comment]
Please post a link to a test page that shows the problem.  Thanks.
