### ISSUE TITLE
"data" option gets ignored when submitted as "multipart/form-data"

### ISSUE THREAD

**Issue by vicary** [jquery-form/form#155]
As long as the form is natively submitted in an iFrame, the data I specified in ajaxSetup gets ignored.

``` javascript
$.ajaxSetup({
    data: { /* something */ }
});
```

This also fails.

``` javascript
$.ajaxSubmit({
    data: $.ajaxSetup().data
});
```

I guess a workaround should be hidden fields being automatically added during `beforeSerialize` event, and then remove them on `success`.

Please let me know if this is a good approach, I'd love to fork and give a patch over this issue. =)

**Comment by malsup** [comment]
Have you tried v2.93?

**Comment by vicary** [comment]
Just tested with 2.93 and the problem wasn't there anymore, thanks man!
