### ISSUE TITLE
From version 2.86 success callback always returns text/html

### ISSUE THREAD

**Issue by LaySoft** [jquery-form/form#157]
Hi!

In form plugin up to version 2.85 the success callback returns the real content type in xhr.getResponseHeader('content-type'). But from version 2.86 always returns text/html content type, independent what the server sends. It is big problem for me, because i have a small framework which uses the content type returned by form plugin, to decide what to do. Is there any other way to extract the real content type?

**Comment by kevindb** [comment]
Are you still experiencing this issue?
