### ISSUE TITLE
newline symbol correction for fields value before send to server

### ISSUE THREAD

**Issue by cgi-caesar** [jquery-form/form#158]
I believe last line of function $.fieldValue should looks like:

```
return $(el).val().replace( /\r?\n/g, "\r\n" );
```

Otherwise standard submit and ajax submit will result with different newline symbol on server script on linux machine. 

Please refer how jQuery serialize form. 

Best Regards.

**Comment by kevindb** [comment]
https://github.com/jquery/jquery/blob/master/src/serialize.js#L124
It makes sense to match jQuery core's serialization logic.
