### ISSUE TITLE
data from text area is duplicated

### ISSUE THREAD

**Issue by GusBeare** [jquery-form/form#16]
Hi

Thanks for taking over this repo. 

I have an issue with **textarea** tags in jquery form.  I have found that if I have something like this:

      <div class="">
                            <label for="Comment">Message</label>
                            <textarea cols="30" rows="8" id="Comment" form="ContactForm" tabindex="2" name="Comment" class="u-full-width"></textarea>
                        </div>

If the comment entered was:

    "here is the comment"

Then at the server I am seeing this:

    "here is the comment,here is the comment"

The text in the form post data is doubled up.

Gus

**Comment by kevindb** [comment]
Would you please include a link to a [JSFiddle](https://jsfiddle.net/) or [CodePen](https://codepen.io/) example of the error?

**Comment by GusBeare** [comment]
Sure, but it's easier said than done. I've set this up:  https://jsfiddle.net/h9nz8d01/

If I post the form I get the CORS error in chrome because it's not allowed to talk to my endpoint.

But if I save the post in chrome tools you get this:

[jsfiddle.net.txt](https://github.com/jquery-form/form/files/739047/jsfiddle.net.txt)

That's a json file representing the post.  In it you will see this:

     "postData": {
            "mimeType": "application/x-www-form-urlencoded; charset=UTF-8",
            "text":     "Name=asd&Comment=aasd&Email=gus%40carawaydesign.com&save=&Comment=aasd",
            "params": [
              {
                "name": "Name",
                "value": "asd"
              },
              {
                "name": "Comment",
                "value": "aasd"
              },
              {
                "name": "Email",
                "value": "gus%40carawaydesign.com"
              },
              {
                "name": "save",
                "value": ""
              },
              {
                "name": "Comment",
                "value": "aasd"
              }
            ]
          }

You can see that there are two params for "Comment". Hence dupes appear at the back end.

**Comment by GusBeare** [comment]
This proves there is no issue with my back end code. I think there is a bug specific to textarea tags where the content of a text area is added twice.

**Comment by GusBeare** [comment]
To verify if I comment out the jquery form code I get this:

 "postData": {
            "mimeType": "application/x-www-form-urlencoded",
            "text": "Name=asdas&Comment=here+is+IS&Email=gus%40carawaydesign.com&save=",
            "params": [
              {
                "name": "Name",
                "value": "asdas"
              },
              {
                "name": "Comment",
                "value": "here+is+IS"
              },
              {
                "name": "Email",
                "value": "gus%40carawaydesign.com"
              },
              {
                "name": "save",
                "value": ""
              }
            ]
          }

Which is fine. So the jquery form code somewhere is doubling up the Comment param.

**Comment by kevindb** [comment]
I think your issue stems from the fact that you have a `form` attribute on the `textarea` tag.
All of the fields that are decedents of the `form` tag are being parsed, and then all elements with the form _attribute_ are parsed, causing the `textarea` to be parsed twice.
According to MDN, the `form` attribute is not necessary, since the `textarea` is already a descendent of (inside of) the `form` tag.
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/textarea#attr-form

In your JSFiddle, when I removed the `form` attribute, the value is only submitted once.

**Comment by GusBeare** [comment]
ah great, thanks for spotting that.  So I guess if I moved the  `textarea` outside the form but kept the tag then it should work too.

**Comment by kevindb** [comment]
Yep, leaving the form attribute on and moving the field outside of the form tag _should_ also work.
