### ISSUE TITLE
error when using iframe upload on safari

### ISSUE THREAD

**Issue by wichert** [jquery-form/form#16]
I am seeing this on safari 5: when call ajaxSubmit() on a form with a file input I get an error "TypeError: Result of 
expression '(jQuery(this).data('form-plugin-onload'))' [null] is not a 
function.".  The fix in http://github.com/secelis/form/commit/0a056f168d0c8feab434d1d2022e3657da46ad99 appears to solve this, but I'm not sure it is the correct fix.

**Comment by malsup** [comment]
Fix implemented.
