### ISSUE TITLE
Include Test Suite in Github repository

### ISSUE THREAD

**Issue by petersendidit** [jquery-form/form#161]
What is the reasoning for not having the Test Suite (http://jquery.malsup.com/form/test/) in the github repository?  Seems like people are going to branch and fix/change things they should also have the test suite to run too.

**Comment by kevindb** [comment]
I have limited experience with getting a project started with unit tests (when none already exist).
@petersendidit would you please submit a pull request to get us started testing?

**Comment by kevindb** [comment]
Testing support has added. Run using `grunt test` or `/test/test.html`
