### ISSUE TITLE
Alter Data with beforeSubmit

### ISSUE THREAD

**Issue by iamjstates** [jquery-form/form#164]
How exactly could you alter data there, or is this the correct place to be changing the data?  I am sending an emtpy $POST to .ajaxSubmit then I would like to change the values with what I've collected in a dictionary.

I've tried

beforeSubmit: function(a,b,c){
   a.push(some-dict-values);
}

and nothing will post?  Any suggestions?

Big Thanks

**Comment by malsup** [comment]
```
beforeSubmit: function(a,b,c){
    a.push({ name: 'myName', value: 'myValue' });
}
```
