### ISSUE TITLE
Success doesn't fire when using fileUploadXhr

### ISSUE THREAD

**Issue by gazeth** [jquery-form/form#166]
Simple form, containing a single file upload, textarea and a few dropdowns. The call reaches the server fine, all data intact but the success or complete methods are never fired. The beforeSend fires fine.

**Comment by malsup** [comment]
Are you using the latest plugin version?  See example:  http://jquery.malsup.com/form/file-example.html

**Comment by gazeth** [comment]
Yes using the latest version, using it with .Net MVC3, jQuery 1.7.1
