### ISSUE TITLE
There should be option to use jQuery: on -event handler instead of bind

### ISSUE THREAD

**Issue by HenriVesala** [jquery-form/form#168]
In current state AjaxForm doesn't work with forms that are dynamically generated. This is a huge issue when you are using dialogs that displays forms. Now only options to fix this is either call AjaxForm every time when you update your dom with form or using Livequery.

**Comment by malsup** [comment]
Good idea.  Added delegation support to v2.96 (requires jQuery v1.7+).

```
$('#myForm').ajaxForm({
    delegation: true,
    // other options
});
```

**Comment by malsup** [comment]
Example:  http://jquery.malsup.com/form/delegate-test.html
