### ISSUE TITLE
Garbage response using fileUploadIframe

### ISSUE THREAD

**Issue by silvafj** [jquery-form/form#169]
Hi,

The following JSON response works great with Firefox, because it does not get parsed by fileUploadIframe(). When running the same code, through IE9, fileUploadIframe() is called and creates a bad response.

Original response:
{ "status": true, "data": "<table id=\"field_workorders_values\" class=\"content-multiple-table sticky-enabled\">\n... <\/script>" }

Response after being parsed:
{ "status": true, "data": "\n Workorders: <\/th>Order<\/th> <\/tr><\/thead>\n\n …

The offending code is this:
xhr.responseText = b.textContent ? b.textContent : b.innerText;

But I'm not being able to understand what the problem is.

Thanks,
Fernando

**Comment by silvafj** [comment]
Doing some testing (do not take the following code as usefull)

Changed:

``` javascript
xhr.responseText = b.textContent ? b.textContent : b.innerText;
```

to:

``` javascript
xhr.responseText = b.innerHTML;
```

But then I observed that the JSON response was being changed by the browser, adding some tags to the end of if.
This makes impossible to $.parseJSON(data);

**Comment by kevindb** [comment]
Are you still experiencing this issue?
