### ISSUE TITLE
file upload from iframe using firefox 3.6

### ISSUE THREAD

**Issue by wichert** [jquery-form/form#17]
I have a page which has a form in an iframe. This form is submitted using ajaxSubmit and the JSON response is then processed. This works until I submit a file: as soon as that happens jquery.form correctly adds a new iframe and change the target for the form to point to the new iframe. However when it calls form.submit() the response comes in with an application/json content type which triggers a 'Save As' dialog from firefox and no further processing is done from javascript.

**Comment by malsup** [comment]
Don't server that file with application/json header if you don't want the browser's default behavior.

**Comment by jstates** [comment]
So in essence this is a Firefox issue, as I have a similar problem.  If a issue a json callback it does not work at all.  What the solution? Something like html or xml? You method works fine in Webkit browsers?

**Comment by tizoc** [comment]
Try serving the response as plain text instead of application/json. For some reason when a file input is inside the form, Firefox tries to download the file.
