### ISSUE TITLE
Bug while using FCKEditor/CKEditor & File input together

### ISSUE THREAD

**Issue by aslamdoctor** [jquery-form/form#170]
I have created a form which contains the FCKEditor + File input box, and I am submitting the form using ajaxSubmit() method provided by this plugin. If I don't use File input box, the FCKEditor values submit properly but if I add File input box in the form, the updated content of FCKEditor do not get stored. It stores old values only. Any suggestions ? Thanks.

**Comment by kevindb** [comment]
Are you still experiencing this issue?
