### ISSUE TITLE
File uploads fail in IE 9 (server abort) since v2.81

### ISSUE THREAD

**Issue by Cryptarcadian** [jquery-form/form#172]
File uploads fail in Internet Explorer 9 immediately upon submission, and it is reported as a server abort
Tried ajaxForm and ajaxSubmit methods and pretty much every option

It seems to be related to the checkState function
The catch seems to be triggered in all cases?

Last version I tested that worked was v2.80 (959195e63cee98809314b6a902f2a29b4d2a00cc)

Doesn't seem to affect IE 8 or IE 7
Does affect IE 9 in Compatibility View mode

**Comment by Cryptarcadian** [comment]
I did see the "A fix for older browsers" issue as well (#171)
But the fix suggested there does not work

**Comment by malsup** [comment]
I'm not seeing this upload error with IE9.  Updated the main docs page to use latest and it seems to be working fine for me.  Win7 w/IE9 (32bit).

**Comment by Cryptarcadian** [comment]
Apologies for the year-late update, but I think it turned out to be an issue with IE and my testing.

(From memory, it was an issue with IE 9 deciding which security zone should apply in a way I didn't expect, based on automatically detected network settings. This lead to IE failing to submit the form, but it was only identifiable as an abort.)
