### ISSUE TITLE
I have to support cross-domain and we want to use the file upload.

### ISSUE THREAD

**Issue by youngjongsuh** [jquery-form/form#175]
You have made ​​good use of jquery.form.
But did not support cross-domain uploads
Now is a very difficult situation.

I ask a question please be able to use the information

Please check, please.

**Comment by hoorace** [comment]
chrome , firefox has no problem , you need set "('Access-Control-Allow-Origin' , 'your-domain');" on server . but it don't wrok on IE, I had got the same problem in IE.
