### ISSUE TITLE
uploadProgress only triggered for first file

### ISSUE THREAD

**Issue by kirkegaard** [jquery-form/form#176]
It looks like uploadProgress only gets triggered for the first file when using an input with multiple="true" attribute. Have anyone else had this problem?

**Comment by malsup** [comment]
How do you mean?  The progress event is for the fileset.  The position and total values in the callback should reflect that.

**Comment by kirkegaard** [comment]
I actually think this is because i was working locally. It was too fast and then the crunching of the images was taking so long that i thought it was only showing progress of the first one. Im sorry, my bad! :)

**Comment by malsup** [comment]
No worries.  Thanks for the update.
