### ISSUE TITLE
Upload Progress doesn´t work with iframe option

### ISSUE THREAD

**Issue by felipepessoto** [jquery-form/form#177]
Upload Progress doesn´t work with iframe option.

```
    // options.iframe allows user to force iframe mode
    // 06-NOV-09: now defaulting to iframe mode if file input is detected
    if (options.iframe !== false && (options.iframe || shouldUseFrame)) {
        // hack to fix Safari hang (thanks to Tim Molendijk for this)
        // see:  http://groups.google.com/group/jquery-dev/browse_thread/thread/36395b7ab510dd5d
        if (options.closeKeepAlive) {
            $.get(options.closeKeepAlive, function () {
                fileUploadIframe(a);
            });
        }
        else {
            fileUploadIframe(a);
        }
    }
    else if ((hasFileInputs || multipart) && fileAPI) {
        fileUploadXhr(a);
    }
    else {
        $.ajax(options);
    }
```

**Comment by malsup** [comment]
Sorry, I thought that was understood.  Upload progress is only supported with XHR uploads on Chrome, FF, Safari and IE10.

http://caniuse.com/xhr2

**Comment by felipepessoto** [comment]
I am using iframe on Chrome. Should I?

**Comment by malsup** [comment]
Are you forcing the iframe option?  If so, you won't be able to get progress updates.

**Comment by felipepessoto** [comment]
Yes, but I don´t know why. I think I did because I thought that was necessary to ajax upload file

**Comment by cirkuitdev** [comment]
I believe that you should not 'force' the iframe, but let the plugin decide when to use it (i.e. don't touch the iframe option). Then in your backend that handles the request (i.e. PHP), return your data in a &lt;textarea&gt; if:

$_SERVER['HTTP_X_REQUESTED_WITH'] != 'XMLHttpRequest'

It seems you'll then be able to use the uploadProgress callback for about 50% of the current market (as malsup points out here: http://caniuse.com/xhr2 )

See more here:
http://jquery.malsup.com/form/#file-upload
