### ISSUE TITLE
File upload sends multiple submit button name/value pairs

### ISSUE THREAD

**Issue by sabob** [jquery-form/form#18]
Using multiple submit buttons to upload files leads to situation where both buttons name/value pairs are submitted to the server, making it impossible to identify which button was clicked.

The problem occurs when using ajaxForm.

See the topic[1](http://forum.jquery.com/topic/jquery-form-file-upload-sends-multiple-submit-button-name-value-pairs) for more information and potential patch.

Regards, Bob

**Comment by malsup** [comment]
Pretty sure this has been fixed.
