### ISSUE TITLE
No feedback from PHP script

### ISSUE THREAD

**Issue by dejunky** [jquery-form/form#182]
Hi guys, I got a bit of a problem and I can't figure it out, the script seems to work and does send me the message once submitted but there is no feedback from the script to jQuery to display the message the the form has been sent, can someone check out my code and see if I'm missing something...? thanks in advance!
###### ###### HTML

<form id="contact_form" name="contact_form" action="###MY DOMAIN###/_lib/_scripts/form.php" method="post">
<input type="text" class="nameinput" name="name" tabindex="1" value="Name" />
<input type="text" class="emailinput" name="email" tabindex="2" value="E-mail" />
<input type="text" class="telephoneinput" name="telephone" tabindex="3" value="Telephone" />
<input type="text" class="locationinput" name="location" tabindex="4" value="Location" />
<input type="text" class="securityinput" name="security" tabindex="5" value="What is 2 + 4 (for security)" />
<textarea id="clear_textarea" name="comment" class="commentinput" rows="0" cols="0" tabindex="6"></textarea>
<input type="hidden" class="languageinput" name="sitelanguage" value="English Pages" />
<input type="submit" class="submitinput" value="Send message" title="Send message" name="Send message" style="padding:0px 2px 1px 2px;font-size: 1.4em; "/>

<div class="success_en" style="display:none;">Thank you, your message has been sent.</div>
<div class="badserver_en" style="display:none;">Please try again later.</div>
<div class="bademail_en" style="display:none;">All fields are required.</div>
</form>

###### ###### PHP SCRIPT

<? error_reporting(E_NOTICE);

```
function valid_email($str)
{
    return ( ! preg_match("/^([a-z0-9\+_\-]+)(\.[a-z0-9\+_\-]+)*@([a-z0-9\-]+\.)+[a-z]{2,6}$/ix", $str)) ? FALSE : TRUE;
}

    function valid_telephone($str)
{
    return ( ! preg_match("([0-9])", $str)) ? FALSE : TRUE;
}

function valid_security($str)
{
    return ( ! preg_match("(6)", $str)) ? FALSE : TRUE;
}

if($_POST['name']!='' && valid_telephone($_POST['telephone'])==TRUE && $_POST['location']!='' && $_POST['email']!='' && valid_security($_POST['security'])==TRUE && valid_email($_POST['email'])==TRUE && strlen($_POST['comment'])>1)
{
    $to = $_POST['name'].'<'.$_POST['email'].'>';
    $headers =  'From: '.$_POST['name'].'<'.$_POST['email'].'>'. "\r\n" .
            'Bcc: '.'###MY EMAIL###'.''. "\r\n" .
            'X-Mailer: PHP/' . phpversion();
    $subject = "Subject";
    $message = "Thank you";
    if(mail($to, $subject, $message, $headers))
    {
        echo 1; //SUCCESS
    }
    else {
        echo 2; //FAILURE - server failure
    }
    }
    else {
        echo 3; //FAILURE - not valid email
    }
```

?> 
###### ###### Form Plugin V3.02

$(document).ready(function(event) {
        $('#contact_form').ajaxForm(function(formData) {
                if (formData==1){
                        $('.success_en').fadeIn("fast");
                        $('.badserver_en').fadeOut("fast");
                        $('.bademail_en').fadeOut("fast");}
                else if (formData==2){
                        $('.success_en').fadeOut("fast");
                        $('.badserver_en').fadeIn("fast");
                        $('.bademail_en').fadeOut("fast");}
                else if (formData==3){
                        $('.success_en').fadeOut("fast");
                        $('.badserver_en').fadeOut("fast");
                        $('.bademail_en').fadeIn("fast");}
        });
});
###### ###### CSS

.success_en { right: -107px; float: right; padding-top: 4px; background-color: #f9f9f9; height: 25px; text-align: right;color: #50d37d; position: relative;z-index: 1000;}
.bademail_en, .badserver_en{ margin-top: 3px; right: 120px;text-align: right;color: #c80000; position: absolute;}

**Comment by dejunky** [comment]
Sorry the HTML part seems to have gone (?!) but it's just a normal form etc.

**Comment by kevindb** [comment]
Are you still experiencing this issue?
