### ISSUE TITLE
File upload + IE + parent tab = isn't working

### ISSUE THREAD

**Issue by vkotlyarov** [jquery-form/form#184]
Hi

We have very specific bug and it's reproducing even on your web-site : http://jquery.malsup.com/form/#file-upload.

If you will open some email in Gmail using IE, and in this email there will be a link to your page (http://jquery.malsup.com/form/#file-upload), by clicking on it - IE will create new browser tab and open this link there. But upload script isn't working in this case. It gives JS error: "SCRIPT5: Access denied. jquery.form.js, line 440 character 17" . 

As we discovered this problem we found that this bug occurs only in case IE+Gmail. We think that it tries (for some strange reason) to access parent window, in our case it's Gmail and of course it fails, because it's different domains.

**Comment by kevindb** [comment]
Are you still experiencing this issue?
