### ISSUE TITLE
Bug: input disabled="disabled" 

### ISSUE THREAD

**Issue by vicenteyu** [jquery-form/form#185]
Client:
&lt;input name="test1" value="0" /&gt;
&lt;input name="test1" value="1" disabled="disabled" /&gt;
&lt;input name="test2" value="2" disabled="disabled" /&gt;

Server:
Result:
Request.Form: "test1=0&test1=1"

True:
Request.Form: "test1=0"

**Comment by malsup** [comment]
I don't see that  behavior.  Can you post a link to a page that shows the problem?

**Comment by vicenteyu** [comment]
demo: http://temp.fornow.strawberry.arvixe.com/demo.htm

TestHandler.ashx:
<code>
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Fee
{
    /// <summary>


    /// TestHandler 的摘要说明
    /// </summary>


    public class TestHandler : IHttpHandler
    {

```
    public void ProcessRequest(HttpContext context)
    {
        context.Response.ContentType = "text/plain";
        context.Response.Write(context.Request.Form);
    }

    public bool IsReusable
    {
        get
        {
            return false;
        }
    }
}
```

}
</code>
