### ISSUE TITLE
Is it possible to change the target according to success or failure

### ISSUE THREAD

**Issue by vivekmyself** [jquery-form/form#186]
Hi

In ajaxSubmit() function is it possible to change the target according to success or failure. If there is some server side error target will be #failuremessage. If there is no failure and request is successfully completed target will be #successmessage.

I have a scenario like this, How can I achieve this?

Regards

Vivekmyself

**Comment by malsup** [comment]
Use the success and error callbacks instead.

**Comment by vivekmyself** [comment]
I tried but its not working as expected. Thats why I raised the question. 

Here is how I wrote, can you please correct me if I am wrong

success: function() {               

$('document').ready(function(){
    submitHandler: function(form){  
       $(form).ajaxSubmit({
          success:function() {  
              target: '#successmessage';
          },
         error: function() {
              target: '#failuremessage';
          }
      });
});

**Comment by malsup** [comment]
```
$(form).ajaxSubmit({
    success:function(data) {
        $('#successmessage').html(data);
    },
    error: function() {
        $('#failuremessage').html('An error has occurred.')
    }
});
```

**Comment by vivekmyself** [comment]
Thank you for your suggestion. This to I tried. But my requirement is 

If success I need to replace the form with the output data. If it is failure the form should remain same. I need to through the error message on top of the form. Thats why I use the "target".

**Comment by vivekmyself** [comment]
Got confused. Now got the solution. thank you for your fast reply.
