### ISSUE TITLE
AJAX File Upload not working on .live('change', fcn)

### ISSUE THREAD

**Issue by ChrisCates** [jquery-form/form#187]
```
$("#yourlogo").live('change', function() {
    $("#logoform").ajaxForm(function() {
        alert("Logo");
    });
});
```

So I have a standard form with just input for file, and, I want the file to be displayed as an image in a div after sucessful upload.

Unfortunately, I haven't been able to debug past this part. I was wondering if there was anything wrong with my code?

**Comment by malsup** [comment]
Use ajaxSubmit in that case, not ajaxForm.
