### ISSUE TITLE
Form plugin does not handle redirect response

### ISSUE THREAD

**Issue by hawkett** [jquery-form/form#19]
Google App Engine's blobstore upload handler http://code.google.com/appengine/docs/python/blobstore/overview.html#Complete_Sample_App mandates a redirect response, and it looks like the form plugin doesn't handle this properly, returning 'null' as the response text.  I'm guessing this is content of the redirect and not of the document returned by following the redirect.
More detail here - http://stackoverflow.com/questions/3080922/ajaxform-and-app-engine-blobstore

**Comment by malsup** [comment]
True, this is not supported by the plugin, nor is it supported by jQuery.ajax.  You can implement this yourself in the success handler by interrogating the 'Location' header of the XHR.  However, this will not work for responses to file uploads because header information is unavailable.
