### ISSUE TITLE
Double click on submit button

### ISSUE THREAD

**Issue by psgels** [jquery-form/form#194]
This is something I noticed when I was using your form plugin: suppose you have a form, and accidentally click on a submit button twice (which in a production environment is very likely to happen). When you do, the form in question gets submitted twice. Wouldn't it be better if in cases like this, the form only submits once instead?

Greetings
- Peter Gels

**Comment by prubin** [comment]
I worked around the problem by preventing a form from submitting twice at the same time.  I added this block at the top of ajaxSubmit:

```
if (this.attr('submitRunning') == 'true') {
    return this;
}
this.attr('submitRunning', true);
```

and the matching line after the loop processes the callbacks in optios.success:

```
options.success = function(data, status, xhr) { // jQuery 1.4+ passes xhr as 3rd arg
    var context = options.context || this ;    // jQuery 1.4+ supports scope context 
    for (var i=0, max=callbacks.length; i < max; i++) {
        callbacks[i].apply(context, [data, status, xhr || $form, $form]);
    }
    $form.attr('submitRunning', false);
};
```
