### ISSUE TITLE
protoype js conflict - this._each is not a function

### ISSUE THREAD

**Issue by michaljan-dev** [jquery-form/form#195]
Hi,
    var n,v,a = this.formToArray(options.semantic);
    if (options.data) {
        options.extraData = options.data;
        for (n in options.data) {
            if(options.data[n] instanceof Array) {

///////////////////////////////======= This should be change to construction with: array.length; ================///////////////////////
                for (var k in options.data[n]) {
                    a.push( { name: n, value: options.data[n][k] } );
                }
/////////////////=====================================////////////////////////////////
            }
            else {
                v = options.data[n];
                v = $.isFunction(v) ? v() : v; // if value is fn, invoke it
                a.push( { name: n, value: v } );
            }
        }
    }

**Comment by malsup** [comment]
I think you're looking at an older version of the plugin.
