### ISSUE TITLE
Request not sent when setting enctype and encoding on form element in IE7

### ISSUE THREAD

**Issue by ghost** [jquery-form/form#197]
Submitting a form with or without any inputs inside causes some kind of error in IE7 if I set encoding='multipart/form-data' and enctype='multipart/form-data' on _the form element itself._

It's hard to tell much without a good debugger, but I can say the request never reaches the server.

Of course, it works in Chrome and Firefox if these are set :)

**Comment by kevindb** [comment]
Are you still experiencing this issue?
