### ISSUE TITLE
Make resetForm function not affect hidden inputs in IE8 and earlier

### ISSUE THREAD

**Issue by elias6** [jquery-form/form#199]
Your resetForm function calls the native reset function which has different effects in IE8 and earlier than in other browsers. It clears the values of hidden inputs, even though it is not supposed to. You can read a description of this bug at http://stackoverflow.com/questions/10440551/simplest-way-to-prevent-form-reset-method-from-clearing-hidden-inputs-in-ie8 and see an example at http://jsfiddle.net/Ddtz4/. Is there any chance that this could be fixed in the Form plugin?

**Comment by malsup** [comment]
The "fix" is to put the initial value in the markup.  This really is not an IE bug and IE is not clearing the value, it's reseting it to its initial value.  Per the spec:

...when a form is reset, each control's current value is reset to its initial value. If a control does not have an initial value, the effect of a form reset on that control is undefined

http://www.w3.org/TR/html4/interact/forms.html#form-controls
