### ISSUE TITLE
iframe option vs XMLHttpRequest

### ISSUE THREAD

**Issue by gunzip** [jquery-form/form#2]
whe using the 'iframe' option an xhr mock object it's created. this prevent reusing a valid XMLHttpRequest object in ajax callbacks (ie. complete()).

**Comment by malsup** [comment]
Can you explain further?  When using the iframe option a real XMLHttpRequest object is not used.

**Comment by gunzip** [comment]
exactly that. if you pass a 'complete' option (as the documentation states that you can pass the same options as $.ajax) you don't receive a real XMLHttpRequest (as  callback parameter) but the mock object which is unuseful. (imho at least the doc should state that if you use 'iframe' option you _cannot_ use the same callback as in $.ajax)

**Comment by malsup** [comment]
Please understand that a "real" XMLHttpRequest object does not exist in the case where iframe option is used.  What information are you trying to get that is unavailable on the mock object?

**Comment by gunzip** [comment]
i tried to call xhr.getResponseHeader('Location') to get the url where i'm redirected after the post request when i realized that xhr was not a real XMLHttpRequest object (so, afaik there's no way to obtain that information after an ajax submit)

**Comment by malsup** [comment]
Correct. There is no way to obtain it from the request headers because they are unavailable (because ajax was not used).  You could embed that information as part of the response body, however, and deal with it in a custom way.

**Comment by gunzip** [comment]
thank you for the feedback (merely I cannot change the server code).
