### ISSUE TITLE
Parameters aren't properly serialized on multipart forms

### ISSUE THREAD

**Issue by kiafaldorius** [jquery-form/form#200]
If a nested object is passed as data in the $.ajaxForm/$.ajaxSubmit call, it currently doesn't properly serialize it. Current version raises an exception, a few versions previous it sent the object as "[object Object]".

For example:

```
{a: {'b': 5}, c: "ok"}
```

should get serialized as

```
a[b]=5&c=ok
```

previous versions sent this to the server

```
a=[object Object]&c=ok
```

current version on master throws an Exception (firefox 12.0)

```
Component returned failure code: 0x80460001 (NS_ERROR_CANNOT_CONVERT_DATA) [nsIDOMFormData.append]
```

Will submit a pull request to fix this soon once I setup a basic test case.

**Comment by kiafaldorius** [comment]
This should be the version on the current master. It fails with an exception: http://morning-robot-2113.herokuapp.com/multipart_fail.html

This is the successful deep-serialize, it suceeds: http://morning-robot-2113.herokuapp.com/multipart_success.html

**Comment by kiafaldorius** [comment]
Pull request created. Feel free to re-implement it if you feel it can be done easier/simpler/better.

Thanks!

**Comment by attiks** [comment]
I can confirm this problem with Drupal, background info can be found at http://drupal.org/node/1575060 and http://drupal.org/node/1574560

**Comment by attiks** [comment]
Is there a reason this cannot be committed?

**Comment by malsup** [comment]
Sorry.  Thought I merged this a long time ago.  Oops.

**Comment by attiks** [comment]
Any idea when a new release will be available?

**Comment by malsup** [comment]
Now.  http://malsup.github.com/jquery.form.js

**Comment by attiks** [comment]
Thanks ;-)
