### ISSUE TITLE
redirect

### ISSUE THREAD

**Issue by lexshine** [jquery-form/form#202]
trying to redirect after success. should something like this work because it doesn't. also tried about 100 other things that didn't. thanks..

<script type=\"text/javascript\">
        $(document).ready(function()
        {
            var options = {
              target: '#blah',
                  success: delayer
        };
            
        
        $('#details').ajaxSubmit(options);
            
function delayer(){
    window.location = 'http://www.mydomain.com'
}

 }); 
</script>

**Comment by lexshine** [comment]
nevermind, it was so obvious i missed it,

```
        $('#myForm').ajaxForm(function() { 
            window.location = 'http://www.mysite.com';
        });
```

**Comment by samdark** [comment]
@malsup close it please.
