### ISSUE TITLE
Minifying Causes the Form Plugin to Crash

### ISSUE THREAD

**Issue by opensaurusrex** [jquery-form/form#203]
I have tried several different minification scripts and it causes the script to fail.

**Comment by malsup** [comment]
Works fine for me.   

http://jquery.malsup.com/form/jquery.form.min.js

I used Google's Closure Compiler service.

http://closure-compiler.appspot.com/home

**Comment by opensaurusrex** [comment]
Oh ok, thanks mate. I appreciate the awesome work you have done.
