### ISSUE TITLE
IE 10 is not sending form body

### ISSUE THREAD

**Issue by ipeisong** [jquery-form/form#204]
A normal POST form won't send any input, the request body is empty but request header is normal.

in IE 10.0.8250.0

**Comment by quantizor** [comment]
Is that issue still there with the newest version of IE in Windows 8 RP?

IE10 is under active development, so functionality might be actually broken in the browser or methods changed.

**Comment by danielstankiewicz** [comment]
I confirm this is still an issue both in IE 10 and in IE 11 - the request body is empty. Tested on that page:

http://malsup.com/jquery/form/#file-upload

**Comment by kevindb** [comment]
Are you still experiencing this issue?
