### ISSUE TITLE
Passing a class selector does not work as expected.

### ISSUE THREAD

**Issue by jdodds** [jquery-form/form#21]
Sorry if I'm missing something obvious here, or if I'm doing something that just shouldn't work period, but I've searched around to no avail, and what I'm trying to do seems like a pretty obvious use case.

Say we have multiple forms on a page that we want to be able to turn into ajaxForms. Something like this:

```
<form method="post" action="/foo/bar" class="ajaxform">
  ...
</form>
<form method="post" action="/foo/quux" class="ajaxform">
  ...
</form>
```

I expected the following to work:

```
$(document).ready(function() { 
  $('.ajaxform').ajaxForm({...});
});
```

It does not.

**Comment by malsup** [comment]
Yes, that should work fine.  Here's a demo:
http://www.malsup.com/jquery/form/multi.html

**Comment by jdodds** [comment]
You're right, it does. So sorry to have wasted your time with this -- I had set my classnames to be ".ajaxform"  instead of just "ajaxform" and had one of those moments where you stare at the screen for 20 minutes trying to figure out why things aren't working correctly.

They weren't working correctly because I didn't have any elements with the class name I was working for -- just ones with the class name I was looking for with a period prepended to it.

Sorry!

**Comment by malsup** [comment]
No prob.  I've made that same mistake before.  Cheers!
