### ISSUE TITLE
File upload issue with Firefox 13

### ISSUE THREAD

**Issue by RobeeeJay** [jquery-form/form#211]
Related to closed issue #113, technically it's a new issue related to the same line of code (which fixing issue #113 has created)...

In Firefox 13, Line 175 of v3.09 of jQuery Form Plugin is returning an empty result which for results in submitting without the file data, or actually even as a file, it just gets sent as an object. :/

This may be a change in Firefox, which is protecting the value of the file input form field from being read by javascript, causing jquery to always think the file field is empty.

It's quite easy to fix, just remove [value] from the line, however it does probably cause issue #113 to occur again.

**Comment by malsup** [comment]
Just tested in FF v14 and it seems to be working fine.
