### ISSUE TITLE
How to use abort function on progress to cancel the upload?

### ISSUE THREAD

**Issue by amus** [jquery-form/form#212]
Hi:
I need some help to know how to use abort function on uploadProgress function?

Thanks!!!

**Comment by amus** [comment]
Hi,
I resolve this issue taking the xhr object on beforeSend and call abort function of this object...

I works for me, if someone have a better solution, please give me the idea...

**Comment by malsup** [comment]
This is an example of canceling an upload:

http://jquery.malsup.com/form/file-upload-cancel.html
