### ISSUE TITLE
Aborting an iframe upload in IE8

### ISSUE THREAD

**Issue by paftek** [jquery-form/form#214]
Hi,

The abort method of the XHR mock object has no effect in IE8.
I am using the latest version of the Form plugin: 3.09

The following line is not enough:

```
$io.attr('src', s.iframeSrc); // abort op in progress
```

Adding something like that around solves the problem (found on stackoverflow: [Is it possible to cancel file upload that uses hidden iframe?](http://stackoverflow.com/questions/5280855/is-it-possible-to-cancel-file-upload-that-uses-hidden-iframe)):

```
io.contentWindow.stop(); //for anything but IE
io.contentWindow.document.execCommand("Stop"); // for IE
```

I ended up with :

```
try {
    if ( $.isFunction(io.contentWindow.stop) ) {
    io.contentWindow.stop();
    }
    else {
    io.contentWindow.document.execCommand('Stop'); // IE browsers
    }
}
catch (ex) {
    log('cannot abort upload gracefully...' + ex);
}
```

Thanks!

**Comment by paftek** [comment]
I just had a look at your commit.

It will not work with Firefox : document.execCommand() is defined and throws an error (I'm using Firefox 14).
That's why I inverted the if / else and enclosed that into a try / catch.

But I admit that I'm not 100% satisfied by my submission :)

IE being the only real problem, maybe we could just do something ugly like:

```
try { if ( io.contentWindow.document.execCommand ) { io.contentWindow.document.execCommand('Stop'); }
catch (ex) { }
```

**Comment by malsup** [comment]
Good call, paftek.

**Comment by paftek** [comment]
To be perfectly safe, shoud not we use the getDoc() function in your last fix?
(But I do not know if such a function is still necessary with the modern browsers.)

**Comment by ceberle** [comment]
This now breaks IE9:

``` javascript
                // #214
                if (io.contentWindow.document.execCommand) {
                    try { // #214
                        io.contentWindow.document.execCommand('Stop');
                    } catch(ignore) {}
                }
```

I see an "Access denied" error in IE9 when it reaches the if statement. In debug, it appears trying to reference anything on `io.contentWindow` will do it...even `io.contentWindow.sdfsdf` will cause an "access denied" error.

Also, it seems a 500 error from the server causes it do act as though the ajax request was aborted.

Should I open a new issue?

**Comment by TheDistantSea** [comment]
@ceberle: I just finished debugging this same issue.

This happens because of the IE "friendly error messages" "feature". For HTTP 4xx and 5xx responses IE replaces the content of the IFRAME with its friendly error message and in so doing changes the domain of the frame. When the plugin tries to access the response document it fails due to the same-origin policy, which causes the plugin to treat the request as aborted (https://github.com/malsup/form/blob/master/jquery.form.js#L490).

You can work around this by sending content larger than 512 bytes with the response, which turns friendly error messages off. See http://support.microsoft.com/kb/294807/en-us.

**Comment by ceberle** [comment]
Thanks for the info, that's very helpful. I was planning on capturing the "abort" error and sending a separate Ajax call to get the actual error message, but padding the response with 512 bytes would be even easier.
