### ISSUE TITLE
X-Requested-With header not sending while uploading a file, only in IE

### ISSUE THREAD

**Issue by helpse** [jquery-form/form#222]
Hey guys, i want to congratz everyone on this plugin. Very nice one.

I just wanna report this issue, 
seems like the X-Requested-With header IS being set when uploading a file from Chrome and Firefox, but not for IE. I dont know if this issue can be fixed for IE. Thanks in advance :)

**Comment by malsup** [comment]
File uploads on IE do not use ajax, hence that header is not set.  IE10 will support ajax uploads, but for older version of IE this plugin simulates ajax while using a native form post.

**Comment by helpse** [comment]
Good to know the answer. I think we all look forward for the time when IE6,7,8,9 disappear, so the web development will become easier :D IE10 looks promising.
