### ISSUE TITLE
Compatibility with jQuery 1.8.0?

### ISSUE THREAD

**Issue by benrhere** [jquery-form/form#223]
Hi,

When I switch my site's jQuery from 1.7.2 to 1.8.0, upon doing an ajaxSubmit I get an "access is denied" error. Not sure if this is helpful, but this is the code block in jQuery that was highlighted for the exception.

return c=c||e,c=(c[0]||c).ownerDocument||c[0]||c,typeof c.createDocumentFragment=="undefined"&&(c=e),a.length===1&&typeof i=="string"&&i.length<512&&c===e&&i.charAt(0)==="<"&&!bt.test(i)&&(p.support.checkClone||!bw.test(i))&&(p.support.html5Clone||!bu.test(i))&&(g=!0,f=p.fragments[i],h=f!==b),f||(f=c.createDocumentFragment(),p.clean(a,c,f,d),g&&(p.fragments[i]=h&&f)),{fragment:f,cacheable:g}

Switching back to jQuery 1.7.2, it works fine. (IE9.)

Has anyone else see any issues using jQuery form with jQuery 1.8.0?

-Ben

**Comment by hotmeteor** [comment]
From the jQuery API docs: http://api.jquery.com/jQuery.ajax/

> Deprecation Notice: The jqXHR.success(), jqXHR.error(), and jqXHR.complete() callbacks will be deprecated in jQuery 1.8. To prepare your code for their eventual removal, use jqXHR.done(), jqXHR.fail(), and jqXHR.always() instead.

I think that things are breaking 1.8 due to deprecated callbacks.

**Comment by leolimas** [comment]
I am also having the same problem, is there any estimate of when we will have a version compatible? I tried to see if I could find where I change the code but without success.

Thanks

**Comment by hotmeteor** [comment]
Basically, the code change that's require is to attach the `jqXHR.done()`, `jqXHR.fail()`, and `jqXHR.always()` callbacks to the $.ajax function in replacement of `success` and `error`. I see where it's done, it'll just take a bit of tinkering.

On the latest version that function is on lines 202 and 262 (for file upload).

**Comment by malsup** [comment]
Can someone post a simple example page that fails?  The test suite uses jQuery 1.8 and does not fail:

http://jquery.malsup.com/form/test/

And the main docs site uses 1.8 as well:

http://jquery.malsup.com/form/#file-upload

Also, "deprecate" does not mean anything has been removed.  It means they will be in the future.

**Comment by benrhere** [comment]
I'll try to put together a repro for this in the next few days. I think that to repro, the form being submitted needs to contain a file, and it needs to be done in IE9 (or possibly earlier).

**Comment by benrhere** [comment]
I've since upgraded my machine to Windows 8 (and hence IE10). I no longer see this. I'll have to find access to IE9 somewhere to try to reproduce this (if someone else can't reproduce it first).

**Comment by hotmeteor** [comment]
I think it's still worthwhile updating to the new jqXHR syntax regardless. I know we are using those new callbacks going forward.

**Comment by malsup** [comment]
The form plugin does not call those deprecated methods.  The success/complete ajax option _properties_ are not deprecated.

**Comment by hotmeteor** [comment]
Too right, my bad.

**Comment by hotmeteor** [comment]
Mike, I guess what I'm hoping to get is access to the $.ajax call that's being perform for an ajaxSubmit (or ajaxForm) so that I can use the .done, .fail, and .always callbacks on them. Is this possible?

**Comment by malsup** [comment]
You can use any ajax options with the form plugin. So for example, use beforeSend and in that callback you'll get the jqXHR.

**Comment by hotmeteor** [comment]
Yep, I totally get that. But these callback methods are slightly different than just options. I'm referring to the jqXHR Object that is returned by $.ajax, and the methods that I can use with that.

See: http://api.jquery.com/jQuery.ajax/#jqXHR

**Comment by malsup** [comment]
The jqXHR is passed to beforeSend

```
var myXHR;
$('form').ajaxSubmit({
    beforeSend: function(jqXHR, settings) {
        myXHR = jqXHR;
        myXHR.done(function() { ....
    },
    ...
});
```

**Comment by hotmeteor** [comment]
Ah... alright. Thanks for your patience in clearing this up, and sorry if I've hijacked this issue.

**Comment by malsup** [comment]
No worries!

**Comment by leolimas** [comment]
Using jQuery 1.8 and IE 9 this simple code fails with access denied message... 

``` javascript
$("#formulario-box").ajaxForm({
    dataType: 'json',
    beforeSubmit: function (formData, jqForm, options) {
        if (!jqForm.validationEngine('validate')) {
            return false;
        }
        $.blockUI({ theme: true });
    },
    success: function (responseText, statusText, xhr, $form) {
        alert("TEST");
    }
});
```

**Comment by malsup** [comment]
There must be more to it than that because I have plenty of examples where that same code works just fine.  Can you post a link to a simplified test page which demonstrates the error you're seeing?

**Comment by benrhere** [comment]
I think I may be narrowing this down. Leolimas, I'm curious: in your code that fails, do you use the Facebook javascript API?

**Comment by benrhere** [comment]
I've got more info. I wasn't able to repro this on IE10, but I did repro what I believe is another issue possibly of the same root cause. I conclude that because:

-Both give the same error in the same line of jQuery
-Both can be resolved by either jumping down from jQuery 1.8 to 1.7.2, or by commenting out the same code (see example)

So, here's the repro:

http://jsfiddle.net/gkgXL/3/

To repro, click in the textbox and type 'o' (to trigger a typeahead match). You should get an access denied error. Make sure your browser is set to display all javascript errors. In IE10, this is off by default. I reran in the non-minified jQuery code to get a clearer idea of where the problem is:

jQuery.buildFragment = function( args, context, scripts ) {
    var fragment, cacheable, cachehit,
        first = args[ 0 ];

```
// Set context from what may come in as undefined or a jQuery collection or a node
context = context || document;
context = (context[0] || context).ownerDocument || context[0] || context; ************
```

(I put some asterisks next to the relevant line above.)

There are two ways to get rid of the problem. Either works:

-Switch from jQuery 1.8.0 to 1.7.2 (from the dropdown) or
-Comment out from the javascript view the line that starts with "FB.init"

Rerun, and put an "o" in the textbox. Values should populate.

Because it seems like this problem is affecting bootstrap's typeahead in addition to (possibly) this plugin makes me wonder if this isn't a problem in the Facebook code. I'm going to post this in the bootstrap github, but I thought it might be relevant here. If you don't think so, feel free to close this.

Thanks!

-Ben

**Comment by malsup** [comment]
Thanks for all the info, it's definitely relevant.  I'm just not sure there is tangible issue with the Form Plugin or not.

**Comment by leolimas** [comment]
Hi,

Sorry for the delay to answer, yes I'm using the facebook "Like" script too, but nothing relative with this script that uses the form plugin.

By the way I'm using the old jQuery version until we got a solution to this issue, I'm finishing the first public version and I will publish it soon.  

Thanks

**Comment by benrhere** [comment]
Hey Leonardo,

Yes, it seems like you're facing the same issue. I've posed a repro (see above) for what I think is the same problem, and the problem seems to occur even if the only thing you do is call "FB.init". I'm not really sure yet about what's going on.

-Ben

**Comment by benrhere** [comment]
Here's an update. Looks like jQuery is aware of this:
http://bugs.jquery.com/ticket/12266
There's a workaround posted inside.

**Comment by malsup** [comment]
Deferred support improved.  Example:  http://jquery.malsup.com/form/deferred.php

**Comment by franjgg** [comment]
Hello as this malsup

I had a question for you, I am implementing the progress bar http://jquery.malsup.com/form/progress3.html specifically but not get it to work in IE8, is there any way that works for this browser?

Without further a Greeting

**Comment by malsup** [comment]
No, progress updates do not work on IE versions below 10.
