### ISSUE TITLE
success not called if set in formSubmit

### ISSUE THREAD

**Issue by gergelypolonkai** [jquery-form/form#226]
If I use

{
    success: function(data) {...}
}

in options for ajaxSubmit, it doesn't get called. If I move it to the ajaxForm() call, it works like charm. I don't know if it's intentional, but if so, it should be mentioned in the docs.

**Comment by malsup** [comment]
Do you have an example of that not working that you can post a link to?

Here's an example of it working as intended:
http://jquery.malsup.com/form/#ajaxSubmit

**Comment by tyler-sommer** [comment]
This is also happening to me. Using jQuery 1.8.1 and jQuery Form 3.15

My usage is from within the jquery validate submitHandler option:

``` javascript
$.validator.setDefaults({
  // ...
  submitHandler: function(form) {
    console.log('submitHandler called'); // This gets called
    $(form).ajaxSubmit({
      dataType: 'json',
      success: function() {
        console.log('success handler called'); // This is never called
      },
      complete: function() {
        console.log('complete handler called'); // This *is* called, presumably because it is just passed through and not modified by jQuery Form
      }
    });
  }
});
```

I've traced it through to where the success handler is pushed onto the stack of callbacks, and then it looks like the actual handler is overwritten with a new handler (line 167) but after that my javascript-fu fails me.

**Comment by malsup** [comment]
More likely you actually have an error, not success.  Try adding an error handler as well.

**Comment by tyler-sommer** [comment]
Ahhh what a fool I am. That was it! Thanks
