### ISSUE TITLE
Clicked input not submitted with HTML5 form-associated elements

### ISSUE THREAD

**Issue by IwanVosloo** [jquery-form/form#227]
HTML5 allows one to have inputs that are not physically contained within a form, yet are still seen as part of that form ( see http://dev.w3.org/html5/spec/single-page.html#form-associated-element ).

When one uses the jquery forms plugin with such a form, and click on an input that is not contained inside the form, the clicked element is not submitted by this plugin.

See the example at: http://jsfiddle.net/IwanVosloo/jpnFe/

When you click on The Upload button, one expects 3 alerts: one for bb, one for file, and one for upload. But upload never happpens.

**Comment by kevindb** [comment]
I am closing this issue due to a lack of activity. If you still need help, please comment and we can reopen.
