### ISSUE TITLE
IE 9 + fileupload: submit-URL is loaded if it contains a frame breaker script

### ISSUE THREAD

**Issue by xong** [jquery-form/form#228]
Hi,

thank you for this very useful plugin.

I have found a very anoying bug of IE which cost me over 8 hours.

If the receiver page of the form you want to submit to has a frame breaker script, IE 9 executes this code when the return data is fetched by your script. That means he loads the receiver page after the data was submitted.

Other major browsers showed no such behavior. I was not able to test other versions of IE but I think there is a good chance, that the problem exists there, too.

You can verify the Problem at http://maumha.de/rex/jquery-form-bug.php. Just click the send-button.

The problem occures because of the frame which is used to upload a file.
You can avoid this by not using the frame breaker script, but maybe you will find a better solution.

I hope this helps you.

Regards,
Robert

**Comment by fruwe** [comment]
FYI: Also setting X-Frame-Options to DENY in your http server settings will brake it...

**Comment by kevindb** [comment]
Are you still experiencing this issue?
