### ISSUE TITLE
Chrome 21.0.1180.89 m

### ISSUE THREAD

**Issue by felipesomolinos** [jquery-form/form#229]
With the latest jquery form and latest jquery, the ajaxForm success renderer is loading the json response instead of executing the callback function. 

I've searched a little about this issue, but found nothing. Is there any workaround?

Thanks.

Felipe Gabriel

**Comment by malsup** [comment]
I haven't been able to duplicate this.  Do you have a simple test page that shows the problem?

**Comment by malsup** [comment]
LOL, now that I think about it, the beforeSend callback already gives you the jqXhr as the first arg.

```
var xhr;

$('#myForm').ajaxSubmit({
    beforeSend: function(jqXhr) {
        xhr = jqXhr;
    }
});

xhr.done(...);
```

**Comment by felipesomolinos** [comment]
Hi,

After some research, I've found the source of the issue. There was two versions of jquery library declared, one in the main page, and the other into a html that is rendered inside a div using the tab function (jquery-ui).
I've already solved this.

Thanks!

Felipe

**Comment by malsup** [comment]
Ok, thanks.
