### ISSUE TITLE
ResponseText is null in case of Error response

### ISSUE THREAD

**Issue by ghost** [jquery-form/form#230]
Hi,

I have popup on which I upload files.

In case of Mozilla Firefox the pulgin is working fine. However in case of IE, I am facing an issue.
I am writing an ajax error json respone in case of any java exception from server.
I debug, the issue I found that you prepare mock object called

 xhr = { // mock object
            aborted: 0,
            responseText: null,
            responseXML: null,
            status: 0,
            statusText: 'n/a',
            getAllResponseHeaders: function() {},
            getResponseHeader: function() {},
            setRequestHeader: function() {},
            abort: function(status) {
                var e = (status === 'timeout' ? 'timeout' : 'aborted');
                log('aborting upload... ' + e);
                this.aborted = 1;
                // #214
                if (io.document.execCommand) {
                    try { // #214
                        io.document.execCommand('Stop');
                    } catch(ignore) {}
                }
                $io.attr('src', s.iframeSrc); // abort op in progress
                xhr.error = e;
                if (s.error)
                    s.error.call(s.context, xhr, e, status);
                if (g)
                    $.event.trigger("ajaxError", [xhr, s, e]);
                if (s.complete)
                    s.complete.call(s.context, xhr, e);
            }

Here I can clearly see that responseText is null and is never populated in case of IE. Even inspecting the HTML I found that  the dummy iframe that you create is not having anything in its inner HTML.

IE 9.0 is the version of IE am working

**Comment by malsup** [comment]
responseText is populated well after the block of code you pasted above.  What exactly is your server response?

**Comment by ghost** [comment]
In case my code breaks at server, the server sends the HTTP status code say 500. First point is In error callback I got responseText as null what I registered instead what I send which was error json
(e.g say error:{ERRORCODE : ERROR MSG}). 

To rectify this issue I had to set the HTTP status code manually to 200 and collect error JSON in responseText.

Please let me know do I need to explain more.

**Comment by kevindb** [comment]
Are you still experiencing this issue?
