### ISSUE TITLE
Firefox & empty response

### ISSUE THREAD

**Issue by rekna1** [jquery-form/form#232]
When the submit returns an empty string as result, firefox seems to assume that the response type is xml. Because of this, inserting this empty string in the target fails.

In chrome and IE this works without any problem....

I tried to specify dataType = 'html', but I saw in the options this is not supported, and also when datatype is not null, the behaviour of the plugin changes: load on the target is not performed when the datatype is not null...

**Comment by malsup** [comment]
Do you have a test page?  I'm unable to duplicate this in FF/Mac.

**Comment by jarrettv** [comment]
I can duplicate on a different project

**Comment by malsup** [comment]
Test page?

**Comment by rekna1** [comment]
difficult to write a test page, because you need to have some server to return data...
could you just allow specifying datatype for the ajax request, this might solve the problem.

**Comment by kevindb** [comment]
Are you still having this issue?
