### ISSUE TITLE
ajaxSubmit does not expose nor return handle to ajax promise

### ISSUE THREAD

**Issue by AndrewRayCode** [jquery-form/form#234]
http://api.jquery.com/jQuery.ajax/#jqXHR

```
The jqXHR objects returned by $.ajax() as of jQuery 1.5
implement the Promise interface, giving them all the
properties, methods, and behavior of a Promise (see
Deferred object for more information)
```

So in normal jquery code you can do

```
$.ajax({ ... }).then(function() { ... }).done(function() { ... }).fail(function() { ... })
$.post({ ... }).then(function() { ... }).done(function() { ... }).fail(function() { ... })
// etc
```

Promises are very powerful and jQuery has adopted them as their core async flow control. An async jQuery form plugin that mimics the ajax method seems like it should return one or a way to get it. From browsing the code I don't see any exposed ajax objects.

Since `ajaxSubmit` takes the same arguments as `$.ajax` so it seems very logical that it would return a promise object instead of the form element, or expose a way to get it. `$form.ajaxSubmit().promise()` does not work since it's only grabbing the form element's deferred object.

**Comment by malsup** [comment]
Made a quick change to allow access to the jqxhr.  The plugin will now add a property to the settings object called 'jqxhr' and that will be available in callbacks, like beforeSend.  I can't change the return type on that method because it is and always has been a plugin method that returns a jQuery object.  This change isn't ideal, I know.

**Comment by AndrewRayCode** [comment]
Could you give an example usage to access it with your above changeset?

What about another jquery.fn like `.ajaxSubmitPromise()` so you could do `$form.ajaxSubmit().ajaxSubmitPromise().then...` ? Just a thought.

**Comment by malsup** [comment]
jqxhr object is now stored in element data.  Example:  http://jquery.malsup.com/form/deferred.php

**Comment by playmono** [comment]
We are using ajaxSubmit in our projects and since we are migrating to new standard Javascript and good practises, is a pity this cant be implemented :(.

If someone has a nice and clean workaround we are here to listen :)
