### ISSUE TITLE
Strange problem $_FILES[file] is seen as $_POST['file']

### ISSUE THREAD

**Issue by yourchoice** [jquery-form/form#236]
Hi,

Just I want to inform you, that I saw a strange problem: when sumit a form with files, after sumbit exists $_POST['file']

So everytime where I use <input type="file" name="file_1"> after sumbit isset($_POST['file_1']) is set.

This neever need to be set. Set need to be just $_FILES['file_1'].

Please let me know how can be solved this .

Best regards,

Florin C.

**Comment by Yohn** [comment]
I noticed something like that when no file was selected to upload.

**Comment by kevindb** [comment]
Are you still having this issue?
