### ISSUE TITLE
Can't change the data ajax send

### ISSUE THREAD

**Issue by wd** [jquery-form/form#237]
We need to send json string data in our project, So I try to set it in beforeSubmit use something like 

``` javascript
options.data = jsonStr;
```

But it's not work, it seems the data is read-only.

I also tried to set the data like

``` javascript
                $('#user-form').ajaxSubmit(
                    {
                        url: '/api/user_update.json',
                        dataType: 'json',
                        contentType: 'application/json; charset=UTF-8',
                        success: function (res, tatusText,                    console.log(res);
                        },
                        data: jsonStr,
                        beforeSubmit: function(formData, jqForm, options) {
                            console.log(options.data);
                        },
                        type: 'POST'
                    }
                );

```

But the data send the server is very strange. So ajaxSubmit do not support change the data we send? I've tried $.ajax, it's worked.

**Comment by malsup** [comment]
You probably want to do something like this:

```
data: { myJSON: jsonStr },
...
```

**Comment by wd** [comment]
It's not work too. I've tried

```
data: { j: jsonStr },
```

j=urlencode(jsonStr) will append to the original data, not replace it.

**Comment by kevindb** [comment]
Are you still experiencing this issue?

**Comment by monkey001127** [comment]
I did it, and it worked, but I don't know if it would cause any problems.

beforeSubmit: function(formData, $form, options) {
          formData[0].value = 'new value';
            return true; 
        }
