### ISSUE TITLE
Input with native javascript property as name

### ISSUE THREAD

**Issue by b2pweb** [jquery-form/form#238]
On IE6 - 7 - 8, when an input field is named with a native javascript array property (i.e. "length"), the ajaxForm function doesn't send any data.

``` html
<form method="POST" id="formTest" name="formTest">
    <input type="text" name="length" value="3" />
    <input type="submit" value="Tester" />
</form>
```

The problem is from formToArray function, which treats a collection of javascript objects ("els") :

``` javascript
$.fn.formToArray = function(semantic, elements) {
    var a = [];
    if (this.length === 0) {
        return a;
    }

    var form = this[0];
    var els = semantic ? form.getElementsByTagName('*') : form.elements;
    if (!els) {
        return a;
    }
```

To fix this, we can call the jQuery makeArray function when listing the elements in order to work with an array instead of HTMLCollection object :

``` javascript
var els = $.makeArray(semantic ? form.getElementsByTagName('*') : form.elements);
```

**Comment by kevindb** [comment]
Are you still experiencing this issue?
