### ISSUE TITLE
with IE  Nothing happenning in rails on ajaxSubmit();

### ISSUE THREAD

**Issue by ketanjm** [jquery-form/form#239]
Hi ,

   I am using  latest plugin with rails3  working superb on ff but for IE and other browser   nothing  happening   .

 using  jquery v1.4.4 tried diff also .

   is it possible to  made it  IE workable ? .

   my implementation in code :

<script>
 $(document).ready(function() {
   $("input[type='file']").change( function() {
     $("form#upload").ajaxSubmit();
  });
});
</script>

in my form 

<%= form_for(@post, :html => {:id => "upload", :multipart => true}, :remote => true) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

```
  <ul>
  <% @post.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
  <% end %>
  </ul>
</div>
```

  <% end %>
  <%= f.file_field :file%>
  <div class="actions">
    <%#= f.submit %>
  </div>
<% end %>

**Comment by kevindb** [comment]
Are you still experiencing this issue?
