### ISSUE TITLE
ajaxSetup data not being sent with ajaxForm

### ISSUE THREAD

**Issue by Yohn** [jquery-form/form#242]
hey man, i gotta say I love your form plugin, and been using it for quite some time now without any problems..

tonight I found found a bug in my script that required me to pass another value to my submitting pages, so I figured i could use ajaxSetup to add that extra value to all my forms, so I included this at the top of those pages that needed it

``` javascript
$.ajaxSetup({data: {checkSum: 'secret key'}})
```

and I noticed that it worked fine for all my $.post ajax requests, but when I used the `$().ajaxForm` to send the data, the `checkSum` wasnt being included.

I can go through and edit all these pages to hold that value, which is what I'm prolly going to do, but it would be good if the ajaxSetup worked..

I'm using version: 3.18 of jquery form, jquery 1.8.2 and firefox v.16

**Comment by evitolins** [comment]
I'm having this same issue.  +1

jQuery v1.10.1
form: 3.46.0-2013.11.21

**Comment by kevindb** [comment]
Possibly resolved by #506
