### ISSUE TITLE
Issue with iframeTarget and on IE7 with the form in a different document

### ISSUE THREAD

**Issue by emasab** [jquery-form/form#246]
I've noticed a couple of problems when the plugin uses an iframe on version 3.17

1) if you use iframeTarget the onsubmit event handler is not attached to the provided iframe, so the success callback is never called

2) on IE7, if the form is on another document than jQuery, it doesn't work because it tries to attach some elements created with the jQuery document to the form document. And IE7 does not allow this.

I've fixed this problem on version 3.17, the one I'm using. And here's my fixed version

http://pastebin.com/3PQGzBR6

Thanks for this useful extension.

**Comment by malsup** [comment]
What changes did you make besides this one?

```
$io = $(s.iframeTarget, form.ownerDocument);
```

**Comment by emasab** [comment]
there's also

``` javascript
if (!s.iframeTarget) {
    // add iframe to doc and submit the form
    $io.appendTo($form.closest('body'));
}

if (io.attachEvent)
    io.attachEvent('onload', cb);
else
    io.addEventListener('load', cb, false);
```

instead of

``` javascript
if (!s.iframeTarget) {
    // add iframe to doc and submit the form
    $io.appendTo('body');
    if (io.attachEvent)
        io.attachEvent('onload', cb);
    else
        io.addEventListener('load', cb, false);
}
```

there is the $form.closest('body') to address the second problem and the addEventListener has been put outside the if(!s.iframeTarget) to address the first problem.

**Comment by emasab** [comment]
however you can check all the differences with a visual diff tool like Meld or Winmerge. There are three other points besides that one where I've put form.ownerDocument

**Comment by malsup** [comment]
@emasab can you please submit a pull request against the latest version of the plugin?  I'll merge your changes.  Thanks.
