### ISSUE TITLE
htmlspecialchars in data

### ISSUE THREAD

**Issue by tamtakoe** [jquery-form/form#247]
I use

<pre>var mydata = {opt1: '1', opt2: '2'}
$(this).ajaxSubmit({ 
    type: 'post',
    dataType:  'json', 
    data: {'mydata': encodeURIComponent(JSON.stringify(mydata))}        
})</pre>

and php get {opt1:&quot1&quot,opt2:&quot2&quot} and json_decode break down

Better, if i can write

<pre>data: {'mydata': mydata}</pre>

and jquery.form convert it as encodeURIComponent(JSON.stringify(mydata))

The best, if i can write 

<pre>sendType: 'json',
data: {'mydata': mydata}</pre>

and jquery.form convert it as encodeURIComponent(JSON.stringify({formparameters..., opt1: '1', opt2: '2'}))

**Comment by kevindb** [comment]
Are you still experiencing this issue?
