### ISSUE TITLE
AJAX File Upload with redirect and script evaluation on firefox 3.6

### ISSUE THREAD

**Issue by mcculloughsean** [jquery-form/form#25]
I'm using this file upload script so users can upload a video to Youtube. The workflow requires that the video be uploaded to youtube's servers, which responds with a redirect to a URL supplied in the form action. The redirect contains the ID of the video, the status of the request, and any user-supplied data necessary. My implementation called for the redirect to return server-generated javascript to modify the page inline to show success or failure.

Basic implementation was:

```
$('#video_upload_form').ajaxForm({
  iframe: true,
  beforeSubmit: function(a,f,o) {
    o.dataType = 'script'; 
    nexturl = $('#nexturl').fieldValue()[0];
    title = $('#title').fieldValue()[0];
    nexturl = $.param.querystring(nexturl, { "title": title});
    o.url = $.param.querystring(o.url, {"nexturl": nexturl});
        $('#nexturl').remove()
    $('#title').remove()

  }
})
```

Ignore the url manipulation. I need this to serialize a field into the nexturl string. 
This works fine on Chrome/Safari, but the response was empty on Firefox 3.6. 

I modified cb() to get the innerHTML if it existed instead of the innerText, which was null.

The implementation code changes to:

```
function unescapeHTML(html) {
   return $("<div />").html(html).text();
}
$.fn.ajaxSubmit.debug = true;
$('#video_upload_form').ajaxForm({
  iframe: true,
  beforeSubmit: function(a,f,o) {
    o.dataType = 'text'; 
    nexturl = $('#nexturl').fieldValue()[0];
    title = $('#title').fieldValue()[0];
    nexturl = $.param.querystring(nexturl, { "title": title});
    o.url = $.param.querystring(o.url, {"nexturl": nexturl});
    $('#nexturl').remove()
    $('#title').remove()

  },
  success: function(data,response, xhr){
    eval(unescapeHTML(data))
   }
});
```

The data is being returned as escaped html. Once it's escaped it can be evaluated. 

I am pushing some changes i made, but the unescaping and evaluation should be done in the plugin. I don't have the time to fully implement and test this now.

**Comment by letoosh** [comment]
Faced similar issue with ajaxForm doing JSON with embedded HTML - the HTML markup inside gets escaped.

The workaround is to unescape whatever is received from an iframe or textarea. Here is a patch:

372,378c372
<                   }
<                     var htmlNode = document.createElement('div');
<                     htmlNode.innerHTML = xhr.responseText;
<                     if (htmlNode.innerText) {
<                         xhr.responseText = htmlNode.innerText; // IE
<                     }

## <                     xhr.responseText = htmlNode.textContent; // FF


I'm new to github, so sorry if I did something wrong, but hope this will help somebody.

**Comment by malsup** [comment]
If you return your response within a textarea tag then things should work fine.  For example:

```
<textarea>{ myKey: 'myValue' }</textarea>
```

The plugin will automatically extract the contents of the textarea and the browser will not escape them.

**Comment by letoosh** [comment]
What if your response is in JSON with HTML embedded, for example:

```
{ myKey: '<div>....</div>'}
```

In my case the inner HTML got escaped.
