### ISSUE TITLE
Server error with file input without file selected

### ISSUE THREAD

**Issue by dbeja** [jquery-form/form#251]
I've noticed the post data sent when there is a file input and no file selected it's different when sent with jquery form plugin and without.

It seems without any script, if I don't include a file, the file input is sent with the parameter filename="".
And with jquery form, that parameter is not sent.

I don't know if that's the problem, but I get a 500 error from the server when the file is not selected.
But if I turn off the script, I don't get any server error.

The error log from the server:
FINE: Resolving exception from handler [pt.iol.uploadservice.controller.VideoUploadSendEmailController@13577a53]: org.springframework.beans.ConversionNotSupportedException: Failed to convert value of type 'java.lang.String' to required type 'org.springframework.web.multipart.MultipartFile'; nested exception is java.lang.IllegalStateException: Cannot convert value of type [java.lang.String] to required type [org.springframework.web.multipart.MultipartFile]: no matching editors or conversion strategy found

**Comment by ybart** [comment]
:thumbsup:

In my case, it was related to this issue: https://github.com/malsup/form/issues/180

Commenting line 865 fixed the problem (for me).
