### ISSUE TITLE
Chrome file upload extraData URIDecodeComponent problem

### ISSUE THREAD

**Issue by jackysee** [jquery-form/form#252]
I have a file upload form and when submitting I would provide `extraData`

```
extraData: {'lmd':'2012-11-21 17:54:24'}
```

In chrome console, it shows:

```
------WebKitFormBoundaryOnCy4H82Q2ctvAO2
Content-Disposition: form-data; name="lmd"

2012-11-21+17:54:24
```

In server, I receive `2012-11-21+17:54:24`, which is not the expected format.

Looking into the code,  it seems the problem comes from `deepSerialize`. It uses `$.param` which will replace `space` with `+`

jsbin test http://jsbin.com/uliwud/1/edit

**Comment by malsup** [comment]
url-encoding is supposed to convert spaces to pluses.

http://www.w3.org/TR/html401/interact/forms.html#h-17.13.4

The server should be decoding those values.

**Comment by jackysee** [comment]
But if the field is one of the `<input/>`, it would be submitted without coverting space to '+' ??

**Comment by jackysee** [comment]
`$.param` will do `encodeURIComponent` and then replace space with `+`. Should the reverse of it doing the same?

**Comment by malsup** [comment]
You were right, there was a bug there.  Thanks for catching and reporting it!
