### ISSUE TITLE
IE7: cannot overwrite the action with the url option

### ISSUE THREAD

**Issue by robsch** [jquery-form/form#254]
If I'm not wrong it seems that in IE7 the action attribute of the form must be set. The url option does not have any effect. I encountered this issue with ajaxSubmit.

``` html
<form 
  name="asdf_form" 
  id="asdf_form" 
  action="some/script.php" 
  method="post" 
  accept-charset="utf-8" 
  enctype="multipart/form-data">
...
</form>
```

``` js
$('#profilbild_form').submit(function (e) {
  e.preventDefault();
  var opts = {
        url: 'a/non-existing/script.php',
        success:function (response) {
            alert('success: ' + response);
        }
    };
    $(this).ajaxSubmit(opts);
});
```

url: 'a/non-existing/script.php' has no effect. 

If the action attribute is empty the the pages url will be used, so I get the whole page as response.

Version 3.20, jQuery version 1.8.3.

It may has something to do with the file upload.

**Comment by kevindb** [comment]
Are you still experiencing this issue?

**Comment by robsch** [comment]
Long time ago. I don't know. II won't check this, but if I encounter this problem again I would create a new issue.
