### ISSUE TITLE
the option 'type‘ can not use 'put'

### ISSUE THREAD

**Issue by noday** [jquery-form/form#256]
the option 'type‘ can not use 'put',i want to use put method when submit form.how to do it?

**Comment by noday** [comment]
oh! I made mistakes.

**Comment by thucnc** [comment]
Hi, can anyone show me an example with PUT method? Thanks a lot?

**Comment by pcompassion** [comment]
yeah, specifying 'PUT' doesn't work..
It gets converted to "GET" somewhere..

OK...

http://stackoverflow.com/a/8054444/433570
https://github.com/malsup/form/issues/46

Apparently, iframe=true and 'PUT' doesn't work at the same time.
