### ISSUE TITLE
Incompatability with jQuery 1,6-1.8

### ISSUE THREAD

**Issue by viricida** [jquery-form/form#257]
Hello

For a long time I have been using jQuery 1.4.2 with jQuery Form 2.45. However, when I tried to switch to jQuery 1.8.3 I started receiving that error:

Object doesn't support this property or method
jquery.form.js
Code:0
Line: 374
Char: 5

(the line is: $.handleError(s, xhr, 'error', e);)

I upgraded to jQury Form 3.22 then and the error changed to that one:

Access forbidden
jquery.form.js
Code: 0
Line: 346
Char: 17

(the line is: if (io.contentWindow.document.execCommand) {)

It's reproduceable in IE 8, Firefox 16.0.2 and Chrome 23.0.1271.95

Could you please help with that?

Thanks!

**Comment by malsup** [comment]
Try with v3.23

**Comment by chrompic** [comment]
I'm getting the same error with jQuery Form 3.23.

**Comment by kevindb** [comment]
Are you still experiencing this issue?
