### ISSUE TITLE
when using iframe transport body is returned as responseText

### ISSUE THREAD

**Issue by gpetrov** [jquery-form/form#259]
When the jquery form submits via iframe, it returns on the success callback as responseText parameter only the body of the iframe response and not the full document!

See https://github.com/malsup/form/blob/master/jquery.form.js#L565

when using normal xhr - the responsetext is always the full returned html response, not only the body.

Why is there a difference or is it a bug?

**Comment by kevindb** [comment]
Are you still experiencing this issue?
