### ISSUE TITLE
'Access Denied' with latest version: 3.23

### ISSUE THREAD

**Issue by kpenrod** [jquery-form/form#260]
I am using IE9 on Win 7 machine. Using jquery.form.js V3.23 with jquery V1.7.2.  I am getting 'Access Denied' at line 320.

317    if (s.iframeTarget) {
318         $io = $(s.iframeTarget);
319         n = $io.attr('name');
320         if (!n)
321                $io.attr('name');
322         else
323                id = n;
324    }

I downloaded the latest jquery.form.js because I was getting 'Access Denied'  on the try-catch block for io.contentWindow.document.execCommand down near line 346 in latest version. {#214, #257}

Any ideas?

**Comment by malsup** [comment]
Do you have a test page I can look at?

**Comment by kpenrod** [comment]
Mike has responded asking for a sample page.  Unfortunately I’ve been temporarily pulled off on another project.  I’ll get info to him when I can get back on this and let you know what transpires.

Ken

**Comment by kpenrod** [comment]
It’s only on my development laptop computer and unfortunately I’ve been temporarily pulled off on another project.  When I get backed to this I’ll get you what I have.  Thanks for responding.

Ken

**Comment by jogep** [comment]
I also Step into this Issue when submitting a form with form plugin and the form includes an file input element.

Access denied in jQuery 1.8.3 Line 6002 Char 6:

```
                if ( elem.parentNode ) {
                    elem.parentNode.removeChild( elem );
                }
```

Maybe this commit is the source of this problem:
https://github.com/malsup/form/commit/1f456636f61583715a859e33c0534cccf0661df4

The Script Error raised after the successfully Submit of the Form. I guess during the insert of the result.

**Comment by kevindb** [comment]
Are you still experiencing this issue?
