### ISSUE TITLE
AjaxSubmit v3.23, with file upload, IE9 and document.domain set - Access Denied

### ISSUE THREAD

**Issue by pogo61** [jquery-form/form#261]
I think that I have read every article by now and have come to the conclusion that there is only a very narrow set of conditions where this will work:

1) The hidden iframe must point to a real HTML page on the server that sets document.domain
2) The response from the server must be HTML and must also set document.domain

This greatly reduces the value of the plugin, so I was hoping that you could confirm that I was not missing something obvious. 

In addition, I have had to resort to writing this UI logic myself. I can't seem to get ajaxSubmit to work without throwing Access Denied, even when I specify iframeTarget.

**Comment by hppycoder** [comment]
I agree that this needs to be addressed.

@malsup - Access denied is getting thrown on line 488
form.submit();

I really hope that this get fixed, it appears in IE9 as far as I have been able to test.

**Comment by schplay** [comment]
Has any progress been made with this?

**Comment by timfee** [comment]
@malsup - Access is getting denied at 

``` javascript
try{form.submit();}catch(err){var submitFn=document.createElement('form').submit;submitFn.apply(form);
```

for me. Still **SCRIPT5: Access is denied.**

**Comment by timfee** [comment]
@schplay, I was able to work around this by setting the `Content-Type` of my response to `text-html` and then,

``` javascript
                        function (data) {
                            data = $.parseJSON(data);
                            // Proceed as normal
                            if (data.error) {
                                alert(data.error);
                            }
                            else {
                                alert('Success');
                            }                            
```

**EDIT:** This worked when there were no files being actually attached---doh!

**Comment by nlyn** [comment]
FYI - I'm experiencing this with IE8 right now.

**Comment by kevindb** [comment]
Are you still experiencing this issue?
This might be helpful:
When using iframes, the content-type header should be left as as text/html or text/plain.
#302 (comment)
