### ISSUE TITLE
False upload percentage using uploadProgress on slow connections

### ISSUE THREAD

**Issue by mabuse** [jquery-form/form#263]
Using a VERY slow connection I've noticed that the progress bar is showing a full 100% upload progress but the file has not been completed.

I've tested it using the sample code int jquery forms web page:

http://malsup.com/jquery/form/progress.html

Please find attached two images, first one showing 100% of updload time at 3s from uploading the file and second one when at 1.3 minutes when the request has been fully completed.

![error_form_upload](https://f.cloud.github.com/assets/108461/28454/90bc1d94-4c2b-11e2-9077-242b18f6d5a3.png)
![error_form_upload_1](https://f.cloud.github.com/assets/108461/28455/90d57690-4c2b-11e2-8ca7-dfd7a953c3a1.png)

**Comment by malsup** [comment]
The plugin only reports the information given to it by the browser in the XHR's onprogress callback.

**Comment by mabuse** [comment]
Thanks for the information. Anyway, I do not understand why the xhr's onprogress callback is so different from the real downlading progress in our server.
