### ISSUE TITLE
TypeError: Attempted to assign to readonly property.

### ISSUE THREAD

**Issue by JasperH8g** [jquery-form/form#265]
In Safari 6 this error is thrown (as for some other plugins as well, it seems). 

```
jquery.form.js:722 | TypeError: Attempted to assign to readonly property.
```

Disabling strict mode solved it for me, for now.

**Comment by malsup** [comment]
Have you tried with latest version?  Line 722 doesn't line up with the latest.

**Comment by JasperH8g** [comment]
Yes. For the latest version this linenumber should be 730:

```
    options.delegation = options.delegation && $.isFunction($.fn.on);
```

**Comment by malsup** [comment]
Can you provide a link that demonstrates the problem?  I'm unable to reproduce.

**Comment by JasperH8g** [comment]
I'm sorry, not really anymore. Maybe it's resolved in the meantime?
