### ISSUE TITLE
Accidentally submitting disabled elements?

### ISSUE THREAD

**Issue by jdelStrother** [jquery-form/form#267]
Hi there - I hope you'll forgive the somewhat vague details here, but I've been staring at this problem for days and getting nowhere.

We upgraded from v2.63 to v3.24 a bit over a week ago.  Ever since then, a few times a day, we get an error report from our server where an iframed POST request from the form plugin has some unexpected parameters.  It appears to be submitting an empty string value for an `<input type=file>` field in the upload, despite that field being disabled.

According to the user agents on my error reports, it only seems to occur in Safari (I've seen both AppleWebKit/534.57.7 and AppleWebKit/536.26.17).  But I can't reproduce it at all.

The logic for skipping disabled fields in the form plugin all looks perfectly fine to me, this is basically a cry for help to see if anyone has run into anything similar and might be able to suggest anything.

**Comment by malsup** [comment]
Sorry for the slow reply.  Is there a value posted as well?

**Comment by jdelStrother** [comment]
Sorry for the slow reply from my side as well - I've been out the country for a while.  Not sure if I understand your question - it posts a value of "".

I'll try upgrading to include that fix & see if it helps.
