### ISSUE TITLE
File inputs not working

### ISSUE THREAD

**Issue by RobinDaugherty** [jquery-form/form#271]
The fix made in #113 seems to be causing a new issue. The selector "input[type=file]:enabled[value]" causes file inputs to be ignored, because (apparently) there's no value available. Removing the "[value]" portion of the selector fixes this issue.

This is with jQuery 1.8.2. Other libraries included in the page: html5shiv, modernizr, respond, and bootstrap 2.2.1.

**Comment by malsup** [comment]
Is this still an issue with latest?
