### ISSUE TITLE
File Upload Progress doesn't work on Android in AJAX mode

### ISSUE THREAD

**Issue by xp-vit** [jquery-form/form#274]
File Upload Progress doesn't work on Android in AJAX mode

**Comment by xp-vit** [comment]
Also doesn't work on Android 4.1.1

**Comment by malsup** [comment]
Just tested on Android 4.1.1 with both stock browser and Chrome.  Upload worked fine.

http://jquery.malsup.com/form/#file-upload

**Comment by xp-vit** [comment]
Yes, my mistake. Progress doesn't work on Android. Updated first message in topic.

**Comment by malsup** [comment]
Looks like the stock Android browser doesn't support progress callbacks.  Works fine with Chrome.
