### ISSUE TITLE
ajaxSubmit does not append buttons' values to the data

### ISSUE THREAD

**Issue by abernier** [jquery-form/form#28]
Hi,

Unlike ajaxForm(), ajaxSubmit() does not append submit buttons' values. Is this expected behavior?

Thank you.

**Comment by malsup** [comment]
Yes.

**Comment by abernier** [comment]
Hi,

Thanks for the quick answer, but shall you explain a bit more? In my mind, form's serialization should be the same between these two methods but maybe I'm wrong.

Thanks for explaining.

**Comment by malsup** [comment]
ajaxForm binds all the required events to capture the submitting element.  ajaxSubmit simply serializes the form values when it is called.  ajaxSubmit is typically invoked by code _after_ the submit event has fired, at which time there is no way to determine which element caused the event.  Think of ajaxForm as proactive and ajaxSubmit as reactive.
