### ISSUE TITLE
Should clearForm()  empty 'select' when there is no empty option?

### ISSUE THREAD

**Issue by jackysee** [jquery-form/form#288]
If there is a `select` with no empty `option` in it, calling `clearForm()` would render the `select` as blank.

Should it instead selecting the first entry, like the browser default?

**Comment by kevindb** [comment]
Are you still experiencing this issue?

**Comment by jackysee** [comment]
Seems still behave like this: http://jsbin.com/gapawixiva/edit?html,output

**Comment by kevindb** [comment]
Have you tried using the [`resetForm()`](https://github.com/jquery-form/form#resetform-1) method? It looks like it does what you're asking for.

**Comment by jackysee** [comment]
`resetForm()` would change back the form to its initial state, not clearing value.

http://jsbin.com/bohedezeje/edit?html,output

Actually since this issue was opened long time ago, it's not my use case now. I probably have worked around it at that time. If no one has concern on this, may be this issue can be closed.
