### ISSUE TITLE
FileUpload response script is not working in IE7. 

### ISSUE THREAD

**Issue by ramadevinangineni** [jquery-form/form#289]
We are submitting our form using ajaxSubmit and response is Html & Javascript.

In IE7 its giving error message - "object expected" wherever we have $document.ready & $("#button").click..

In Firefox, its firing initially onload events and displaying the content.

Please suggest the solution. we are using Jquery 1.8 and JqueryForm latest 3.27 .

**Comment by raj-jkr687** [comment]
Hi Malsup,
I am also facing the same issue.even the http://jquery.malsup.com/form/#file-upload with selecting option of script is not working.Pls reply asap

**Comment by tburd** [comment]
I got same problems in IE9 and checking the console I found the following error:  

```
SCRIPT5: Access denied. 
jquery.form.js, line 483 Character 17
```

Lines 481-483 from jquery.form.js:

```
// just in case form has element with name/id of 'submit'
var submitFn = document.createElement('form').submit;
submitFn.apply(form);   // The problem is here
```

And to complicate it even more, my form has no element with name/id of 'submit'.
Any possible solution @malsup ?

**Comment by malsup** [comment]
@tburd, do you have issues with the demo page?

http://jquery.malsup.com/form/#file-upload

I just tested it in IE8 and IE9 and it did not produce any errors.

/cc @rajasekarbee

**Comment by tburd** [comment]
@malsup 
Yes, it is the same error and I checked all return types.
I am using IE 9.0.8...

**Comment by malsup** [comment]
I'm running IE 9.0.8 as well, but not seeing any errors.  Is IE rendering my page in IE9 Standards mode?  Are you using any IE plugins?

**Comment by tburd** [comment]
Now I´ve rebooted IE and it worked in your page, but not on mine.
I am not using any pulgins and IE9 is in Standard mode.

@malsup I found people with the same error here: https://github.com/malsup/form/issues/286
