### ISSUE TITLE
Reporting status_code = 403 in error handler

### ISSUE THREAD

**Issue by zahanm** [jquery-form/form#29]
I just spent a load of time tracking this down, and though it involved multiple screw-ups on my part, jQuery.form could've helped.
I was using the hidden iframe file uploader to upload a file and returning JSON wrapped in textarea's if successful and an empty HTTP response with a status code of 403 if the response failed due to a server-side problem (Django).
Unfortunately, if there is no response content, jQuery.form doesn't catch the response and assumes that the iframe DOM isn't ready yet and queues the callback 99 more times. As a result I never noticed that the server was returning 403's and thought it was a JS or browser fault.
Anyhow, basically the Opera iframe DOM-not-ready hack screws up empty response handling. This is an edge case, but it should be mentioned somewhere or fixed so that the error handler is called.
Thanks!

**Comment by malsup** [comment]
I believe this is now fixed with v2.47.
