### ISSUE TITLE
Alter Data with beforeSubmit in IE

### ISSUE THREAD

**Issue by lwojtysiak** [jquery-form/form#294]
According to issue https://github.com/malsup/form/issues/164
I have similar problem, but while working on IE. 

I'm adding data to form in beforeSubmit, but this works only in Firefox, but not working on IE - data is added to table (argument 1) but not sended in post. 

For now I prepared workaround - I'm adding "data" to ajaxForm(options) and then in beforeSubmit I'm changing the value
(options.data.varName = varValue;)

But still I think, that this is an error that "normal" push to formData in beforeSubmit doesn't work on IE8

**Comment by mateusz-szymanski** [comment]
The same here, in firefox and chrome everything works fine, but IE8 does not send new data added in beforeSubmit or even modified data. I had to add not one value but array without specified length. My workaround was to modify form also, like:

```
options.beforeSubmit = function (values, form) {

            values.push({ name: 'dataName', value: 'my value1' });
            values.push({ name: 'dataName', value: 'my value2' });
...
            $(form).append($('<input />').attr({ type: 'hidden', name: 'dataName', value: 'my value1' }));
            $(form).append($('<input />').attr({ type: 'hidden', name: 'dataName', value: 'my value2' }));
...
}
```

remember to remove added inputs later. Works in firefox, chrome and ie8.

**Comment by AndrewRayCode** [comment]
I can verify this is happening in IE8. Ping @malsup. Nasty little issue.

**Comment by AndrewRayCode** [comment]
This occurs because IE8 triggers the `fileUploadIframe` function which basically just submits the original form, and disregards a lot of the options data. It will respect `options.extraData` but that's it not the array in `beforeSubmit`

**Comment by malsup** [comment]
An alternative approach is to set the `data` option in `beforeSerialize`:

```
beforeSerialize: function(form, options) {
    options.data = {
        name1: 'value1',
        name2: 'value2'
    };
}
```
