### ISSUE TITLE
Wrong request data with file upload if no file selected

### ISSUE THREAD

**Issue by zgmnkv** [jquery-form/form#296]
I have a simple file upload form.
If I select a file and submit the form, all goes fine.
If I do not select a file and submit the form, sended request differs from request that is sended without ajax. So my server-side library behaves wrong.
Similar issue is described here: http://stackoverflow.com/questions/14771446/spring-upload-form-optional-with-optional-file .

**Comment by malsup** [comment]
You can use the iframe option to force the same type of post for both cases:

```
iframe: true
```

**Comment by zgmnkv** [comment]
Thanks, iframe: true fixes this issue, but it would be nice if it will work without iframe.
I found that this issue actually duplicates that one: #180 , so I will leave a comment there.
