### ISSUE TITLE
File Upload with JQM (Returns True instead of False)

### ISSUE THREAD

**Issue by jashaffe** [jquery-form/form#298]
Hi Everyone,

Thanks for all the community support!  

I very aware you can't upload files from iOS.  Some people will be using this will full browsers/OS.

Literally using the default sample and works great until I need add any JQM (tried 1.2/1.3).  Its still works, but it returns true and send the browser to the action page.  =(

Any thoughts?

Appreciate any and all help!

-j

**Comment by malsup** [comment]
Can you post a simple demo?
