### ISSUE TITLE
Setting of headers on IE not working

### ISSUE THREAD

**Issue by jaxjixmix** [jquery-form/form#299]
Hi, 

I'm using Jquery.form and currently having problem on IE browsers. 

Action URL : www.local.test.com/imageuploader.php - this requires authorization in its header

It works on every browser after setting up Ajax Headers but on IE, it seems it can't view the imageuploader file because it requires an Authorization key.

I added a function that set header request but it seems not working...

function setHeaderFileUpload(xhr) {
    xhr.setRequestHeader('Authorization', "Basic "+token);
}

On IE the AUTHORIZATION header was not included.. Please help

**Comment by malsup** [comment]
Setting headers when uploading is not supported in IE (< v10) because ajax is not supported for uploads.
