### ISSUE TITLE
Firefox 19.0.2 failure

### ISSUE THREAD

**Issue by timo22345** [jquery-form/form#304]
jQuery Form Plugin version: 3.31.0-2013.03.22 fails in the following pages in Firefox:

http://jquery.malsup.com/form/progress.html
http://jquery.malsup.com/form/progress2.html
http://jquery.malsup.com/form/progress3.html

Firefox 19.0.2 (Mac OS X 10.6.8) causes in Firebug three lines of errors:
x Error:
x Error:
x Error:

If upload is proceeded while Firebug closed (so that no error can be seen), the erroneous can be seen from progress bar: sometimes it reaches 100%, sometimes don't.

Also Firefox 15.0.1 (Ubuntu) and Firefox 19.0.2 (Windows 7) has the same problem: progress bar doesn't reach always 100%, although status text indicates that files are uploaded.

The following has nothing to do with Form plugin, but I have to say that Firefox is not a choice for users who want to upload files: Firefox prevents user to clear file input! Delete, Backspace, Esc or Refresh button doesn't clear file input field, but pressing Enter on Address bar does, which clears other fields also. Not good!

**Comment by malsup** [comment]
I don't see any errors on FF19.0.2 on OSX.  Maybe some other FF extension is causing an issue.

On Windows I do see that the progressbar doesn't always reach 100%.  You can fix that by adding a success handler:

```
success: function() {
    var percentVal = '100%';
    bar.width(percentVal)
    percent.html(percentVal);
},
```

**Comment by timo22345** [comment]
Error comes when Firebug is open. So it seems that it causes the three line "Error".

All other browsers gives 100% immediately after upload and BEFORE server side processing (eg. image resize etc.). Proposed success() -workaround gives 100% after server side processing. Do you know any method to get 100% before server side processing in Firefox? Or should we wait Firefox update?

**Comment by malsup** [comment]
I tested with and without Firebug open.  No errors for me.

I don't have any other suggestions.  The plugin can't force the browser to invoke it's callback.

**Comment by srikanthraob** [comment]
I faced the same issue,
For me the case is, the office Firewall settings not allowing the jquery.form.js to be loaded included as :  ..  <script src="http://malsup.github.com/jquery.form.js"></script>, if I am out of this firewall settings, "$("#form1").ajaxForm(options) "  is working great for me. 

Not sure if this is relevant for the reported user's cases, but wanted to share, this could also be one possibility.
