### ISSUE TITLE
Different submit behavior when using uploadProgress

### ISSUE THREAD

**Issue by confile** [jquery-form/form#305]
I use ajaxSubmit to submit a form to a third party url. I use the following code. 

``` javascript
$("#uploadToYoutubeForm").ajaxSubmit({
                            url: "http://www.example.com?nexturl=someurl",
                            type: 'post',

                           uploadProgress: function(event, position, total, percentComplete) {

                            },

                           complete: function(response){
                                        alert("complete");                      
                            }
                        });
```

My problem is that there is a different behavior when I use uploadProgress. The server executes the nexturl only when I do not use uploadProgress. When I use uploadProgress the nexturl will not be called.

What can I do?

**Comment by confile** [comment]
@malsup Do you have an idea?

**Comment by malsup** [comment]
No.  That's extremely odd.

**Comment by confile** [comment]
@malsup so what should I do about it?

**Comment by malsup** [comment]
What browser are you using?  Are there any errors in the console?  Is your uploadProgress callback invoked?

**Comment by confile** [comment]
@malsup Chrome Version 26.0.1410.43 MAC OSX 10.8.3.

No Errors in the console. uploadProgress worked fine. I get a perfect progress bar.

**Comment by malsup** [comment]
Is the server receiving the file?  Do you get a response?

**Comment by confile** [comment]
@malsup 
The only part I add is the following: 

``` javascript
uploadProgress: function(event, position, total, percentComplete) {
                                $("#ajax-videouploader").hide();
                                $("#progressbar").progressbar({
                                    value : percentComplete
                                });
                                $(".progress-label").html(percentComplete+" %");
}
```

The progress bar works fine. The uploaded file is stored on the server, but the server does not send a request back when I added the above code.

Do you have an idea?

**Comment by malsup** [comment]
Sorry, don't know what to suggest.  I'm not able to duplicate the issue on a similar cors setup:

http://malsup.github.com/demo/progress.html

The server response is consistently received by the client.

**Comment by ajwinkworth** [comment]
I am also having this issue. Using Fiddler I can see that the server is sending a redirect response but the request maintains a pending type and (eventually) cancelled status. The chrome client never sees a response. It eventually turns from pending to cancelled. I also have narrowed it down 100% to adding the handler for uploadProgress as adding/removing the handler will add/remove the issue. I also get a good progress reporting. The response from the server is a 303 with new location(back to my server). Works fine in IE10? (wtf when does that ever happen). File is received fine by S3 (the CORS server).

**Comment by ajwinkworth** [comment]
Oh after looking at your(malsup's) code to reproduce you should add the 303 redirect as response as that is also in the mix of the problem.

**Comment by confile** [comment]
@ajwinkworth where should I add it?

**Comment by ajwinkworth** [comment]
If it helps.. adding an progress handler makes the cors do a preceeding options request (which passes) where without progress handler it doesn't.

**Comment by ajwinkworth** [comment]
I am chrome: Version 25.0.1364.172 m on Windows 7 64

**Comment by ajwinkworth** [comment]
@confile Sorry my poor writing at 1am was to do with malsups attempt at recreation of the issue. The server your sending your (@confile) request too would be redirecting also back to your server(or whatever nexturl is). So this issue involves CORS, uploadProgress Handler, and Redirection of CORS request as CORS seems to work without redirection. Its almost as if the xhr forgets how to redirect if you add an uploadProgress handler. ?
