### ISSUE TITLE
ajaxSubmit 's problem

### ISSUE THREAD

**Issue by twxia** [jquery-form/form#306]
I write like this in previous version is working well ,but now my upload.php can't get the post:

`var myoptions = {  
    type:   'POST',
    url:    'upload.php',
    dataType:   'json',
    success:    uploadJson
};
$("#file").change(function(){
    $("#previewForm").ajaxSubmit(myoptions);
});`

**Comment by NaHack** [comment]
URI is OK?

**Comment by malsup** [comment]
Submitting a form based on a file input change event will not work in Internet Explorer (security violation).

**Comment by twxia** [comment]
okay  tks~
