### ISSUE TITLE
Can't control which form fields are submitted

### ISSUE THREAD

**Issue by uliuli** [jquery-form/form#312]
I have a form where I need to submit certain fields of the form depending on different scenarios rather than all of them. Is there a way to do this? 

It would be nice to have something like a 'fields' option where you can pass the elements that should be serialized and submitted.

**Comment by malsup** [comment]
You can temporarily disable the fields you don't want submitted or remove their name attribute.

**Comment by warmhug** [comment]
good. but if it can have a configuration item will be better...
