### ISSUE TITLE
does error calback has the jquery wrapped form element or not....

### ISSUE THREAD

**Issue by ankur20us** [jquery-form/form#314]
I am just wandering that error callback of ajaxForm has jquery wrapped form object or not just like in success and beforeSubmit callbacks

**Comment by malsup** [comment]
No, it doesn't.

**Comment by ankur20us** [comment]
can anything be done so that it can give that too........

**Comment by malsup** [comment]
Inside the success and error callbacks, 'this' defaults to the settings object.  So you can do something like this:

```
var myForm = $('#myForm');
myForm.ajaxForm({
    theForm: myForm,
    error: onError,
    success: onSuccess
});

function onError(xhr, status, err) {
    var myForm = this.theForm;
    ...
}
```
