### ISSUE TITLE
There should be a minimized version of the file.

### ISSUE THREAD

**Issue by sunshineo** [jquery-form/form#320]
For serving production. Or everyone has to do their own compression.

**Comment by Menelion** [comment]
I was thinking about providing a Grunt file but I'm not too good at Grunt yet. However, it would be great, indeed.

**Comment by malsup** [comment]
A minified version can be found here:

http://malsup.github.io/min/jquery.form.min.js

**Comment by sunshineo** [comment]
Awesome!
