### ISSUE TITLE
help needed with file upload

### ISSUE THREAD

**Issue by ikechukwuokalia** [jquery-form/form#321]
hi, please need to be able to upload multiple file one after the other displaying upload progress without submitting the entire form.

is it possible for one to foreach  the file array of the multiple file input field, sending each individual file array to the server script that will handle the upload?
how can i achieve this.
thanks for this wonderful project.

**Comment by kevindb** [comment]
Are you still experiencing this issue?

**Comment by liuatgit** [comment]
I have a strange situation like yours. How to upload the specific file `($('#files')[0].files[i])` when user chose multiple files `'<input id="files" type="file" multiple="multiple" />'`?

**Comment by liuatgit** [comment]
Never mind, it can't be done. I'll process files in PHP instead of Javascript.
