### ISSUE TITLE
'type' null or not an object

### ISSUE THREAD

**Issue by graindeweb** [jquery-form/form#323]
Hi,

Since I've updated jquery.form.js with last version, I now get a "type" null or not an object (l94). Tested on IE8, FF 20.00, chrome 26.

**Comment by malsup** [comment]
Please provide an example.  The main docs page seems to work just fine:

http://jquery.malsup.com/form/

**Comment by VincentPeters** [comment]
# Solved!:

need to add empty object as parameter to ajaxsubmit -> ajaxSubmit({});

I have the same problem

JS:
![screen shot 2013-07-11 at 13 04 06](https://f.cloud.github.com/assets/400738/781172/b6307b24-ea19-11e2-9b46-4673ecbc5e0b.png)

HTML:
![screen shot 2013-07-11 at 13 06 04](https://f.cloud.github.com/assets/400738/781177/eb4d53a4-ea19-11e2-9aa2-25f06a13ea81.png)

Error:
![screen shot 2013-07-11 at 13 07 14](https://f.cloud.github.com/assets/400738/781184/11c57a5c-ea1a-11e2-8825-018822c67948.png)
