### ISSUE TITLE
Form with multipart/form-data runs success on 404 in IE.

### ISSUE THREAD

**Issue by mkefd** [jquery-form/form#324]
Hi,

ajaxSubmit() on form with enctype multipart/form-data and action to HTTP 404 runs success callback in IE (6-9) and error in Chrome (as expected in normal browser). Could it be fixed for damn IE, please?

**Comment by malsup** [comment]
Can you provide a simplified example?

**Comment by mkefd** [comment]
Hi, thanks for the quick answer!
Here it is: http://csa.ru/~kef/public/jfie.html, please, see console output when pressing the buttons.

**Comment by mkefd** [comment]
Maybe better to put the example source code here:

``` html
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
    <script src="http://malsup.github.io/jquery.form.js"></script>

    <script>
    $(function() {
        $('#button').on('click', function() {
            $('#form').ajaxSubmit({
                success: function() {console.error('success on 404')},
                error: function() {console.log('error on 404')}
            });
        });
    });
    </script>
</head>
<body>

    <form action="404" method="post" id="form" enctype="multipart/form-data">
        <input type="hidden" name="name" value="value" />
    </form>

    <input type="button" id="button" value="form bad in ie" />

</body>
</html>
```

**Comment by malsup** [comment]
Sorry for the delay.  This should work fine on IE10.  It doesn't work on older versions of IE because they do not support XHR Level 2 and there is no way to determine the status code when using an iframe for the response.  The only workaround is for you to add a "status" attribute to the body element of the response document.

```
<!doctype html>
<html>
<body status="404">
....
```
