### ISSUE TITLE
Line 295 of jQuery.form.js has a reference to jQuery that I think should be to $

### ISSUE THREAD

**Issue by markfolrees** [jquery-form/form#326]
Hello

version 3.35.0. I also noticed the same problem in version 3.18

I am working in a portlet environment with multiple jQuery versions. So jQuery always runs in extreme noconflict mode and is always aliased. This means that an object named jQuery is not necessarily available after each script has been initialised. As this script is initialised by passing in jQuery as the argument $, it makes sense to me that all references within the script should be to $. On line 295 however there is one to jQuery. I noticed this as it's undefined in my environment. Replacing jQuery with $ appears to solve the issue.

Here's the code snippet:

if (options.uploadProgress) {
            // workaround because jqXHR does not expose upload property
            s.xhr = function() {
295 >>>>>>                var xhr = jQuery.ajaxSettings.xhr();
                if (xhr.upload) {
                    xhr.upload.addEventListener('progress', function(event) {
                        var percent = 0;
                        var position = event.loaded || event.position; /_event.position is deprecated_/
                        var total = event.total;
                        if (event.lengthComputable) {
                            percent = Math.ceil(position / total \* 100);
                        }
                        options.uploadProgress(event, position, total, percent);
                    }, false);
                }
                return xhr;
            };
        }

**Comment by malsup** [comment]
Good catch. Thanks!
