### ISSUE TITLE
named submit buttons don't get submitted

### ISSUE THREAD

**Issue by sixmo** [jquery-form/form#329]
Some frameworks use named submit buttons to decide which action to perform on the backend. Right now these buttons don't get submitted with jquery.form. The same happens with named images.
For myself I fixed it by adjusting $.fieldValue:
(t == 'submit' || t == 'image') on line 1030 changed to ((t == 'submit' || t == 'image') && !el.name)

**Comment by Macs75** [comment]
normal behaviour on a submit I think that only the button actually clicked will send its value, with your solution
every submit button with a name attribute in the form is sent.

**Comment by malsup** [comment]
If you use ajaxForm (instead of ajaxSubmit), the submitted data will include the name and value of the submitting element (and its click coordinates if the submitting element is an image).  This can be seen in the online example: 

http://jquery.malsup.com/form/#ajaxForm
