### ISSUE TITLE
$('body').ajaxSuccess not being triggered.

### ISSUE THREAD

**Issue by Enome** [jquery-form/form#33]
I have a gobal handler for ajax calls and it seems the event isn't being triggered when I use ajaxSubmit()?

$('body').ajaxSuccess(function(){ alert('ajax called was successful'); });

**Comment by malsup** [comment]
Can you post a link to a test page?  Thanks.

**Comment by Enome** [comment]
Was writing an example and realised I had a if statement in ajaxSuccess so that I only get a success message on http post requests.

```
$('form').ajaxSuccess(function(e, xhr, settings){
    if(settings.type == 'POST'){
         response = JSON.parse(xhr.responseText);
         alert(response.msg);
    };
 });
```

If I don't use jQuery.form to submit the form this works. But with jQuery.from the settings.type is post and not POST. Hope this helps to narrow it down. If you still need a test page let me know and I'll create one.
