### ISSUE TITLE
Issue using ajaxSubmit to upload files in IE9 with Basic Authentication.

### ISSUE THREAD

**Issue by jellomoose** [jquery-form/form#330]
We are using ajaxSubmit to handle media uploading on a project. Here is a stripped down version of what we are doing:

form.ajaxSubmit({
    beforeSend: function(data) {
        var auth = "Basic " + Base64.encode(username + ":" + password);
        data.setRequestHeader("Authorization", auth);
    },
    complete: function(xhr) {
        // Do other stuff
    }
});

In other browsers, this appears to function perfectly. In Chrome's network inspector, for example, we can see the Authorization header plain as day:

Authorization:Basic MjAwMD....etc

In IE 9 (and 8, but we don't really care about 8...) this is not the case. When we run the request, there is no Authorization in the header and we just immediately get back a 401 error from the server due to the lack of credentials (which in turn pops up a login box to the user).

From what I have read in the examples on the ajaxForm site, the plugin should fallback to an iframe upload in "older" browsers. We know that it worked in IE9 before we turned on the basic authentication, but now we have run into the issue listed above.

I am not very familiar with this area (if you couldn't tell from my meandering description of the issue), so any help or pointers in the right direction would be greatly appreciated.

**Comment by malsup** [comment]
IE9 does not support file uploads via ajax, therefore the fallback iframe technique is used.  With this fallback method there is no way to set request headers.
