### ISSUE TITLE
Start using Semantic Version numbering for git tags

### ISSUE THREAD

**Issue by JohnAlbin** [jquery-form/form#332]
Over in #248, the request was made to start using Git tags so jquery.form could be packaged using Bower. But Bower actually needs semantic version numbers as defined by http://semver.org

You are 99% complying with that spec already, but you need to stop adding the date to the end of the git tags. In other words, "3.32.0" is great, but the tag "3.32.0-2013.01.28" doesn't work with Bower.

This is also related to #331.

**Comment by teohhanhui** [comment]
The problem still remains. Current version tag "3.51" does not follow semver specification.
