### ISSUE TITLE
File Upload

### ISSUE THREAD

**Issue by GeNiuDeV** [jquery-form/form#333]
When file not selected it has send as string to server 
When i use it with spring have this problem and i see exception "spring Failed to convert property value of type 'java.lang.String' to required type 'org.springframework.web.multipart.commons.CommonsMultipartFile' for property ..."
I resolve it with this simple change in fileUploadXhr function:

```
    for (var i=0; i < a.length; i++) {
        if(a[i].type!="file" ||  a[i].value && a[i].value!=null && a[i].value!="" )
            formdata.append(a[i].name, a[i].value);
    }
```

**Comment by kevindb** [comment]
Are you still experiencing this issue?
