### ISSUE TITLE
ajaxForm + IE8 + Redirect in postresult = IE8 hang

### ISSUE THREAD

**Issue by paales** [jquery-form/form#334]
We use the jQuery.ajaxForm plugin to add products to a cart. As far as I understand it creates an iframe and posts the information.

This goes well, but when a product is succesfully added to the cart, the system redirects to the success page. When the redirect happens, IE8 crashes.

When there is an error while posting the form (the product isn't in stock any more) the pages doesn't redirect and just shows the error, IE8 doesn't crash.

The software ran fine for a looong time, but it suddenly stopped working. Since IE8 crashes it is impossible to debug. The crash is triggered by the ajaxForm module because every other post works, every other ajax thingy work, normal ajaxForms works but ajaxForm+Redirect = IE8 Crash.

Any idea what is going on?

**Comment by paales** [comment]
I've tried to simplify it as much as possible, latest form plugin and latest jQuery:
http://www.postbeeld.com/ajax3.html

The problem is that the browser crashed after the success method is called, it seems that the browser crashes when  the iframe is cleaned up or something.

Please note: this problem does not happen with the in the Microsoft offered VM's, therefor I first thought is was a configuration problem of my clients system, but my client reports that multiple customers suddenly have this problem. This leads me to think that it is some sort of security fix for IE8 that causes this problem (the VM's cant be updated). The problem does not occur on IE8 Compability mode.

**Comment by paales** [comment]
> The problem is that the browser crashed after the success method is called, it seems that the browser crashes when the iframe is cleaned up or something.
- Also, it seems to only happen when there is a redirect on the page.
- After clicking the button, please clear your cookies.

Thanks for taking a look @malsup.

**Comment by malsup** [comment]
Sorry, I don't have access to a native version of IE8.  I confirmed that the VM version of IE8 as well as IE9 in IE8 mode do not have this problem.

**Comment by paales** [comment]
Oh.. :( Anything I can do? Any pointers how to debug this, because the codebase is a bit overwhelming?

**Comment by paales** [comment]
@malsup Update: I've updated the VM, you can't use the windows update interface but you can let windows update in the background:

Enable the automatic updates and set the time of the computer one minute before the automatic update time. The system will now update (had to install 127 updates in my case). Restart the VM and try again. IE8 will now crash.

Ps. I've used these VM's: https://github.com/xdissent/ievms

**Comment by paales** [comment]
@malsup Sorry to spam you a bit, but it seems to affect all updated IE8 users and my client is complaining a bit :(

**Comment by malsup** [comment]
I'm swamped with other work right now and haven't had a chance to look at it.  I suggest you not send the redirect for IE8.  Even if IE8 didn't crash, I don't think the redirect would have any useful function.

**Comment by paales** [comment]
Unfortunately we cant just disable the redirect, the system does the redirect. The redirect has a function in such a way that it redirects to the success page and the result thereof is shown.

For now I've completely disabled the Ajax form for IE8. That 'fixes' the problem for now. I've you manage to get a solution, please let me know :)

**Comment by kevindb** [comment]
Are you still experiencing this issue?

**Comment by paales** [comment]
Hehe, I don't really think so 👍 Thanks for the response 😉
