### ISSUE TITLE
No "success" with multiple forms

### ISSUE THREAD

**Issue by fschroiff** [jquery-form/form#340]
There are multiple forms with the class `.inline-edit` on the page. I have this code:

```
    $(document).ready(function(){
            $('.inline-edit').ajaxForm({
                    dataType: 'json',
                    success: function(data, status, xhr, $form) {
                        $form.find('.control-group').addClass('success');
                    }
            });
    });
```

The data gets submitted successfully. The `success` function does not get executed. What am I doing wrong?

**Comment by malsup** [comment]
Do you have an example page?

**Comment by fschroiff** [comment]
Will this suffice? http://jsfiddle.net/fernstrg/ZsVrM/ 
Or do you need a real functional form?

**Comment by malsup** [comment]
You probably have invalid JSON.  Here's your same example working fine:

http://jquery.malsup.com/form/double.html

**Comment by fschroiff** [comment]
Got it, my bad! JSON was indeed invalid. Thanks a million.
