### ISSUE TITLE
how to upload image without click submit button

### ISSUE THREAD

**Issue by loethen** [jquery-form/form#342]
i want upload the image immediately after choose the image. don't click the submit button .

thks.

**Comment by alirezahatami** [comment]
``` html
<input name="ImageFile" id="imageInput" type="file" style="display:none;" onchange="document.getElementById('submit-btn').click();" />
```

**Comment by malsup** [comment]
Browsers make this difficult for security reasons.  The usual workaround that I see people use is to put a change handler on the input to fire the submit event and to also use a label element to trigger the click on file input.  Try playing around with that.
