### ISSUE TITLE
AjaxForm IE7-8-9 Problem

### ISSUE THREAD

**Issue by mehmetakifalp** [jquery-form/form#343]
Hi guys

My upload app not working IE Version 8-9
- Beforesubmit its working,

But "succes" or "error" not working.

I try latest version(malsup form) still not working.

thank you

**Comment by kanuj** [comment]
Facing this exact issue as well. The form submits properly in FF, Chrome and others, except in IE. The error I get: "SCRIPT438: Object doesn't support property or method 'ajaxSubmit' ". Help?

**Comment by officeallyandrew** [comment]
Yep same for me in IE9! Is there a solution for this?

**Comment by kevindb** [comment]
Are you still experiencing this issue?
