### ISSUE TITLE
IE9 problems when RESPONSE has a SCRIPT tag

### ISSUE THREAD

**Issue by lmiguelmh** [jquery-form/form#350]
Hi, IE9 has some issues when adding a script tag in the response. To replicate this, you could go to http://jquery.malsup.com/form/file-example.html , select any file and write in the input field: 

```
some text <script>$(function(){ alert("hola"); });</script>
```

You will see that Chrome really shows the alert message, but IExplore, yes, shows the message too but the Console tells a different story, and this gets worse in complex environments:

```
SCRIPT5009: '$' no está definido 
file-echo.php, Línea 3 Carácter 1
```

I think what is happening here is that IExplore for some reason is ignoring the libraries loaded at the beginning of the page (Could it be because the way IE is sending the file -iframe?). 

I was thinking that the solution could be adding the libraries in the response, but maybe there are other solutions.

Thanks in advance!

**Comment by kevindb** [comment]
Are you still experiencing this issue?
