### ISSUE TITLE
Option to use .serializeArray() instead of .serialize()?

### ISSUE THREAD

**Issue by jwvanderbeck** [jquery-form/form#354]
I want to send my data in a JSON format rather than query string.  When I roll my own code to do this I use form.serializeArray() instead of form.serialize().  Does this plugin offer a way to do this?

**Comment by malsup** [comment]
No, this plugin focuses on serializing and posting form data consistent
with the HTML spec.

**Comment by jwvanderbeck** [comment]
Ok well fair enough.  Shame though because this plugin does EVERYTHING I want in a nice easy package, with the exception of the data format.  The serialized string format is just yuck to work with on the back end :(

**Comment by malsup** [comment]
You can transform the data that is submitted using the beforeSubmit option.  That callback is passed an array-based serialization of the form data and you can manipulate the array contents to change what is posted to the server.

**Comment by jwvanderbeck** [comment]
Yeah but manipulating that array doesn't change the fact that the data is still posted to the server in a string format.  Unless I did something wrong.

**Comment by malsup** [comment]
You could take the given array as input, transform it into a single string
json value, and then leave the array with a single name/value pair where
the value is your JSON data.  I don't have an example, just speculating
that it may be possible using beforeSubmit.
