### ISSUE TITLE
IE issue with file upload and non-200 response

### ISSUE THREAD

**Issue by jshanman** [jquery-form/form#355]
When a file upload is included in a form and ajaxSubmit is used, if the response is non-200 (in our case, api returns a 400 if there was a server side validation problem), the xhr is aborted and responseText is not available, even though the request shows as completed with the full response body in the "network" tab of the developer tools.  Firefox and Chrome work fine.   

html

``` html
<html>
<head>
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
<script type="text/javascript" src="jquery.form.js"></script>
</head>
<body>
<form id="testForm" method="POST" enctype="multipart/form-data" action="400.php">
    <input type="text" name="testField1"/>
    <input type="file" name="testFile1"/>
    <input type="submit"/>
</form>
<script type="text/javascript">
$(document).ready(function() {
    $('#testForm').ajaxSubmit({
    success: function(responseText, statusText, xhr, $form) {
        alert('success: '+responseText);
    },
    error: function(xhr, status, errorThrown) {
        console.log(errorThrown+'\n'+status+'\n'+xhr.statusText);
        alert('error responseText: '+xhr.responseText);
    }
    });
});
</script>
</body>
</html>
```

400.php

``` php
<?php

header( 'HTTP/1.1 400 BAD REQUEST' );
echo "BAD REQUEST, but with a custom error";
```

**Comment by malsup** [comment]
In IE < 10 it is not possible to detect the 400 status response when uploading files.  If you have control over the entire error response body then you may place attributes on the `<body>` tag to inform the plugin of the status.

For example:  `<body status="400" statusText="Bad Request">`
