### ISSUE TITLE
iframe option never gets set as a POST

### ISSUE THREAD

**Issue by geoffreyk** [jquery-form/form#357]
using a call similar to this, the iframe always is set to a GET, never a POST

$(function() {
    $('#myForm').on('submit', function (e) {
        e.preventDefault();
        $(this).ajaxSubmit({
            url: 'urlToSubmitTo',
            dataType: 'json',
            type: 'POST',
            iframe: true,
            success: function (data) {
                //do stuff
            },
            error: function () {
                //do tuff
            },
            timeout: 15000
        });
    });
});

Some short debuging led me to:
#96     method = options.type || this.attr2('method');

so method === 'POST'
#482           if (!method) {
#483                form.setAttribute('method', 'POST');
#484            }

Since method === 'POST', no method attribute is ever set, so the form defaults to 'GET'

If I remove the 'type' option, line #96 will set method to 'GET', the default of the original form. Because there is a value in method, line # 482-4 will never set method attribute of the iframe form, and a default GET will be used. 

I did a quick fix in my copy of the plugin by changing line # 482
Before:
    if (!method) {
After my change:
    if (!method || method==="POST") {

Not sure if this is the best way to fix this or not.

**Comment by malsup** [comment]
Good catch, thanks.
