### ISSUE TITLE
IE 8-9 SCRIPT5: Zugriff verweigert (Access Denied) on Submit

### ISSUE THREAD

**Issue by Hackbard** [jquery-form/form#359]
Hi,
i'm trying to send my form with:

Form:

<form id="fileForm" method="POST" action="/cgi-bin/upload">
<input name="filename" type="file" id="filename"><br>
<input name="action" type="hidden" value="fileupload">
<a href="#" class="btn block" style="width: 105px; margin-top: 5px;" id="file-upload">Datei hochladen</a>
</form>

Send:
$("#file-upload").click(function(event){
    event.preventDefault();
    $("#fileForm").ajaxSubmit();
})

when i press the button i become this error:
SCRIPT5: Zugriff verweigert (Access Denied)
jquery.form.js, Zeile 554 Zeichen 21

in jquery form it is the line with "submitFn.apply(form);" in it.

I hope you can help

**Comment by kevindb** [comment]
Are you still experiencing this issue?
