### ISSUE TITLE
Access Denied in Firefox 22+

### ISSUE THREAD

**Issue by redthor** [jquery-form/form#361]
Since Firefox 22 I've been getting the dreaded CORS 'Access Denied' error.

It's in the getDoc method [here](https://github.com/malsup/form/blob/master/jquery.form.js#L450)

This is logged:
`[jquery.form] cannot get iframe.contentWindow document: Error: Permission denied to access property 'document'`

Created by:

``` javascript
 log('cannot get iframe.contentWindow document: ' + err);
```

What is really strange is that even though it's in a try catch block it doesn't seem to continue and then the `checkState()` method [here](https://github.com/malsup/form/blob/master/jquery.form.js#L505) ends up getting an undefined error for `getDoc(io).readyState` which triggers a server abort.

**Comment by redthor** [comment]
In the iframe there is:

```
<script type="text/javascript">
    document.domain = 'example.com';
</script>
```

What might be happening is that the checkState is run after the iframe is loaded but before the `document.domain = 'example.com';` has been executed (not sure how likely that is....).

These changes fix the problem for me:

```
--- a/jquery.form.js
+++ b/jquery.form.js
@@ -496,8 +496,11 @@ $.fn.ajaxSubmit = function(options) {

             // look for server aborts
             function checkState() {
+              var frameDoc;
+
+              if (frameDoc = getDoc(io)) {
                 try {
-                    var state = getDoc(io).readyState;
+                   var state = frameDoc.readyState;
                     log('state = ' + state);
                     if (state && state.toLowerCase() == 'uninitialized')
                         setTimeout(checkState,50);
@@ -509,6 +512,10 @@ $.fn.ajaxSubmit = function(options) {
                         clearTimeout(timeoutHandle);
                     timeoutHandle = undefined;
                 }
+             } else {
+                 log('no document available, retrying');
+                 setTimeout(checkState, 50);
+             }
             }

             // add "extra" data to form if provided in options
```

I am checking whether the getDoc method had returned something I can work on. However this is problematic as it may just keep re-trying... perhaps the timeout will kick in. I also need to test this with other browsers.

**Comment by kevindb** [comment]
Are you still experiencing this issue?
