### ISSUE TITLE
IE 8: $.fn.resetForm() removes "selected" property from option even though the select's selectedIndex points to the option

### ISSUE THREAD

**Issue by livefree75** [jquery-form/form#368]
I'm using $.ajaxForm() to add rows to a table.  The form contains some select-one select boxes that do not contain any non-empty options.  After a successful ajax submit, I reset the form:

```
$("#myForm").resetForm();
```

Looking at the code for this, it essentially just uses the form's built-in reset() method to reset the form.  Fine.

The select boxes revert to displaying the first option, as expected.
However upon a second submission, I see that the target URL does not receive the values of my select elements, unless I change them off of their initial values.

Using IE's developer panel, I discovered where the error(?) is:
in jQuery.form-3.40.js lines 1058-1080, we have this code:

```
if (tag == 'select') {
    var index = el.selectedIndex;
    if (index < 0) {
        return null;
    }
    var a = [], ops = el.options;
    var one = (t == 'select-one');
    var max = (one ? index+1 : ops.length);
    for(var i=(one ? index : 0); i < max; i++) {
        var op = ops[i];
        if (op.selected) {
            var v = op.value;
            if (!v) { // extra pain for IE...
                v = (op.attributes && op.attributes['value'] && !(op.attributes['value'].specified)) ? op.text : op.value;
            }
            if (one) {
                return v;
            }
            a.push(v);
        }
    }
    return a;
}
```

At this point, the `el.selectedIndex` is indeed `0`, but `el.options[0].selected` is `false`.
Not sure if this is an IE 8 bug (haven't tested it on later versions, but it works fine in Firefox of course).  But, why do you not just use $(el).val() (which would work for select-multiple as well)?

**Comment by kevindb** [comment]
Are you still experiencing this issue?
