### ISSUE TITLE
ie7-9 error

### ISSUE THREAD

**Issue by l12ab** [jquery-form/form#369]
I test my code on IE7-10, FF & Chrome, its works fine on ie10, ff & chrome,but error on ie7-9.

SCRIPT5:  
jquery.form.js, line 554 character 21

submitFn.apply(form);

but your demo code works fine

dont know why

**Comment by malsup** [comment]
Are you uploading files?  Are you trying to submit the form in response to a file being selected?  That's not allowed in IE.
