### ISSUE TITLE
xhr.responseText problem

### ISSUE THREAD

**Issue by sebabal** [jquery-form/form#37]
hi,

we recently upgraded to the newest version (from 2.43) and are having some problems at the success function, we output using php json_encode some status messages, etc but with the newest version 2.47 we are not getting anything.

if we go to line 352 and change the following:
xhr.responseText = doc.documentElement ? doc.documentElement.innerHTML : null; 

to the way it was before:
xhr.responseText = doc.body ? doc.body.innerHTML : null;

it works without problem so maybe we are doing something wrong.
any help would be greatly appreciated.

warm regards,
sebastian baldovino

**Comment by malsup** [comment]
I think this is now fixed.
