### ISSUE TITLE
IE8 bug when adding additional data to formData with enctype="multipart/form-data" defined

### ISSUE THREAD

**Issue by 12hys** [jquery-form/form#371]
Why does IE8 not push values onto the formData array when enctype="multipart/form-data" is set on the form?

Chrome and FF are able to do this. Tested on v20130616.

Example code (this is not meant to run on jsFiddle): http://jsfiddle.net/f6Uwz/

When I run the above code on IE8, my PHP script on the back end gives me the error:

```
PHP Notice:  Undefined index: test
```

As soon as I remove the enctype on the form, everything works in IE8.

Is this a bug?

**Comment by malsup** [comment]
Try this:

```
var options = {
    dataType : 'xml',
    beforeSerialize : validate_form
};

$( '#test_form' ).ajaxForm( options );

function validate_form( formData, jqForm, options ) {
    options.data = { test: 'testvalue' };
}
```

**Comment by 12hys** [comment]
That doesn't work. The "data" property is still null after you try to set it in validate_form().

This is the code:

``` javascript
function validate_form( formData, jqForm, options ) {
    options.data = { test: 'testvalue' };
    console.log( options );
}
```

http://i.imgur.com/sU7eeRc.png

I've got a working fiddle here: http://jsfiddle.net/f6Uwz/1/

Open up your dev tools and hit submit. Inspect the options object.

**Comment by 12hys** [comment]
By the way, the workaround I've implemented uses a hidden input in the form and the beforeSerialize callback. What I'm doing is validating what I need to in beforeSerialize and setting the value of this hidden input once validation is complete. Once the plugin serializes the form elements, it picks up the hidden input.

I would still like to know why IE8 fails to add the key/value pair when the enctype is set to "multipart/form-data".

**Comment by malsup** [comment]
Sorry, the code should look like this:

```
$(function(){
    var options = {
        dataType : 'xml',
        beforeSerialize : validate_form
    };

    $( '#test_form' ).ajaxForm( options );

    function validate_form( jqForm, options ) {
        options.data = { test : 'test_value' };
    }
});
```

Note that beforeSerialize is used instead of beforeSubmit, and the args to validate_form are different.

**Comment by malsup** [comment]
IE < 10 follows a different path in the code because those browsers don't support XHR2.  The "data" option is your way around the limitation.

**Comment by 12hys** [comment]
This works, thank you very much. I should probably switch all my validation over to beforeSerialize so that I wont run into this issue again.
