### ISSUE TITLE
.ajaxFormUnbind() callback needed

### ISSUE THREAD

**Issue by goneglobal** [jquery-form/form#372]
Can you please add a call back to .ajaxFormUnbind() - I need to trigger events after this occurs. I tried updating the plugin myself but I'm not that experienced - tried below but didn't work... thankyou so much!

$.fn.ajaxFormUnbind = function(callback) {
    callback = callback || function(){};
    return this.unbind('submit.form-plugin click.form-plugin', callback);
};

**Comment by kevindb** [comment]
~I am closing this issue due to a lack of activity. If you still need help, please comment and we can reopen.~
Scratch that. Fixed by #566
