### ISSUE TITLE
Access Denied Error on IE9 on line 558 of jquery.form.js

### ISSUE THREAD

**Issue by surajreddy** [jquery-form/form#374]
Hi there,

I have a hidden file input that I programatically click when another button is clicked with $('#file_input').click();

When submitting this form with ajaxSubmit(), I'm getting an "Access is denied." error on line 558 - submitFn.apply(form);.

This method of choosing the file input seems to work fine in chrome.

Problem code in jquery.form.js:

```
                try {
                    form.submit();
                } catch(err) {
                    // just in case form has element with name/id of 'submit'
                    var submitFn = document.createElement('form').submit;
                    submitFn.apply(form);
                }
```

**Comment by surajreddy** [comment]
I think this is more of an ie issue with my method of clicking the file input than jquery form.

**Comment by surajreddy** [comment]
Confirmed: It wasn't related to the form plugin, it's a security issue with ie. Following this suggestion I simply themed the input instead of programatically triggering it - http://stackoverflow.com/questions/8350927/file-upload-button-without-input-field/8350966#8350966

**Comment by hayageek** [comment]
Suraj,
Simple solution for IE8,IE9 is.

```
<form >
<label for='fileid'>Upload</label> //This is shown to user.
<input type='file" id='fileid' style="position:absolute;left:-500px;" />  //This is not visible to User.

</form>
```

If you click on 'label' , file dialog is opened. It works in IE8,IE9.

**Comment by surajreddy** [comment]
Thanks @hayageek! That seems like a really simple solution. Why don't more people use it?

**Comment by hayageek** [comment]
I am using the same technique in my plugin.
https://github.com/hayageek/jquery-upload-file

**Comment by surajreddy** [comment]
Great, thanks @hayageek! I noticed that it doesn't work in some versions of firefox and opera - https://bugzilla.mozilla.org/show_bug.cgi?id=701353 - so I might stick with the css option.

**Comment by hayageek** [comment]
Yes, This works fine IE. So I am using it only for IE

**Comment by surajreddy** [comment]
That makes sense. Thanks!
