### ISSUE TITLE
How to prevent keyup

### ISSUE THREAD

**Issue by yourchoice** [jquery-form/form#375]
Hi,

I have a form with more actions. Here I refer to a filed in form used for an ajax search.

I try to prevent enter key, but ajaxForm have priority and submit the form.

$('#field').keyup(function(event) {
         var code = (event.keyCode ? event.keyCode : event.which);
          if(code==13)  {   event.preventDefault(); }

....
});

I tryed all of these:
$(this).closest('form').ajaxStop();
        event.preventDefault(); 
        event.stopImmediatePropagation(); 
        event.stopPropagation();

Can you help me?

Thank You!

**Comment by aland** [comment]
I guess you don't care after such a long time, but I faced a similar issue and solved it by using `keypress` rather than `keyup`
e.g.

```
$('#field').keypress(function(event) { 
    if (event.which === 13) {
      event.preventDefault();
      // ....
    }
});
```

**Comment by yourchoice** [comment]
Hi, 

Yes, I forgot about this issue, but thanks for your answer.
