### ISSUE TITLE
Redirect user after completion

### ISSUE THREAD

**Issue by henrywright** [jquery-form/form#378]
This is what I currently have:

`complete: function() {
    status.text('Success!');
}`

It just outputs a line of text.

Instead of outputting this text, how can I redirect the user to a specific URL? My form is being used to create a new WordPress post so it captures a post title, content and an optional file. On form submission, a new WordPress post is created which gets given an auto generated post ID.

The URL I need the user to be redirected will therefore look like `example.com/367` where '367' is the auto generated post ID.

**Comment by malsup** [comment]
Instead of status.text('Success!'); do this:

```
location.href = 'example.com/367';
```

**Comment by henrywright** [comment]
Thanks @malsup - although I'm now stuck again as 367 is hard coded. I need to somehow get the ID of the new WordPress post that is created to replace the 367.

This is how I'd get the post ID with PHP:

``` php
if( isset( $_POST['post_id'] ) )
$post_id = $_POST['post_id'];
```

I am struggling with how to do it with Javascript:

```
complete: function() {
    location.href = 'example.com/367';
}
```

Any ideas? I'm aware this might be slightly out of support scope but I'd be grateful for any help.

**Comment by malsup** [comment]
You should return it from the POST request so that you can do something like this:

```
success: function(data) {
    // for example, if you return a JSON object:  { "redir": "example.com/367" }
    location.href = data.redir;

    // if you return just the page url:
    location.href = data;
}
```
