### ISSUE TITLE
File Upload Progress issue with smaller files in Chrome

### ISSUE THREAD

**Issue by hayageek** [jquery-form/form#379]
Hi,
I have tested file upload  in Chrome 31.0  ( Mac OS).

For smaller file uploads, before the file is uploaded to server  progress % becomes 100%.
I mean, with seconds progress becomes 100%, but the file is uploaded after sometime.

http://hayageek.com/examples/jquery/ajax-file-upload/small.php

**Comment by malsup** [comment]
Seems to be working well to me.  The plugin can't control when the browser reports upload completion.
