### ISSUE TITLE
What version of jquery does this work with, I'm finding any version over 1.8.3 fails 

### ISSUE THREAD

**Issue by applemad** [jquery-form/form#381]
I was just wondering what the official highest version of jquery is that this works with, it works sweetly as far as I can see with 1.8.3 but as soon as I try any version higher than this, the forms submit and the response comes back with a page refresh instead of as an ajax update.

Am I missing something ?

**Comment by malsup** [comment]
You must be missing something.  Are you using an old version of the plugin?  The plugin page itself uses jQuery 1.9.1 and works just fine.

http://jquery.malsup.com/form/#ajaxForm

**Comment by applemad** [comment]
Hi Mike, thanks for the swift reply, yes I downloaded the latest version last night as I realised the one we had was about a year out of date, but unfortunately exactly the same issue, as soon as I increase the Jquery version number beyond 1.8.3 it fails to reload the page as an ajax update and does a whole page refresh, very strange...  :-(

**Comment by malsup** [comment]
Well, there must be an error occurring somewhere.  Is there a message in the console?

**Comment by applemad** [comment]
I'll see if I can find something, I'm no javascript expert by any stretch of the imagination, more a PHP and MySQL guy, but I'll see if I can track down more details for you and give you a clue lol, it's running on our beta server I work for one of the UK's largest nursery chains and I've got it running on our own CMS system so it's difficult for me to give you access to it to see the issue, I'll get back with more details as soon as I can ;-)

**Comment by applemad** [comment]
Mike reference to my previous posting, I have found the issue, it's actually errors in an older version of fancy box that we use on the web page which is causing issues for ajaxform, I've just installed the latest version of fancy box and now the console is throwing no errors and ajaxform is working properly as expected, so I need to wade through all of our CMS and update all instances of fancy box which is probably long overdue anyway.

Thanks for your swift responses though, much appreciated as is your excellent scripting.

;-)
