### ISSUE TITLE
iFrame default value when passing options

### ISSUE THREAD

**Issue by Furynation** [jquery-form/form#382]
It appears the iFrame default value is being set to true instead of false like the documents state.

Example: 

$("#myForm").ajaxSubmit({
                        iframe: false,
                        success: function(xhr, status, successMsg) {
                            alert("Success");
                        },
                        error: function(xhr, status, errorMsg) {
                            alert("Failure");
                        }
                    });

The success and error handlers never get called unless 'iframe: false' is added to the options.

**Comment by kevindb** [comment]
Are you still experiencing this issue?
