### ISSUE TITLE
Analyze form submit returned string  before putting it in target.

### ISSUE THREAD

**Issue by afattahi54** [jquery-form/form#384]
Is it possible to have a call back function which works on returned value when sending a form via ajax.

I am looking for something like this:

1- Click on submit button
2- The form data is serialized to server and the response is turned back. The form should not be submitted only the data should have been sent. 
3- I wand to analyze returned string.
4- If the input has a certain logic the target should be invoked
5- If not another function should be called.

I could not find how can I do step 4, that is analyze data before showing them in target.

I need because, I may face some errors while I submit the form at the server side. So I want the user could still see the form plus the server error message. 

Regards,
Alireza

**Comment by malsup** [comment]
I'm assuming you mean that you're using the "target" option to instruct the plugin where to place the server response.

If you need that level of control then you should not use the "target" option and instead just use the "success" option.  For example:

```
$('#myForm').ajaxSubmit({
    success: function(data, status, xhr) {
        if ( data == 'somethingSpecial' )
            doSomethingSpecial();
        else
            $('#myTarget').html( data );
    }
});
```
