### ISSUE TITLE
Field order

### ISSUE THREAD

**Issue by tremby** [jquery-form/form#385]
I want to post a file to Amazon S3 to be stored in a bucket. I have the form working without this plugin, but when I enable it and submit things no longer work.

Amazon is very particular that the file field is the very last one passed, so I took care in the markup to make sure it comes last (in case it's relevant, in this particular case I'm using the HTML5 `form` attribute -- the `input type="file"` element isn't actually a child of the `form` element it references). But when posting with this plugin the file is the first field posted.

I've tried with the `iframe` option both off and on.

Would it be possible to keep the markup order of fields?

Obviously this is a stupid limitation of the Amazon API, but I doubt it's easy to persuade them to change how they do things.

**Comment by malsup** [comment]
Have you tried using the option:  `semantic: true`?

**Comment by tremby** [comment]
Wow, thanks for the very speedy response.

I had not spotted that option. I tried it just now and it seems to make a mess of things.

If I watch the net debug panel, I see that the uploaded POST data is now this:

```
-----------------------------17483824651045347354589262571--
```

That's all -- it's just the Mime boundary. Perhaps this has uncovered a bug with the `form` attribute? I'll see if I can dig deeper...

**Comment by tremby** [comment]
I was an idiot and was disabling the form fields before the submit call. Moving that to after the submit call uncovers most of the form fields, but there is no file being uploaded. It looks like the `formToArray` method is just looping through children of the form element. In this case my `file` input is not a child of the form so it's being skipped. So this is now a feature request: please include other input elements which reference the form with the `form="form-id"` attribute.

**Comment by tremby** [comment]
Also worth noting that though I didn't see the `semantic` option at all, its documentation suggests that I should have ignored it anyway -- I am not using an `input type="image"` element. Yet it is still relevant to me. Perhaps the documentation could be tweaked here.

**Comment by tremby** [comment]
Changing line 910 to

```
    var els = $('[form="' + form.getAttribute('id') + '"], #' + form.getAttribute('id') + ' *').toArray();
```

does the trick for me, but it's a hack which relies on the form having an ID element. I'll put something a little more bulletproof together in a fork.

**Comment by malsup** [comment]
Fix in latest update.
