### ISSUE TITLE
When using ajaxSubmit with iframe:true, success is never fired

### ISSUE THREAD

**Issue by itaizi** [jquery-form/form#387]
Hi Malsup, thanks for the great plugin.

I am calling ajaxSubmit for file upload and use iframe:true (to support IE 8/9).
The problem is that my success callback is never fired, and I get a popup to download file with the json response in it.

How can I "catch" the response and show a message to the user based on it?

Thanks, Inbal.

**Comment by malsup** [comment]
Read here about how to handle json responses in iframe mode:

http://jquery.malsup.com/form/#file-upload

```
<textarea>  json data here </textarea>
```
