### ISSUE TITLE
Access to form context during uploadProgress

### ISSUE THREAD

**Issue by Rule-Books** [jquery-form/form#389]
Hello Mike

Thank you for your great plugin and all the work you have put in!

Suggestion:
To keep the form as generic as possible I wanted to have the current form context exposed in uploadProgress.

I added it myself (see below) and it seems to do the job.
If it makes sense to you, maybe you want to consider adding this (or something similar) to your module? Let me know what you think.

see: 
<code>var context = $form.context:</code>
and:
<code>options.uploadProgress(event, position, total, percent, context)</code>

<code>if (options.uploadProgress) {
            // workaround because jqXHR does not expose upload property
            s.xhr = function() {
        var context = $form.context;
                var xhr = $.ajaxSettings.xhr();
                if (xhr.upload) {
                    xhr.upload.addEventListener('progress', function(event) {
                        var percent = 0;
                        var position = event.loaded || event.position; /_event.position is deprecated_/
                        var total = event.total;
                        if (event.lengthComputable) {
                            percent = Math.ceil(position / total \* 100);
                        }
                        options.uploadProgress(event, position, total, percent, context);
                    }, false);
                }
                return xhr;
            };
        }
</code>

**Comment by kevindb** [comment]
Would you please submit this suggestion in the form of a pull request?
