### ISSUE TITLE
File upload on firefox with application/json response

### ISSUE THREAD

**Issue by diegok** [jquery-form/form#39]
When using ajaxForm over a file upload form that get back an application/json response from the server, FF is giving a file download dialog and 'success' event isn't called. It works ok on chrome and safari.

I can fix the problem changing content-type to text/plain for json responses. But it doesn't look like the right direction. I'm missing something?, is this something that should be fixed on FF and nothing can be done here?

Googling a bit tells me I'm not the only one having this issue: http://stackoverflow.com/questions/2755802/jquery-ajaxform-returning-json-file

**Comment by jstates** [comment]
Did that fix the problem, I have the same problem.  FF wants to download the json response, not parse it in the callback.

**Comment by lamtha** [comment]
duplicate of ticket 36 http://github.com/malsup/form/issues#issue/36

**Comment by malsup** [comment]
If you embed your response json in a textarea element everything will work fine:

```
<textarea>{ "my": "response" }</textarea>
```

**Comment by diegok** [comment]
Hm, that looks like a worst workaround than placing an incorrect mime-type on the response to me. Which is the real problem here?, isn't it a FF problem?

**Comment by malsup** [comment]
The problem requires a workaround so pick your poison.

**Comment by diegok** [comment]
Seems like it. I'm already poisoned with my proposed solution, but I wonder how to report this to mozilla as a FF bug. It's a FF bug, right?

**Comment by malsup** [comment]
No, it's not a bug.  The browser can be configured to take various actions based on the mimetype of the response.  But there is no way for javascript to effect that configuration.  Note that when I add FormData support to the plugin this issue should resolve as genuine ajax will be used for the upload.  Hope to have that added within the next couple weeks.

Worth reading:  http://kb.mozillazine.org/File_types_and_download_actions

**Comment by diegok** [comment]
Thank you!

**Comment by odahcam** [comment]
I recomend to take a look in: #448

Also, `text/x-json` works better than `text/plain`, for semathic reasons.
