### ISSUE TITLE
IE8 ajaxForm issue. Incorrectly collect form data

### ISSUE THREAD

**Issue by monco83** [jquery-form/form#390]
I'm using ajaxForm and has no data in request.
I got around the problem code modifying:

in _formToArray function replaced

```
if ( els ) {
        els = $(els).get();  // convert to standard array
    }
```

by new code:

```
if (els && !/MSIE 8/.test(navigator.userAgent)) {
        els = $(els).get();  // convert to standard array
    }
```

**Comment by toneplex** [comment]
I ran into the same issue with IE8 and this fixed it. Thanks @monco83

**Comment by stefetom** [comment]
hello,
Exactly same problem for me, and same solution.
Thanks too.
Can official repository be update ?
PS. I'm french, sorry for my approximative english

**Comment by pgioseffi** [comment]
This problem seems to be happening with other methods such as formSerialize. Maybe they're all using formToArray method inside which is the method that caused me problems in this version.

**Comment by malsup** [comment]
Fixed.  Sorry for the delay.

**Comment by freeman983** [comment]
@malsup  I get same problem in IE7

**Comment by ghost** [comment]
@malsup Please include the "IE 678" solution of webgal to codebase.

The current version with "IE 8 only" check breaks e.g. current release of "Contact Form 7" plugin for WordPress with IE7.

http://wordpress.org/support/topic/sending-formdata-to-server-broken-in-ie7

**Comment by Tjalle** [comment]
The fix works,
But here is a small tip for the people struggling with this.
I downloaded this code a month or so ago, and in the minified version wasn't updated yet.

So if in doubt, try the non minified code if you want to save yourself some time.

**Comment by guantou** [comment]
actually, ie9 has a “Compatibility Mode”， which button after the browser address . when turn it on , ajaxform also can not post any filed prarm. may be the code need add the check of ie9 。

**Comment by pokej6** [comment]
In IE8, I'm having the opposite problem. I need this conversion to happen. If I comment out the regex part of the conditional the code works. Otherwise, it errors and asks me to debug.

Edit: els is of type DispHTMLFormElement

**Comment by nimasmi** [comment]
Because of [this wontfix jquery bug](http://bugs.jquery.com/ticket/2114), I get the following in IE8:

``` javascript
>> form.elements.length
76
>> els2.length
2
>> form.elements.concat(els2)
"Object doesn't support this property or method" // does nobody else see this?
>> $(form.elements).get().concat(els2)
{...}                                  // looks good…
>> $(form.elements).get().concat(els2).length
3                                      // huh?
>> $(form.elements).get().length
1                                      // oh - I guess this is why this ticket was opened
>> $.makeArray(form.elements).concat(els2)
{...}
>> $.makeArray(form.elements).concat(els2).length
78                                     // this has the desired effect
```
