### ISSUE TITLE
Unable to pass $.ajax always as option

### ISSUE THREAD

**Issue by eclipxe13** [jquery-form/form#391]
Hello, from your page says that _"Aside from the options listed below, you can also pass any of the standard $.ajax options to ajaxForm and ajaxSubmit."_

The option always(handler) is not working.

Looks like this plugin is using the success, error and complete callbacks and that will be deprecated: 

> Deprecation Notice: The jqXHR.success(), jqXHR.error(), and jqXHR.complete() callbacks are deprecated as of jQuery 1.8. To prepare your code for their eventual removal, use jqXHR.done(), jqXHR.fail(), and jqXHR.always() instead.

I can work arround by this using:

``` javascript
// this does not work:
$('#form').ajaxSubmit({
    always: function() {
        /* ... */
    },
    /* ... */
});

// this is a workaround
$('#form').ajaxSubmit({
    /* ... */
}).data('jqxhr').always(function(){
    /* ... */
});

// this works but will be deprecated
$('#form').ajaxSubmit({
    complete: function() {
        /* ... */
    },
    /* ... */
});
```

In the issues I've seen that you are planning a new version "form2", thats good news! Thanks for your effort and software!

**Comment by malsup** [comment]
'always' is not a valid $.ajax option, it is a method on the promise object returned from the $.ajax() call.  The success/error/complete options used by this plugin are not deprecated.  What's deprecated are the success/error/complete methods on the jqXHR object.

Your workaround is the correct way to access and use the promise with ajaxSubmit.  Alternatively you could use the 'complete' option.

**Comment by eclipxe13** [comment]
You're right, I read the docs from http://api.jquery.com/jQuery.ajax/ but didn't notice that always is not part of the options. Thanks a lot!
