### ISSUE TITLE
<button> tag values are not submitted

### ISSUE THREAD

**Issue by timesheep** [jquery-form/form#393]
When you submit a form using jQuery forms using buttons with the button tag, the values set by the buttons are not sent to the action script.
To reproduce:
- Create a handler that simply prints the $_GET superglobal array
- Write a form along the lines of

```
    <form action="testscript.php" method="get">
        <button name="action" value="1">Accept</button>
        <button name="action" value="0">Reject</button>
    </form>
```
- Press either button, $_GET is empty.

**Comment by malsup** [comment]
You need to use ajaxForm to capture the submitting element (not ajaxSubmit).
