### ISSUE TITLE
JSON iframe

### ISSUE THREAD

**Issue by jtousek** [jquery-form/form#4]
When I have some HTML in the JSON object, I get &amp;lt; instead of < and &amp;gt; instead of > and so on.
This modification fixed the problem.:

Line 320:
xhr.responseText = pre.textContent;

There is innerHTML instead of textContent now. But that returns something like php func htmlspecialchars - chars like < and > are encoded to their entities which is bad.

**Comment by gucki** [comment]
This bug still exists in version: 2.43 (12-MAR-2010). I found it while working rails 3.

The suggested fix works fine for me (firefox 3.6). Only the line changed from 320 to 327.

**Comment by malsup** [comment]
What browser does this occur on?  Can you create a simple test page for me? Thanks.

**Comment by djcas9** [comment]
Same Issue - This is a problem on Max OSX, Windows - tested with all browsers.

**Comment by jtousek** [comment]
I'm not sure it's the only problem, anyway I've used <textarea> tag and it works just fine. :)

**Comment by softlion** [comment]
+1

**Comment by ulmus** [comment]
I can attest both to the problem still existing (osx and win, all major browsers) and that the patch fixed the problem for me. Was losing my mind until I saw this bug report!

**Comment by malsup** [comment]
Fixed in v2.50. Thanks for all the feedback.
