### ISSUE TITLE
"extra data" escaping issue (patch included)

### ISSUE THREAD

**Issue by chrisnetonline** [jquery-form/form#40]
if you try to inject a json string as the value of extra data using the data option the double quotes in the string mess up the value of the field.

SUGGESTED PATCH:
http://gist.github.com/624099

**Comment by nylen** [comment]
chrisnetonline,

It would be much more convenient for the developer if you fork the repository, commit and push this change to your copy, and send a pull request with the change.  Alternatively (especially if you're not familiar with git/github) you could put your patch file on http://gist.github.com/ and link to it.  As it is, your patch is unreadable.

**Comment by chrisnetonline** [comment]
apologies! i've updated my comment.

**Comment by malsup** [comment]
Thanks!  That patch would have been difficult to read if you'd changed more than two lines.  :-)

**Comment by chrisnetonline** [comment]
;)

**Comment by malsup** [comment]
Fixe will land in next update.
