### ISSUE TITLE
Bower pulls 3.46 when 3.50 was released a month ago

### ISSUE THREAD

**Issue by tedberg** [jquery-form/form#402]
bower install jquery-form --save

Not only gives an old version, but also logs a warning:
bower jquery-form#\*           mismatch Version declared in the json (3.45.0) is different than the resolved one (3.46.0)

I've been using 3.49 for a while before moving to grunt/bower, now this gives me a downgraded version.

bower.json lists 3.45 as the version, while .bower.json lists 3.46.

**Comment by rosenfeld** [comment]
Isn't this caused by the version being 3.50 instead of 3.50.0? I think bower expect versions to follow the semver specs. I'd love to be able to use 3.50 with bower as 3.46.0 prints some deprecation warnings on Chrome with regards to Attr.specified.

**Comment by rosenfeld** [comment]
Actually, I believe the bug is still present on 3.50 as the source-code doesn't seem to have changed for that part. I'll create another issue.

**Comment by kevindb** [comment]
Probably resolved by 0dc9b4e
The new release has just been posted. I'll check back in a day or two to see if the package managers have picked up on the new version.

**Comment by kevindb** [comment]
Bower has been updated with [v4.1.0](https://github.com/jquery-form/form/releases/tag/v4.1.0)
