### ISSUE TITLE
Uploading multiple files with same name leads to only one file being uploaded multiple times

### ISSUE THREAD

**Issue by jtammen** [jquery-form/form#403]
Hi,

we came across following issue: When a form handled by `ajaxForm` contains a file input with `multiple` and you select multiple files with the same file name, only one of them gets uploaded, but _n_ times.
It was initially reported for Safari on iOS, as selecting files (only images from them gallery can be selected) seems to name _all files_ as "image.jpeg". This issue is reproducible in other browsers (tested in Chrome) as well: just try to upload multiple files with same file names contained in different folders. Only one of them will be uploaded.

We are using version 3.50.

Any idea how to work around this issue?

**Comment by kevindb** [comment]
Are you still having this issue with version 4.1.0? If so, would you please create an example of the error on [CodePen](https://codepen.io/) or [JSFiddle](https://jsfiddle.net/)?

**Comment by jtammen** [comment]
@kevindb Has been a looong time … not using jQuery Form anymore, so I fear I cannot provide any feedback ;-)
