### ISSUE TITLE
ajaxSubmit Should Return jQXHR, not this

### ISSUE THREAD

**Issue by rdfedor** [jquery-form/form#404]
ajaxSubmit should match jQuery's ajax function in the sense that both should return a jQXHR object as documented in the jQuery API to allow for the use of the .done, .fail and .always methods associated with the object.

Example
$(this).ajaxSubmit().done(function(data) { ... }).fail(function(err) { ... });

or if you want consistency with jQuery functions where if you call $(this) and it should return $(this), then I would suggest it be set up as follows

$.ajaxSubmit({ form : $(this) }).done(function(data) { ... }).fail(function(err) { ... });

**Comment by malsup** [comment]
You can do this:

```
$('form').ajaxSubmit().data('jqxhr').done(function() {} );
```
