### ISSUE TITLE
warning in Chrome: "Attr.specified is deprecated. Its value is always true."

### ISSUE THREAD

**Issue by rosenfeld** [jquery-form/form#405]
This line assumes that if value is empty it must be an IE specific problem:

https://github.com/malsup/form/blob/master/jquery.form.js#L1147

But it happens that option values can be empty and this is a common practice for the first element that could mean something like "[please select]".

But calling `attribute.specified` is deprecated in both Firefox and Chrome. If this is needed for some old IE version, it should be called only in such cases.

**Comment by kevindb** [comment]
Are you still seeing this issue?
