### ISSUE TITLE
How to Add Option to already inited ajaxForm?

### ISSUE THREAD

**Issue by gam6itko** [jquery-form/form#406]
Hello.

I have code, where ajaxForm applies to every form.

```
    $('form').ajaxForm({
        method: 'post',
        dataType: 'json'
    })
```

But in some time i need to add specific success handler.

```
$('#specialForm').ajaxForm({
       success:function(data){
            //do something with data
        }
    })
```

If i will do second call of ajaxForm the previous options will be overwritten, and specialForm will not has  ( method: 'post',  dataType: 'json') options.

How i can add additional options to already inited ajaxForm ?

I need something like in jquery UI http://api.jqueryui.com/datepicker/#method-option

**Comment by Azuka** [comment]
This is an important feature, especially when I have one handler for all forms and want to add validation before submitting to just one of them.

**Comment by bulychev** [comment]
+1

**Comment by kevindb** [comment]
I am closing this issue due to a lack of activity. If you still need help, please comment and we can reopen.
