### ISSUE TITLE
Response parse fails after file upload

### ISSUE THREAD

**Issue by litvinenkow** [jquery-form/form#410]
Full message is in attached file, because parser eats data at all.

In IE 7-9 there is an error when parsing JSON. Tags are cut down. Javascript is not evaled. 
Native JQuery ajax function parse similar JSON data without problems same as your plugin working in Firefox and Chrome, but not IE.
Can you explain this behaviour and maybe make some improvements?

Text representation of full message is here.
http://rghost.ru/55009624

**Comment by kevindb** [comment]
Are you still experiencing this issue?
