### ISSUE TITLE
response text: selected #my_id in #target

### ISSUE THREAD

**Issue by santaclaus21** [jquery-form/form#411]
I'm using this plugin from a few years. I love it. But it wil be great making possibility of returning just selected ID to target instead of all response text.
I was trying to make own reponse function without success.

What I need is returning to "target" only #my_id instead of full response text.

Is that possible ? I mean something like jquery load
$("#target").load("file_to_load.php" #my_id....)

I need to do something like that with ajax form. I need to show only part of response in target.

Any help?

**Comment by kevindb** [comment]
Are you still experiencing this issue?

**Comment by santaclaus21** [comment]
I will appreciate. In similar cases I am using $.ajax and filter/find function.

**Comment by kevindb** [comment]
Would you please create an example of the feature you're asking for on [CodePen](https://codepen.io/) or [JSFiddle](https://jsfiddle.net/)?

**Comment by santaclaus21** [comment]
Something like this (see success function - this return only filtred part of ajax answer): 

```
var xhr;

function filtruj(add_get)
{
  var ajax_params = $("#fszukajka :input[name!='co']").serialize() + ((typeof(add_get) === 'undefined') ? '' : add_get);
  
  $("#content").html("<div style='margin: 0 auto; text-align: center;'><img src='/_img/loader10.gif' /></div>");
  xhr = $.ajax({
            url: window.location.pathname,
            data: ajax_params, 
            beforeSend : function()    {           
                  if(xhr != null) { xhr.abort(); }
            },
            success: function (data) {                 
                $("#content").html($(data).find("#content > *"));
            }
        });      
}
```

**Comment by kevindb** [comment]
I think it would be most effective to use the [success callback](https://github.com/jquery-form/form#success), and put your "response targeting" logic there, just like you've done in your example.
```javascript
success: function (data, textStatus, jqXHR, $form) {
  $("#content").html($(data).find("#content > *"));
}
```

**Comment by santaclaus21** [comment]
Ok, it may be done in that way.
