### ISSUE TITLE
Blank "action" attribute submits back to wrong page in IE when HTML 5 doctype is used. 

### ISSUE THREAD

**Issue by gitrandynow** [jquery-form/form#412]
When <!DOCTYPE html> is used, Internet Explorer returns an incorrect value for an empty "action" attribute when referenced via formElement.action. Instead of returning an empty string, it returns the full URL of the current page's parent folder! 

The reason I am bringing this up here is because this plugin's _attr2_ function defaults to using _$.fn.prop_ to retrieve the form's action attribute which causes the form to be submitted back to the incorrect page. I have fixed the problem on my sites by changing  _ajaxSubmit()_ and _doSubmit()_ to use _this.attr('action');_ instead of _this.attr2('action');_

**Comment by malsup** [comment]
There are other issues that are fixed using attr2.  Have you considered not using a blank action attribute?

**Comment by gitrandynow** [comment]
Unfortunately, that's not an option. Is there a reason why attr2 tries prop first rather than attr? As I understand it, the issue that attr2 fixes is that in some circumstances attr is not available, so wouldn't it be less of a deviation from the original code that's been in use for years to first check attr, and if it's not available then use prop?

**Comment by justim** [comment]
I've run into this issue as well and solved this by removing the attribute all together, the [spec](http://www.w3.org/html/wg/drafts/html/master/semantics.html#attr-fs-action) says an empty `action` attribute is not valid.

> The action and formaction content attributes, if specified, must have a value that is a valid **non-empty** URL potentially surrounded by spaces.

_(emphasis added)_
