### ISSUE TITLE
Please add documentation into GIT

### ISSUE THREAD

**Issue by gaboom** [jquery-form/form#42]
Dear Malsup,

I just started using your jquery plugin, and it's totally amazing. Would it be possible to add the documentation available from your webpage (http://malsup.com/jquery/form/) under revision control?

Cheers,
Gábor

**Comment by kevindb** [comment]
Some assistance moving the documentation into Github Pages would be appreciated.

**Comment by AzureByte** [comment]
Hi, I found this project via issuehub.io and would like to help move the documentation to Github Pages. Are you looking to make the Github Pages version of the documentation a copy of the site at http://malsup.com/jquery/form/ or is it just the content?

**Comment by kevindb** [comment]
Thank you for reaching out to help!
I'm just looking to copy the content from http://malsup.com/jquery/form/, not the design.
I've already copied over content from all the pages except [Examples](http://malsup.com/jquery/form/#ajaxForm) and [Form Fields](http://malsup.com/jquery/form/#fields).

Another task that needs doing is updating the [API](https://jquery-form.github.io/form/api/) and [Options](https://jquery-form.github.io/form/options/) pages with newer information from the [API](https://github.com/jquery-form/form#api) and [Options](https://github.com/jquery-form/form#options) section of the repo's README.md.

The Github Pages site is hosted from the /docs folder. Pull requests into the `develop` branch would be preferable.
https://github.com/jquery-form/form/tree/develop/docs
There are two new empty files: [examples.md](https://github.com/jquery-form/form/blob/develop/docs/examples.md) and [form-fields.md](https://github.com/jquery-form/form/blob/develop/docs/form-fields.md)

**Comment by AzureByte** [comment]
Okay great! I've managed to set up the documentation on my fork and I'll work on getting the Examples and Form Fields pages into a PR soon. Will go over the API and Options pages next.

**Comment by AzureByte** [comment]
#520

**Comment by AzureByte** [comment]
@kevindb  Opened a PR here #520 Contains the Examples and Form-fields pages. Could not get the examples to update in the output div after clicking submit. Help on how to do that would be appreciated.
