### ISSUE TITLE
Add error callback arguments to the documentation

### ISSUE THREAD

**Issue by fletchowns** [jquery-form/form#422]
The documentation for the error callback is missing the list of arguments: http://malsup.com/jquery/form/#options-object

From what I can tell the arguments are:

``` javascript
$('form').ajaxForm({
    error: function(xhr, textStatus, errorThrown, form) {
    }
});
```

**Comment by kevindb** [comment]
`success` and `error` options are deprecated, due to jQuery's removal of Deferred methods from jQuery.ajax.
https://jquery.com/upgrade-guide/3.0/#breaking-change-special-case-deferred-methods-removed-from-jquery-ajax
