### ISSUE TITLE
AjaxSubmit is not a function on DOM reload

### ISSUE THREAD

**Issue by arvinsim** [jquery-form/form#423]
I have this code below.

```
$('body').on('submit', '.some-form', function (event) {
    $(this).ajaxSubmit({
        dataType: 'json',
        success: function (data, statusText, xhr, form) {
            var url = 'some/url';

            // Reload the form markup/DOM using the response
            $.ajax({
                dataType: 'html',
                type: 'get',
                url: url
            }).done(function (html) {
                // get markup from url and replace the form markup ...    
            });
        },
        error: function () {
            alert('error');
        }
    });

    return false; 
});
```

Essentially what I am doing here is
1. submit and process the form
2. get the results
3. if success, get new form markup from a page then replace the current form markup.
   if failure, show error

Now, because I delegated the submit event to the body, there shouldn't be a problem with
handling the submit on the newly loaded form markup. 

The function handler works fine until I see this error

```
TypeError: $(...).ajaxSubmit is not a function

error: function () {
```

Any idea why this happened? It implies that ajaxSubmit does not exist but I did not reload
the page.

**Comment by kevindb** [comment]
Are you still experiencing this issue?
