### ISSUE TITLE
missing tag for "3.51.0"

### ISSUE THREAD

**Issue by thet** [jquery-form/form#424]
the git tag is missing for "3.51.0". thus, fixing bower to use this version is not possible.

**Comment by doits** [comment]
same for me, bower is pulling 3.46.0 and not even mentioning something bigger

**Comment by smmoosavi** [comment]
+1

**Comment by noelblaschke** [comment]
+1

**Comment by doits** [comment]
quick note how to get the latest version, specify it like this in bower.json:

```
"jquery-form": "malsup/form#master"
```

**Comment by malsup** [comment]
3.51 tag added.
