### ISSUE TITLE
form.ajaxSubmit() posts to a new window instead of submitting asynchronously (IE 9)

### ISSUE THREAD

**Issue by Medjeti** [jquery-form/form#428]
Hiya,

I have a form that I'm trying to get working on IE 9. Initially I had some problems with the file upload triggering the "SCRIPT5: Access denied" but I've put that on hold by removing everything related to file upload.

However I am now facing an issue where, upon calling form.ajaxSubmit(), the browser submits the form to a new tab/window instead of submitting "under the hood" as other browsers do.

Has anybody else experienced this? Can anybody give a hint as to what might be causing it?

My form is a bit complex, so it's difficult for me to offer a simple example, but I'll try give it a go if anybody is interested.

Thanks in advance for any pointers!

**Comment by bovercash** [comment]
If you submit a form to an iframe that does not have a name ie appears to use '_blank' by default.  The plugin does set the name, but apparently setting a name attribute via javascript is buggy in older versions of ie and may not work.  I fixed this by using my own iframe and specifying the name explicitly.
