### ISSUE TITLE
File upload with no files selected

### ISSUE THREAD

**Issue by duku602** [jquery-form/form#429]
Hi and thank you for this plugin, it made the work a lot more easier.

Unfortunately I've found a problem (at least for me). I want to know how many input [files] were submited, EVEN IF no file was selected in order to use count in php (for [multiple] file upload & replace)
If I submit the form by regular action="post" I get the correct count of fields sent (with or/and without files selected).

The problem is that the plugin is not allowing me to send empty values for file inputs. 

PLEASE help!

Thank you

I'm using the latest version: 3.51.0-2014.06.20 and jquery/1.11.1/jquery.min.js

**Comment by kevindb** [comment]
Are you still experiencing this issue?
