### ISSUE TITLE
Disabled inputs w/ iframe option

### ISSUE THREAD

**Issue by mattejames** [jquery-form/form#430]
I've run into an issue that I haven't seen anyone else talk about.  My situation is thus: I want to disable all inputs and buttons on a form during submission (to prevent duplicate submission).  This works just fine using beforeSubmit as long as the iframe option is not set to true.  Looking at the code, it appears as though when sending through the iframe, all the inputs that were serialized are re-enabled at the time of submission.  With this in mind, I updated my code to disable the elements by binding to the custom 'form-submit-notify' event instead.  This disables the inputs, but the data from them is not sent over through POST.

Is there a workaround that anyone can recommend so that I can disable these elements during submission outside of a possibly race-condition-bug-inducing setTimeout() call?

Thanks!

**Comment by kevindb** [comment]
Are you still experiencing this issue?
