### ISSUE TITLE
Authorization header is lost in IE9

### ISSUE THREAD

**Issue by wokier** [jquery-form/form#431]
I have tried 3 different ways to pass an Authorization header for a file upload.
1/
$.ajaxSetup({
  headers: { "Authorization": authorization }
});
2/
    $('form#myForm').ajaxSubmit({
        headers: { 'Authorization': authorization },
        url: '...',
        type: 'POST',
    success: function (data)
    {
        //...
    },
        cache: false,
        processData: false
    });
3/
   $('form#myForm').ajaxSubmit({
        url: '...',
        type: 'POST',
        beforeSerialize: function ($form, options) {
            options.headers = { 'Authorization': authorization };
        },
    success: function (data)
    {
        //...
    },
        cache: false,
        processData: false
    });

The 1/ never worked
The 2/ and 3/ work in Firefox, but not in Internet Explorer IE9
I am wondering if the iframe fallback causes the header to be lost.
I have also notified that the Content-Type of the file inside the request body is 'application/json' for Firefox 'application/octet-stream' for IE9 but i am not shure that it matters.

Firefox Headers
Accept  _/_
Accept-Encoding gzip, deflate
Accept-Language en-us,en;q=0.8,fr;q=0.6,fr-fr;q=0.4,ar-sa;q=0.2
Authorization   ...
Cache-Control   no-cache
Connection  keep-alive
Content-Length  622
Content-Type    multipart/form-data; boundary=---------------------------15553126411432
Cookie  JSESSIONID=BE13ADFE1AD63F028C0C99DC7C7CB075
Host    ...
Pragma  no-cache
Referer ...
User-Agent  Mozilla/5.0 (Windows NT 6.1; WOW64; rv:26.0) Gecko/20100101 Firefox/26.0
X-Requested-With    XMLHttpRequest

IE9 Headers
Request POST /.../ HTTP/1.1
Accept  text/html, application/xhtml+xml, _/_
Referer ...
Accept-Language fr-FR
User-Agent  Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Trident/5.0)
Content-Type    multipart/form-data; boundary=---------------------------7dea776011c
Accept-Encoding gzip, deflate
Host    ...
Content-Length  614
Connection  Keep-Alive
Cache-Control   no-cache
Cookie  JSESSIONID=952B7A1D63ED7F22840166BA89318704; JSESSIONID=hq19zlykw3t0z3ipmd10n33a

**Comment by kirangsa** [comment]
HI wokier,

have  found any work around for this?

**Comment by wokier** [comment]
Hi

The solution i use is to pass the needed parameters by url query param instead of header, and go out of the iframe after the upload.

``` javascript
if(top !== self){
    parent.window.location.assign( '<%=request.getRequestURL()%>?<%=request.getQueryString()%>');
}
```

**Comment by kirangsa** [comment]
Thanks wokier :+1:
