### ISSUE TITLE
Can there be an option to ajax submit from a submit element?

### ISSUE THREAD

**Issue by thisjunewest** [jquery-form/form#432]
It would be really handy to be able to submit a form using a particular button with ajax submit i.e.
`$('button.something').ajaxSubmit();` and have it submit the associated value.

I don't want to make the whole form AJAX with `ajaxForm`, I just want to be able to submit in the same way.

**Comment by GevatterGaul** [comment]
Why not use this:

```
$('button.something').click(function (e) {
    $(this).parents('form').ajaxSubmit();
}
```

Perhaps you should fine-tune the selection of the form. Currently it selects all parent forms.

**Comment by thisjunewest** [comment]
This doesn't submit the form with the specific button. Submitting with a particular button sends the value of that button.

**Comment by GevatterGaul** [comment]
I'm sorry, I didn't get that in the first place.

**Comment by kevindb** [comment]
Are you still experiencing this issue?
