### ISSUE TITLE
IE9 fails when uploading a file using ajaxSubmit

### ISSUE THREAD

**Issue by mynameisstephen** [jquery-form/form#435]
IE9 errors out in the `jQuery.val()` function with the error:
Unable to get property 'toLowerCase' of undefined or null reference

This is being caused by passing in this which is referencing the `Window` object in the following line.

`var fileInputs = $('input[type=file]:enabled', this).filter(function() { return $(this).val() !== ''; });`

**Comment by kevindb** [comment]
Are you still experiencing this issue?
