### ISSUE TITLE
File Upload and XML broken with Opera

### ISSUE THREAD

**Issue by chy-causer** [jquery-form/form#44]
Hi Malsup,

Great plugin. I was wondering if you've noticed that Opera does not handle xml return responses like the other browsers? Your examples page is (ironically) a good example:

http://jquery.malsup.com/form/#file-upload

I'm looking through the source now and unfortunately it's out of my depth but if I do find something I will post it here.

Cheers

Chris

**Comment by yourchoice** [comment]
<p>Hi,</p>

<p>Just replace this line:</p>

<p>- var $io = $('&lt;iframe id=&quot;' + id + '&quot; name=&quot;' + id + '&quot; src=&quot;'+ s.iframeSrc +'&quot; onload=&quot;window[\'_\'+this.id]()&quot; /&gt;');</p>

with

<p>+ var $io = $('&lt;iframe id=&quot;' + id + '&quot; name=&quot;' + id + '&quot; src=&quot;'+ s.iframeSrc +'&quot; onload=&quot;if(window.opera){tmp=\'_\'+this.id; setTimeout(\'window[tmp]()\', 700);} else {window[\'_\'+this.id]();}&quot; /&gt;');</p>

**Comment by chy-causer** [comment]
Thanks YourChoice. I'd actually forked the project and fixed it in a manner similar to you and asked for a pull from Malsup, but with no reply :(

The fork is here 
https://github.com/ChrisCauser/form
