### ISSUE TITLE
IE8 - Submit file upload will result in blank file

### ISSUE THREAD

**Issue by lance-shi** [jquery-form/form#443]
I submitted a form containing a file using .ajaxSubmit(); It works well for Chrome but not IE8 (haven't tried other IE versions). It seems to me that the issue might be because of serializing. I uploaded the file into Amazon S3 server, the key is generated and the file is already there but empty. 

I also tried with setting the option traditional to be true. However it still doesn't work for me. Any thoughts or walkaround on this?

**Comment by kevindb** [comment]
Are you still experiencing this issue?
