### ISSUE TITLE
IE9/8/7 fail when uploading a file using ajaxSubmit

### ISSUE THREAD

**Issue by ansonchen8956** [jquery-form/form#444]
in 593 line, “var submitFn =document.createElement('form').submit; submitFn.apply(form); ”
ie 9/8/7 failed in that line,then the browser stop running  when uploading a file using ajaxSubmit.
i find that the submitFn is an object,not a function in ie 9/8/7. so how can i do make the submitFn be a method.

**Comment by CheapSk8** [comment]
The code you are referring to attempts to create a form element and return the submit function to the var "submitFn" (line ~592). The line below with "submitFn.apply" (~593) attempts to execute the submit function using the already existing "form" var defined earlier in the script (~351). The way it is written is correct. 

The issue you are encountering may be related to: https://github.com/malsup/form/issues/286

Make sure you have the latest version of the script and then check the error + solutions referenced in that thread.
