### ISSUE TITLE
Uploading a file via "ondrop" event

### ISSUE THREAD

**Issue by osvaldasvalutis** [jquery-form/form#452]
Hi,

Is there any way to upload a file using ajaxForm/ajaxSubmit, without having presenting the actual `input[type=file]` element in HTML code? I was going to enable file upload via "ondrop" event, but...

I tried passing the file data via "data" option. It did not work, looks like "data" option does not accept this format of data:

```
var data = '';
area.ondrop = function(e){ data = { 'extra-file': e.dataTransfer.files[0] }; };
...
form.ajaxSubmit(
{
     data: data
     ...
});
```

Thanks.

**Comment by kevindb** [comment]
Are you still experiencing this issue?
