### ISSUE TITLE
error callback not always called on Safari

### ISSUE THREAD

**Issue by kyouko-taiga** [jquery-form/form#453]
The error callback sometimes doesn't get called at the moment the server answered a 4xx. Instead, it seems to get called just before the page refreshes.

I can reproduce this problem on my system (OS X 10.10, Safari 8.0.2) with the following code, my server responding 413 to any request.

``` html
<form action="media" method="POST">
  <input name="file" type="file" accept="image/*;capture=camera">
</form>
```

``` javascript
$('input[name=file]').change(function(e) {
  $('form').ajaxSubmit({
    success: function() { console.log('success') },
    error: function() { console.log('error') },
  });
});
```

The same example works fine with google Chrome 39.0, same OS version.

**Comment by kevindb** [comment]
Are you still experiencing this issue?
