### ISSUE TITLE
IE 10 Access Denied Error

### ISSUE THREAD

**Issue by slinky66** [jquery-form/form#459]
@malsup 
I am having an issue with the plugin, when used in IE 10. I am getting back a JS error "Access Denied".
The issue is related to the file upload section of the form, I believe, specifically a security "feature" of IE.

Here is how I have the form fields set up, per the suggestions I read, related to circumventing IE's security filters as seen with this plugin. I am using a label element for the file browse button and I am positioning the file upload field off-screen as well.

```
            <label>Attach File:</label>
            <input class="js-file-text" type="text" id="fileUploadFileName" name="fileUploadFileName">
            <input type="file" class="js-file-field" id="attachment" name="attachment" style="left: -9999px; position: absolute;"/>
            <label class="btn blue js-file-btn">Browse</label> 
             <input type="submit" id="btnSend" class="btn" value="Send" />
```

![form-plugin-access-denied](https://cloud.githubusercontent.com/assets/1904465/6509137/4e563326-c32b-11e4-9473-68c34ad5e155.png)

**Comment by slinky66** [comment]
@malsup 
Apparently, the issue exists on the plugin demo page, too

![form-plugin-access-denied-2](https://cloud.githubusercontent.com/assets/1904465/6509445/666e075c-c32d-11e4-8299-342c297c46b8.png)

**Comment by kressly** [comment]
Has someone found a fix for this ?

**Comment by kevindb** [comment]
Are you still experiencing this issue?
