### ISSUE TITLE
iframe ajaxSubmit doesn't accept PUT method

### ISSUE THREAD

**Issue by sandrew** [jquery-form/form#46]
in FireFox 3.6 (I didn't test other browsers) code like
.ajaxSubmit({ 'type' : 'PUT', 'dataType': 'json', 'iframe': true); or
.ajaxSubmit({ 'method' : 'PUT', 'dataType': 'json', 'iframe': true); (I tried many variants)
with form method attr set to 'PUT' makes POST request instead of needed PUT.

**Comment by malsup** [comment]
When the iframe:true option is used, 'PUT' is not a valid method type.  iframe:true causes the plugin to simulate an ajax request using a native form submit.  And unfortunately PUT is not a valid method attribute on an HTML form.
