### ISSUE TITLE
How to headers

### ISSUE THREAD

**Issue by pokal4u** [jquery-form/form#465]
HI,

I am using below code:

var options = { 
        target:   '#output',   // target element(s) to be updated with server response 
        beforeSubmit:  beforeSubmit,  // pre-submit callback 
        uploadProgress: OnProgress,
        success:       afterSuccess,  // post-submit callback 
        resetForm: true,       // reset the form after successful submit  
    }; 
    $('#MyUploadForm').ajaxSubmit(options); 

In options variable how to set authentication headers?

ex:
headers:{"Authorization": "Basic " + btoa("username" :" pasword")}

Thanks
Srinivas

**Comment by kirangsa** [comment]
hi pokal4u,

Have u find any wor around for this ? 

Thanks,
Kiran Gopal

**Comment by kevindb** [comment]
Are you still experiencing this issue?

**Comment by pmcfernandes** [comment]
Hi

I fixed this issue using ajaxSetup from jquery

`$.ajaxSetup({
    headers: { 'x-my-custom-header': 'some value' }
});`
