### ISSUE TITLE
Uncaught TypeError: $(...).ajaxForm is not a function

### ISSUE THREAD

**Issue by DevangMstryls** [jquery-form/form#467]
First time after page load it works properly, But after that for second use(or for uploading another file), it gives the following error in console:
Uncaught TypeError: $(...).ajaxForm is not a function 
and doesn't submit the image to the php file.

Thanks in advance!

**Comment by malsup** [comment]
Sounds like you're loading a 2nd version of jQuery with the response from submitting the form and your plugins are being overwritten.

**Comment by DevangMstryls** [comment]
My image processing php file(**_parse_images.php_**) includes a `require_once 'init.php'` statement. The **_init.php_** file contains all the general functions and CDN link for loading jQuery and has some comments in it.
So, Whenever I upload an image for the first time, it inserts into the target `div` whatever(I am echoing this: `<img id="coverpic" class="coverpic" src="'.$image_path.'">`) is echoed in the image processing file(**_parse_images.php_**) _along_ with that CDN link and those comments.
After that for the subsequent uploads it gives the previously mentioned error. 
I don't want it to insert those comments and the CDN link again.

#### 1. Why is that happening and how can I prevent it ?

This is how I've used the plugin:

``` javascript
function jsF_UploadImage(jsP_type, jsP_CntntKind, jsP_token, jsP_target, jsP_form) 
{
     $(jsP_form).ajaxForm({
        target: jsP_target,
        url: 'parse_images.php',
        data: {
            type: jsP_type,
            kind: jsP_CntntKind,
            token: jsP_token
        },
    }).submit();
}

$('#image-input').on('change', function() {
   jsV_token = Date.now();
   jsF_UploadImage('image', 'profile', jsV_token, '#trgt-image-div', "#image-form");
});
```

#### 2. Is something wrong here ?

**Comment by Whiax** [comment]
In case the answer didn't fix it, you need to get the form with an id $('#myform'), not with a name $('form[name="myform"]')[0] which doesn't return the same jquery object
