### ISSUE TITLE
Hi, Opera Bug

### ISSUE THREAD

**Issue by Andre-yar** [jquery-form/form#47]
Opera 10.63, Form Plugin 2.52, jquery 1.4.4

Uncaught exception: TypeError: 'window['_'+this.id]' is not a function
Error thrown at line 1, column 0 in <anonymous function>(event):
    window['_'+this.id]()

.. and don't upload files, response is false

**Comment by yourchoice** [comment]
<p>Hi,</p>

<p>Just replace this line:</p>

<p>- var $io = $('&lt;iframe id=&quot;' + id + '&quot; name=&quot;' + id + '&quot; src=&quot;'+ s.iframeSrc +'&quot; onload=&quot;window[\'_\'+this.id]()&quot; /&gt;');</p>

with

<p>+ var $io = $('&lt;iframe id=&quot;' + id + '&quot; name=&quot;' + id + '&quot; src=&quot;'+ s.iframeSrc +'&quot; onload=&quot;if(window.opera){tmp=\'_\'+this.id; setTimeout(\'window[tmp]()\', 800);} else {window[\'_\'+this.id]();}&quot; /&gt;');</p>

<br />
