### ISSUE TITLE
Error callback $form argument is undefined

### ISSUE THREAD

**Issue by fabiocaccamo** [jquery-form/form#470]
Tested receiving a 403 error callback, using jquery-1.11.2, 
(in beforeSubmit callback $form argument is correct).

**Comment by kevindb** [comment]
Are you still experiencing this issue?

**Comment by fabiocaccamo** [comment]
I have not tested it anymore, but if you have not fixed this you should not close the issue.

**Comment by kevindb** [comment]
Would you please create an example of the error on [CodePen](https://codepen.io/) or [JSFiddle](https://jsfiddle.net/)?

**Comment by fabiocaccamo** [comment]
At the moment I have not time to do it, but based on the error description it should be really easy to test/debug.

**Comment by kevindb** [comment]
Without a reproducible example, there isn't a lot I can do, so I’m going to close the issue for now.
When you have time to mock up a demonstration of the problem in CodePen, please post a link here. We can reopen the issue then.
