### ISSUE TITLE
This plugin is supported?

### ISSUE THREAD

**Issue by nepster-web** [jquery-form/form#472]
This plugin is supported?

**Comment by silverqx** [comment]
i want to know too, thank you

**Comment by nepster-web** [comment]
It turns out that the answer is indeed negative =(

**Comment by kevindb** [comment]
TLDR: Yes jQuery Form plugin is being maintained.

The original owner transferred ownership of the repo to the jquery-form Github organization today so the project won't be dependent on one maintainer anymore. I'm working on accepting pull requests and getting the project back into shape.
