### ISSUE TITLE
If the form have many submit buttons, exists the possibility to get in "beforeSubmit" callback the pressed submit button?

### ISSUE THREAD

**Issue by yourchoice** [jquery-form/form#474]
If the form have many submit buttons, exists the possibility to get in "beforeSubmit" callback the pressed submit button?

For example I have a form where I use top and bottom submit buttons. In "beforeSubmit"  callback I want to add an ajax loader and hide the button. For that I need to know the pressed button.

Thank's

**Comment by kevindb** [comment]
Are you still experiencing this issue?
