### ISSUE TITLE
iframe cross domain ajax post return error 

### ISSUE THREAD

**Issue by luowenxing** [jquery-form/form#477]
I meet with the issue when I post to other domain containing file using ajaxForm.The request is send successfully but the return data is the current document html within <body> tag.I go through the source code and find IE9- use iframe to emulate ajax post.As a result of cross domain,it cannot get the <body> content of iframe of other domain,so it return the current document html of <body> tag.I solve this problem in server side using html5 postMessage.Is there any way to solve the iframe cross domain ajax post issue in client side,just in the plungin itself?

**Comment by kevindb** [comment]
Are you still experiencing this issue?
