### ISSUE TITLE
in ie8,9 submit working, but after success function process not working

### ISSUE THREAD

**Issue by minkyeong** [jquery-form/form#478]
My script  is like this. :
if($("input[name=autosave]").val() == "Y") {
      $("#resumeForm").ajaxSubmit({
        type : "post",
        encType : "multipart/form-data",
        cache : false,
        target : "_self",
        url : "formAjax",
//         dataType : "json",
        async : false,
        success : processJson
      });

  } else {
    return false;
  }.

function processJson(data) {
  $.each(data, function(key, value){
    alert('2');
    if(key == 'resumeid') {
      alert('a');
      alert(value);
      $("input[name=resumeid]").val(value);
    }
    if(key == 'schoolid') {
      alert('b');
      alert(value);
      var schoolid = $.trim(value).split('_');
      for (var a = 0; a < schoolid.length; a++) {
        $("input[name=schoolid]:eq("+a+")").val(schoolid[a]);
        $("input[name=schoolmode]:eq("+a+")").val("update");
      }
    }  
    $("input[name=mode]").val("modify");
  });
}

it works well in FF, Chrome, ie10. ( in ie10, i can't see value change in function processJson, anyway it works well.)
But, I need it to work in ie8, ie9, too.
I don't use file upload.
In ie8 and ie9, to submit is working in server and I can see the result in eclipse console, 
but the value change in function processJson is not happen, even no alert, only options to download json file.
I don't want to see the msg to download file anymore and I wanna make it work well in ie8.
The plugin that I'm using is jquery form plugin 3.39.0-2013.07.31.
I tried some form options in comments of plugin js file, and json, ajaxsubmit, ajaxform examples in github page such as : 

$('#myForm').on('submit', function(e) {
            e.preventDefault(); // <-- important
            $(this).ajaxSubmit({
                target: '#output'
            });
        });

Or
$(this).ajaxForm({
                target: '#output'
            });

$('#myForm').submit({
            e.preventDefault(); // <-- important
            $.ajax({
                target: '#output'
            });
        });

Anything above does not work properly.
Please help me. lol

**Comment by kevindb** [comment]
Are you still experiencing this issue?
