### ISSUE TITLE
Add minified version of jquery.form

### ISSUE THREAD

**Issue by iquito** [jquery-form/form#479]
A minified version of jquery.form should be included (as jquery.form.min.js), so when including this package in composer the minified version is available. Currently only the regular source file is included, which is not suitable for production use.

**Comment by x5engine** [comment]
https://malsup.github.io/min/jquery.form.min.js

**Comment by designosis** [comment]
The NPM package has no minified version either.
And is still at v3.50.0.

**Comment by kevindb** [comment]
Resolved by 50e68c3
