### ISSUE TITLE
IE8 issue with ajaxForm type GET sending as POST

### ISSUE THREAD

**Issue by edallen** [jquery-form/form#48]
We are using ajaxForm 1.49 with jQuery 1.3.2 and seeing only in IE8 that it is ignoring the GET declared in the form tag and submitting as a POST. Also tried setting type: 'GET'  in the options hash without success. It correctly does the GET in Firefox and Chrome.

**Comment by malsup** [comment]
Can you post a link to a simplified test page?

**Comment by edallen** [comment]
I'll try to get one together tomorrow. Worked around it today with an additional Rails route for IE.

**Comment by nebulous** [comment]
IE has a nasty habit of modifying the http request method. See issue #58 for details and a fix for some of that. What you're describing sounds slightly different however. Usually IE converts things to "get" from other methods, not vice-versa. Is the form's enctype set to multipart by any chance?
