### ISSUE TITLE
Behavior after jQuery.noConflict()

### ISSUE THREAD

**Issue by vishnuprabhu-g-3086** [jquery-form/form#481]
In my development i have to do jQuery.noConflict(). But after that jquery form stops working. How to fix it?

**Comment by kevindb** [comment]
Are you still experiencing this issue?

**Comment by vishnuprabhu-g-3086** [comment]
Yes. I have to get $ and have to pass it

**Comment by kevindb** [comment]
Would you please create an example of the error on [CodePen](https://codepen.io/) or [JSFiddle](https://jsfiddle.net/)?

**Comment by kevindb** [comment]
I'm closing this issue until an example can be created.
https://github.com/jquery-form/form/blob/master/CONTRIBUTING.md#reporting-a-bug
