### ISSUE TITLE
Exception thrown in Internet Explorer 11 when resolving form elements outside the form

### ISSUE THREAD

**Issue by chrisjsmith** [jquery-form/form#483]
Tripped over this one today. Not bad - first problem in 6 years - thanks for the good times :)

The code that resolves the form elements outside the stack is causing an error inside jQuery. This is reproducible on Internet Explorer 11.0.21 on Windows 8.1 x64, jQuery 2.1.4. I don't have a test rig for it unfortunately.

Stack:
![stack](https://cloud.githubusercontent.com/assets/8579749/9226575/2a8ef43c-4107-11e5-8f90-4eb28f260eed.png)

Final exception:
![location](https://cloud.githubusercontent.com/assets/8579749/9226625/6d205dae-4107-11e5-8b74-f97587595c64.png)

Calling code:

https://github.com/malsup/form/blob/master/jquery.form.js#L959

If I blow away lines 957-963 it stops the error occurring. Probably something inside jQuery but it is manifesting itself through jquery.form only. Any further info needed, please let me know.

formId passed in is "form_1_2_3"

**Comment by kevindb** [comment]
Are you still experiencing this issue?
