### ISSUE TITLE
Please update license context.

### ISSUE THREAD

**Issue by hshiraya** [jquery-form/form#484]
We want to use your jquery form plugin in a commercial product we distribute, but the license is not clear enough.

In your README and javascript code, the license is described as "Dual licensed under the MIT and GPL licenses".
I think that "or" clause is more suitable than "and" clause in this case. This "and" context might be recognized as that it applies both of two licenses.
In jquery v1.5, the license is "Dual licensed under the MIT or GPL Version 2 licenses". This sentence uses "or" instead of "and." I think that it's better to follow up this version license.

My company is a little more careful with GPL licensed projects and our legal team wants some clarification on what this dual licenses means.

**Comment by malsup** [comment]
https://github.com/malsup/form/blob/master/README.md#copyright-and-license
