### ISSUE TITLE
Add file upload function

### ISSUE THREAD

**Issue by chidalgom** [jquery-form/form#485]
Hi there!!

Well Im using your mail form and it works perfect for what I need, but so far I only used to send plain mail form... Now I need to add the upload part wich is so confusing to me... was reading and searching on google but nothing is so clear (to me), and my skills are limited by now.

Is there a way you can help me with that please?

If you can I'll show you the files Im using, but bassically is the html file (html form, ajax function and jquery for displaying succes or error), and the php file wich extract the data from the form and send the email.

for example the form is used on this site Im working on:
www.aricanativa.cl/home
if you go down to "contact us" will see the form Im using please chek it if you can.

Thanks and so sorry for bother with this, but Im cant get this to work right.

**Comment by hayageek** [comment]
Check this https://github.com/hayageek/jquery-upload-file
