### ISSUE TITLE
Add 'method' option

### ISSUE THREAD

**Issue by tony-ist** [jquery-form/form#486]
In `ajaxSubmit` there is line:

```
method = options.type || this.attr2('method');
```

And what if `options` has only `method` and no `type` specified? According to jquery reference, `method` is alias for `type`. Maybe add both?

**Comment by kevindb** [comment]
https://api.jquery.com/jQuery.ajax/#jQuery-ajax-settings
jQuery 1.9.0 prefers setting `method` (values: "GET", "POST", "PUT")
Prior to 1.9.0, _must_ use legacy setting `type` (same values)
