### ISSUE TITLE
No tags in git repo? How to get older versions

### ISSUE THREAD

**Issue by rfay** [jquery-form/form#49]
Hi - I needed to grab the unminified 1.48, but found no way to do it. It seems there are no tags in the repo, and no way to get old versions?

Thanks,
-Randy

**Comment by malsup** [comment]
Every commit is a new version so just look through the history.

https://github.com/malsup/form/commits/master/

**Comment by malsup** [comment]
And I assume 1.48 was a typo.

**Comment by rfay** [comment]
Thanks - it would be better to tag, as the technique you propose requires checking out the commit and looking at the version number in the code. Having a way to map versions using tags would be really nice.

Thanks for the quick response and for your care for this excellent plugin.

**Comment by rfay** [comment]
1.48 was a typo. I wanted 2.48.
