### ISSUE TITLE
Options defaults

### ISSUE THREAD

**Issue by esavichev** [jquery-form/form#491]
Would be nice to have possibility to init default values for submission options. 

Example: I use AJAX submission and each response sets cookies with actual CSRF protection tokens. I want to update these values before form submission. I could define **beforeSerialize** handler related to all project instead of duplicating it everywhere, because this logic is not related to only one form in project, it is common sequrity policy for the whole resource. The same thing about **error** callback as it is often being handled typically for the whole project.

PS: Sorry for my bad english. Hope the main idea is clear.

**Comment by kevindb** [comment]
I am closing this issue due to a lack of activity. If you still need help, please comment and we can reopen.
