### ISSUE TITLE
Mail form prevent sending of mail to new top domain. 

### ISSUE THREAD

**Issue by kandresen** [jquery-form/form#494]
The form mark email addresses from new top domains such as dot.wedding as invalid. 

Due to the changing nature of top domains, I believe we need to test if a domain actually exist according to dns rather than a passive regex. This way we would reject expired/non-registered domains as well, while not blocking mail addresses of to be new top domains.

**Comment by kandresen** [comment]
"host <domain>" would return NXDOMAIN if domain is not valid. It might be possible to call such a function from php.

**Comment by kevindb** [comment]
Are you sure this issue is for the jQuery Form plugin?
