### ISSUE TITLE
Exclamation Character Used in Docblock

### ISSUE THREAD

**Issue by alexfinnarn** [jquery-form/form#499]
While looking at a parsing/encoding/something error in my code, I noticed that the docblock in this file contains an exclamation point instead of another asterisk:

https://github.com/malsup/form/blob/master/jquery.form.js#L1

When I search for guidelines for JS docblocks they seem to say it should go like:

```
/**
 *
 */
```

I don't think this is a big issue, but I thought I'd mention it for consistency's sake.

**Comment by kevindb** [comment]
The `/*!` tells the JavaScript minifier to not remove the comment. This is important for license information that has to stay in the file. See [Skip License/Credit Comments when minifying JavaScript using YUIcompressor](http://stackoverflow.com/questions/6614532/skip-license-credit-comments-when-minifying-javascript-using-yuicompressor)
http://stackoverflow.com/a/21832804/1480959
