### ISSUE TITLE
Minify

### ISSUE THREAD

**Issue by lakario** [jquery-form/form#5]
Is there a minified version available? I tried to do the minification myself using a website, but it created errors pertaining to the call to window.console.log in the log() function. Would be really nice to see a minified/packed version.

**Comment by malsup** [comment]
Try this:  http://refresh-sf.com/yui/

**Comment by ericduran** [comment]
Sorry for re-opening this. But any change to actually provide one in the repo?

I'll be doing a pull request soon for this.
