### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by chalist** [jquery-form/form#502]
How I can use jquery form in bower?
I register this repo in bower and I can't find minified file.
tnx

**Comment by kevindb** [comment]
Probably resolved by 14fa0c8 and 0dc9b4e
The new release has just been posted. I'll check back in a day or two to see if the package managers have picked up on the new version.

**Comment by pavelaverkiev** [comment]
I got version 4.0.1 using bower and there is a trouble with AMD loading (requirejs). I have seen that this trouble was fixed (in github repo), but I cannot manually replace the module. Please update bower repository!

**Comment by kevindb** [comment]
What error are you seeing loading using AMD (RequireJS)?

**Comment by pavelaverkiev** [comment]
I see error "$ is not defined".

Here is the code I got today using bower ("jquery-form": "latest"):
`/*!
 * jQuery Form Plugin
 * version: 4.0.1
 * Requires jQuery v1.7 or later
 * Copyright 2017 Kevin Morris
 * Copyright 2006 M. Alsup
 * Project repository: https://github.com/jquery-form/form
 * Dual licensed under the MIT and LGPLv3 licenses.
 * https://github.com/jquery-form/form#license
 */
/*global ActiveXObject */

// AMD support
(function (factory) {
	"use strict";
	if (typeof define === 'function' && define.amd) {
		// using AMD; register as anon module
		define(['jquery'], factory);
	} if (typeof module !== 'undefined') {
		factory(require('jquery'));
	} else {
		// no AMD; invoke directly
		factory( (typeof(jQuery) != 'undefined') ? jQuery : window.Zepto );
	}
}`

When I change Line "} if (typeof module !== 'undefined') {" to "} **else** if (typeof module !== 'undefined') {" everything works fine :)

I see changed version in github project, but in bower repo code is different and I can not get last changes

**Comment by kevindb** [comment]
Bower has been updated with [v4.1.0](https://github.com/jquery-form/form/releases/tag/v4.1.0)

**Comment by pavelaverkiev** [comment]
Thanks a lot!
