### ISSUE TITLE
clearForm() does not clear hidden inputs

### ISSUE THREAD

**Issue by kevinrood** [jquery-form/form#51]

**Comment by kevinrood** [comment]
I can see that clearing _all_ hidden inputs would cause an issue with Rails' auto generated "authenticity_token" input.  Not sure what to recommend.

**Comment by malsup** [comment]
By design.

**Comment by mattpenner** [comment]
Would be nice if there was some sort of option on the clearForm function that allowed you to clear hidden fields or not, or at least taking some sort of selector.  For those of us that don't use Rails the clearForm function is pretty much useless if the form contains any hidden fields.

**Comment by malsup** [comment]
Added an option to include hidden fields.
