### ISSUE TITLE
Easy post and PreventDefault

### ISSUE THREAD

**Issue by ghost** [jquery-form/form#522]
Thank you for a good library!

It would be really wishful to "embedd" submit functionality in the library so one could do something like:

```
$("#form1").ajaxSubmit({
      ....
});
```

And also prevent default as standard behavior (option if wanted).

**Comment by kevindb** [comment]
There is already an ajaxSubmit method. Please see the API documentation
https://jquery-form.github.io/form/api/#ajaxsubmit
