### ISSUE TITLE
Extending

### ISSUE THREAD

**Issue by Iamscalla** [jquery-form/form#524]
Please how do I extend this jquery plugin ??

**Comment by kevindb** [comment]
What, specifically, are you trying to accomplish?

**Comment by Iamscalla** [comment]
Wanna add custom response especially on failed request

**Comment by kevindb** [comment]
You'll want to review the [Options](https://jquery-form.github.io/form/options/). In particular, the [Error](https://jquery-form.github.io/form/options/#error) option.
