### ISSUE TITLE
feature for Deferred

### ISSUE THREAD

**Issue by luwfls** [jquery-form/form#527]
- I think ajaxSubmit shoud be a deferred Object 。 so that we can use `$.when()`
- usecase  as below
<pre>
    var deferreds = [];
    // there are more than one form 
    $("form").each(function () {
        deferreds.push($(this).ajaxSubmit({
            success: function (data) {
                console.log(data);
                $(this).find("input[name$='id']").val(data.id);
                $(this).find("input[name$='materiaName']").val(data.materiaName);
                $(this).find("#preview-btn").unbind("click");
                $(this).find("#preview-btn").attr("onclick", "openImgeMadal(" + data.url + ")");
            }
        }));
    });
    $.when.apply($, deferreds).done(function () {
        console.log("all ajax down");
    });
</pre>

**Comment by kevindb** [comment]
I am closing this issue due to a lack of activity. If you still need help, please comment and we can reopen.
