### ISSUE TITLE
File Upload broken in IE

### ISSUE THREAD

**Issue by eirikurn** [jquery-form/form#53]
There seems to be a recent regression with the iframe response handling inIE. 

In commit a53241d4c8c087f37f7e this code was changed to use textContent instead of innerHTML. This property doesn't exist in IE as far as I can tell, and thus the success handler receives the data as null.

**Comment by codeincontext** [comment]
See this pull request... https://github.com/malsup/form/pull/60

**Comment by eirikurn** [comment]
Yeah, that looks like it would fix this issue. 

Although, this library is useful enough to demand some decent test coverage. Since it's using internals of both jquery and browsers, both of which update quite often, it makes regressions inevitable. We just need a better way to detect them. Maybe I'll get some spare time to start work on that.
