### ISSUE TITLE
License Confusion

### ISSUE THREAD

**Issue by lc-vs** [jquery-form/form#530]
I have been asked by our legal team to seek clarification on the dual license or remove the package from our project.  

I found a closed issue (https://github.com/jquery-form/form/issues/484) from 2015 which is similar .  The statement in the README uses "and" instead of "or" which has injected the potential legal confusion.  The issue was closed with a link to an update of the README in 2015 but the issue has perhaps been restored since then.

The Software Freedom Law Center has a section discussing dual licensing which may be of interest (http://www.softwarefreedom.org/resources/2007/gpl-non-gpl-collaboration.html).  JQuery switched to a single MIT license in 2012 (https://blog.jquery.com/2012/09/10/jquery-licensing-changes/).

If a clarification can be made to the README by changing the "and" to an "or" or a more explicit statement granting use only MIT use it would be very helpful.

**Comment by kevindb** [comment]
Fixed by 0762c5b. The `and` is now an `or`.
