### ISSUE TITLE
How do I terminate requests for uploading files?

### ISSUE THREAD

**Issue by freezyh** [jquery-form/form#534]
How do I terminate requests for uploading files? 

If the upload file is too large, how can I abort the request when it is uploaded?

**Comment by kevindb** [comment]
I'm afraid I don't know. I, personally, have never used the upload feature. Perhaps somebody from the community can answer.

**Comment by freezyh** [comment]
It does not support “abort” function.

**Comment by odahcam** [comment]
Take a look: https://stackoverflow.com/a/446626/4367683

You could use the `.abort()` xhr method inside `beforeUpload` or `uploadProgress` method.
