### ISSUE TITLE
The option or the method to resize image before uploading

### ISSUE THREAD

**Issue by supercreator** [jquery-form/form#543]
Is there the method or option to resize, rotate or crop the image before uploading? I found that the large image size will use much time to upload, sometime got norespoding. if the plugin can reduce image size in client side firstly then upload it, it’s faster. 

Please suggest the simple way how to resize image with this plugin or add the option for resize or rotate the image for this plugin. I use this plug in to upload file and data in form. It do well and it can report progress status.  It’s awesome.

Thank you Jquery-Form Team

**Comment by kevindb** [comment]
I'm glad that jQuery Form works well for how. However, it does not do any image manipulation. There are many other tools to do that, both in Javascript and server-side.
