### ISSUE TITLE
file type returning blank on windows machine

### ISSUE THREAD

**Issue by umeshnevase** [jquery-form/form#546]
Please review [Instructions for Reporting a Bug](https://github.com/jquery-form/form/blob/master/CONTRIBUTING.md#reporting-a-bug).

### Description: 
I'm using ajax upload in my form. It is working fine on my Linux and Macbook system. On windows system, when I select a CSV file and start the upload. It is not giving me blank file type, so I could not restrict file type to uploads. all the file parameters are returning coorectly, but file type is not getting. It is not working only for CSV file.

### Expected Behavior: 
File type should return text/csv or application/vnd.ms-excel

### Actual behavior: 
Getting blank file type. I'm checking filetype by jQuery( element)[0].files[0].type. it is returning blank for windows machine only.

### Versions:
**LoadJSON:**   
**jQuery:**   
**Browsers:**   
Windows any browser. Chrome and Edge

### Demonstration
Link to demonstration of issue in [JSFiddle](https://jsfiddle.net/) or [CodePen](https://codepen.io/):

**Comment by kevindb** [comment]
I'm closing this issue until an example can be created. If you still need help, please comment and we can reopen.
https://github.com/jquery-form/form/blob/master/CONTRIBUTING.md#reporting-a-bug
