### ISSUE TITLE
ajaxSubmit with empty form in IE 7/8

### ISSUE THREAD

**Issue by couillardcharles** [jquery-form/form#55]
Hello,

First thanks for this usefull plugin.

I've got a problem when i try to post empty form in IE 7 and 8, success callback is called but no post is done. (not tested in IE 6) 

My example: 

```
<form id="plop" action="myaction" method="POST">
    <button type="submit">Post!!!</button>
</form>

$("#plop button").click(function() {
    $("#plop").ajaxSubmit({
        success : function(data, textStatus, xhr) {
                alert("success");
        }
    });
    return false;
});
```

Thanks!
Charles

**Comment by shoting** [comment]
Hi,

When I upgrade from 2.45 to 2.81 , I got this error too.

In IE 6 7 8 , will get error  Object doesn't support this property or method 'toUpperCase', jquery.form.js, Line 119

try to Set type : 'post'  in ajaxSubmit option.

**Comment by kevindb** [comment]
Are you still experiencing this issue?
