### ISSUE TITLE
Multiple file problem when add more files or remove some of selected

### ISSUE THREAD

**Issue by stojankukrika** [jquery-form/form#550]
Hi,
Is anybody know how do I send form over ajaxForm when have multiple files in it. I have problem when have multiple select for files and then remove some and then again add some. when I fistable add files and send to server all files are send to server. But when remove some, again it send to server all files (with items that I delete). And when add some and again add some, in that case send only new files added without prev. added files.

Can anybody have idea what to do?

**Comment by kevindb** [comment]
Please review [Instructions for Reporting a Bug](https://github.com/jquery-form/form/blob/master/CONTRIBUTING.md#reporting-a-bug).

* Which version of the plugin are you using?
* Which version of the jQuery library are you using?
* What browsers (and versions) have you tested in?
* How can the error be reproduced?
* Please include a link to a [JSFiddle](https://jsfiddle.net/) or [CodePen](https://codepen.io/) example of the error.

**Comment by kevindb** [comment]
I'm closing this issue until an example can be created. If you still need help, please comment and we can reopen.
https://github.com/jquery-form/form/blob/master/CONTRIBUTING.md#reporting-a-bug
