### ISSUE TITLE
multiple select parameter to comma delimited

### ISSUE THREAD

**Issue by buste** [jquery-form/form#551]
### Actual behavior: same parameter like: name=John&name=Joshua&name=Jeric

**Comment by kevindb** [comment]
Please review [Instructions for Reporting a Bug](https://github.com/jquery-form/form/blob/master/CONTRIBUTING.md#reporting-a-bug).

* Which version of the plugin are you using?
* Which version of the jQuery library are you using?
* What browsers (and versions) have you tested in?
* How can the error be reproduced?
* Please include a link to a [JSFiddle](https://jsfiddle.net/) or [CodePen](https://codepen.io/) example of the error.

**Comment by kevindb** [comment]
I'm closing this issue until an example can be created. If you still need help, please comment and we can reopen.
https://github.com/jquery-form/form/blob/master/CONTRIBUTING.md#reporting-a-bug
