### ISSUE TITLE
Can I use a template engine with this library? How to this?

### ISSUE THREAD

**Issue by PedroUrday** [jquery-form/form#558]
### Question:

One of the options of "ajaxSubmit" method or "ajaxForm" method is "target" option. With this option I can specify an element to place the response. But, if the response format is JSON, how can I render a template (for example a Mustache template) on the target element?

### New feature:

If it is not posible, one posible feature to add can be an event that fires before the response is placed in the target element. This event would allow to render a template on the target element by modifing the response. The modified response can be the return value of the event handler.

### Why:

To program SPA applications more easily, without frameworks.

**Comment by kevindb** [comment]
I am closing this issue due to a lack of activity. If you still need help, please comment and we can reopen.
