### ISSUE TITLE
$.httpData and $.handleError removed from 1.5

### ISSUE THREAD

**Issue by helloandre** [jquery-form/form#56]
They have been rolled in to the ajax functionality with the ajax rewrite, therefore $.httpData and $.handleError no longer exist, and this plugin no longer works. temporary workaround is to manually include the functions into the plugin and call them.

**Comment by malsup** [comment]
v2.60 addresses these changes.  
https://github.com/malsup/form/commit/0657b81436cf4b516db0b5e37aa032a003d725b6
