### ISSUE TITLE
It seems not support button formaction attribute

### ISSUE THREAD

**Issue by GF-Huang** [jquery-form/form#564]
![image](https://user-images.githubusercontent.com/4510984/62167190-430c9180-b355-11e9-912d-7a106f056849.png)

**Comment by ffreeman39** [comment]
I am lost, the code is blurred. What seems to be the problem and what are you looking to accomplished.?

**Comment by kevindb** [comment]
I'm closing this issue until more information can be provided. If you still need help, please comment and we can reopen.
https://github.com/jquery-form/form/blob/master/CONTRIBUTING.md#reporting-a-bug
