### ISSUE TITLE
Form doesn't submit in Firefox 3.5.7 when in iframe

### ISSUE THREAD

**Issue by rl** [jquery-form/form#6]
This issue may exist in other versions of Firefox, but it specifically exists in 3.5.7. If the form being submitted is within an iframe, then the form never submits because the setTimeout callback is never called. I have no idea why, it just doesn't seem to work when setTimeout is called within an iframe.

Removing the setTimeout call which wraps the actual form submission resolves the issue, but this seems to be more of a temporary fix than a permanent one.

**Comment by malsup** [comment]
There will be a 'forceSync' option in the next version which till cause the setTimout logic to be bypassed.
