### ISSUE TITLE
Character encoding problem in IE with file upload

### ISSUE THREAD

**Issue by HertzaHaeon** [jquery-form/form#63]
There seems to be an encoding error in IE (6, 7 and 8 checked) when there is a file upload. Swedish characters are returned mangled, despite everything being set as utf-8. Ajax loading of content through the plugin works fine when there isn't a file upload involved.

I've checked and double-checked my site to eliminate my own errors, but they only turn up in IE 6-8 when Ajax form plugin is used. I'm using version 2.63.

**Comment by RadekHavelka** [comment]
I can confirm this, having this problem as well. While in FF, CHR and other browser the submit form works ok and data are submitted as UTF8, in IE for some reason are data submitted in original page encoding (my pages are CP WIN1250, but the data are trasmitted in UTF8) and the post is invalid. There are 5 file fields in my form, so it might be this issue. Im using the current version of script as of 10.6.2013 - v 3.35.0-2013.05.23.

**Comment by kevindb** [comment]
Are you still experiencing this issue?
