### ISSUE TITLE
issue with jquery 1.5.0

### ISSUE THREAD

**Issue by yellow1912** [jquery-form/form#64]
Not 100% sure, but I get this very strange issue with jquery 1.5.0 (1.4.4 runs fine):
An additional param is added to the url: &callback=jQuery1506837476517671327_1297080018038

This causes the "parsererror", very weird. I tried to change dataType to "text" instead of "json" just to try, and the error went away (but then the returned data was not parsed, of course)

**Comment by malsup** [comment]
Can you post a simple test page that shows the problem?

**Comment by bckspc** [comment]
I'm having the same issue. I'll try to provide an example but I don't have any server to publish the server side part of the request.

**Comment by bckspc** [comment]
more on the issue...

Manually debugging line by line, the submit part is done correctly and I receive the request on the server but when the callback is called, it triggers some jquery function that give the error: "jquery-1.5.min.js:16Uncaught SyntaxError: Unexpected token :"

**Comment by bckspc** [comment]
more indepth debugging... :)

Error on line 601 of jQuery 1.5 ("head.removeChild( script );").
The json I've returned from the server is {"result":"OK","message":"Criado evento com o ID 76"}
I believe that jquery isn't parsing the json data as json. There were some changes in the ajax request on jquery 1.5, maybe some of the parameters or default value have changed.

It seems the ajax request is being interpreted as type "text" or "script".

hope this helps

**Comment by bckspc** [comment]
OK. Sorry for the spam but I keep returning to the problem with some insight of what might be.

I began to have the problem with another plugin (fullcalendar) and I realized the problem was in fact jQuery that trying to parse json as a script. If I change the datatype to "text json" (new functionality in 1.5) and it works like a charm on both cases but I believe it's a bug from jquery itself.

**Comment by bckspc** [comment]
I've reported bug #8302 in jQuery trac

**Comment by bckspc** [comment]
They can't reproduce the bug on jQuery but I have this problem also on fullcalendar so maybe is something to do with the way it's being called.

Can someone reproduce the bug using http://jsfiddle.net?

**Comment by yellow1912** [comment]
well, i didnt have time to recheck everything, but i can confirm 2 things
1. This issue is real
2. using jquery form with jquery 1.5.0 doesnt guarantee that an error will be triggered, must be something special needed to reproduce this issue. 

I will spend some time on this issue this weekend to narrow down the possible causes
