### ISSUE TITLE
Chrome/safari issue with file upload and XML return

### ISSUE THREAD

**Issue by dannewns** [jquery-form/form#65]
Hi 

i seem to be having an issue with file uploading in chrome and safari it works ok in everything else. it uploading an image file within a modal popup the code for the form looks like this

```
 var formOptions = {
    target:        '#media',
    beforeSubmit: function(arr, $form, options) {
        startLoader();
    },
    clearForm: true,
    iframe: true,
    forceSync: true,
    dataType: 'xml',
    success: showResponse

 }

$('#media-u-form').bind('submit',function(){

    $(this).ajaxSubmit(formOptions);

    return false;

});
```

within chrome it never seems to get into the showResponse function and just loads the forms actual href action, im using jquery 1.4.4 and the latest version of the form plugin. hope there is some form of solution for this.

thanks
Dan

**Comment by abilek** [comment]
I am having similar issues - as far as I can tell the success callback does not fire at all on webkit browsers.

**Comment by scowles4** [comment]
If anyone has an ETA on this issue it'd be extremely helpful - we need to know whether we should choose a different plug-in or hold out for this fix... it's a major one for us.

Alternatively, has anyone found a workaround?  

Thanks!

**Comment by malsup** [comment]
Can someone post a link to a simplified test page that shows the problem?  Chrome is my main browser so I know this works.  Does my demo page work for you?

**Comment by Vojtek71** [comment]
I believe I am having a similar issue......however I get mixed results.  For me it depends on how long my process is taking on the server.  It seems that after about a 1:30 min another POST to the sever is being made and a 404 error is being returned from NGINX although this is regardless of how long my timeouts are set for NGINX and APACHE.....

**Comment by dannewns** [comment]
the way i managed to get this fixed was to turn off forceSync it was the only thing that seemed to stop if from happening.
