### ISSUE TITLE
ajaxSubmit not sending form immediately

### ISSUE THREAD

**Issue by xmacinka** [jquery-form/form#67]
Hello,
I have a problem with latest version 2.63 and jQuery 1.4.4.

Problem: ajaxSubmit doesn't seem to send the form immediately.

sample code using POST form id=emailSendForm:

$('#emailSendForm').attr('action',{/literal}"{$ajaxLink}"{literal}); // sets url from PHP

var content = getDataFromCK('text'); // loads text from CK editor

$('#email_body_real').val(content); // hidden input inside form

$('#send_newsletter_email').val(0); // hidden input inside form

$('#generateProducts').val(0); // hidden input inside form

$('#generateEmailPreview').val(1); // hidden input inside form

$('#emailSendForm').ajaxSubmit(options);

$('#generateEmailPreview').val(0);

---

Problem is that generateEmailPreview POST value is 0 at the server. Commenting the last line solves the problem and the value is 1 at the server then.

Version 2.28 with jQuery 1.3.2 worked with the same source code as expected.

**Comment by malsup** [comment]
Are you uploading a file in that form?  If so, use this option to force a synchronous post:

```
forceSync: true
```

**Comment by xmacinka** [comment]
No, I'm not uploading any files, just sending hidden fields. I tried forceSync: true and it helped, now I see you added this in v 2.38, that is why it worked well in 2.28.
Thank you.
Anyway I think this behavior should be noted somewhere for others, because here http://malsup.com/jquery/form/#api is written that ajaxSubmit "Immediately submits the form via AJAX."

**Comment by malsup** [comment]
You must be getting into the file upload logic.  Are there file inputs in the form?  Is the form multi-part?

**Comment by xmacinka** [comment]
Yes, there is one file input (but no file is selected - it is optional = email attachment) and the form has enctype="multipart/form-data". I tried it without both the file input and without the enctype and it worked as expected without forceSync: true.

**Comment by malsup** [comment]
forceSync only applies to the file upload logic.  The default behavior is to introduce a small delay when uploading files so that "please wait" messages can be shown, etc.  If your form has a file input (regardless of whether a file is selected) or it is a multipart form, then you'll trip the file upload logic.

**Comment by Chealer** [comment]
I reported the problem of submitted data being incorrect in https://github.com/malsup/form/issues/162
