### ISSUE TITLE
WebKit only error, '$.handleError' [undefined] is not a function.

### ISSUE THREAD

**Issue by tmertz** [jquery-form/form#69]
I am using this plugin in a site, and everything seems to run fine, except when I try to run the code in Safari or Chrome the Error Console returns the error below: 

TypeError: Result of expression '$.handleError' [undefined] is not a function.

The code runs perfectly well in all other browsers (ie. non-WebKit browsers). Can you, or someone else perhaps, point me in some sort of direction on how to fix this?

**Comment by sambs** [comment]
Upgrading to the latest version (2.64) fixed this for me.
