### ISSUE TITLE
X-Requested-With

### ISSUE THREAD

**Issue by IAlexanderI** [jquery-form/form#7]
Hello.
Why u don't send this header:
xhr.setRequestHeader("X-Requested-With", "XMLHttpRequest");

It's feature from jquery.
May be u know how correct this???

Thanks.

**Comment by malsup** [comment]
This header is always sent when the XHR is used, however the form plugin does not use XHR when your form has a file input.  Files cannot be uploaded via ajax.

**Comment by IAlexanderI** [comment]
You tell me what i want.
Thank you.
