### ISSUE TITLE
v2.65 IE8 file upload does seem to work

### ISSUE THREAD

**Issue by vivrana** [jquery-form/form#71]
Reverting to 2.64 did the trick.  The form couldn't be submitted without having it return incorrect output even if all the tags were removed.

Here's the format if replication needed --

```
jQuery('#reviewForm').ajaxForm({
  success: function(data) 
  {
  ....
  }
}
...

<form name="reviewForm" id="reviewForm" method="post"
  action="/review/submitReview.ajax" enctype="multipart/form-data">
  ...
</form>
```

**Comment by malsup** [comment]
v2.66 should fix.  Thanks.
