### ISSUE TITLE
ajax submit sends some values as [object Object]

### ISSUE THREAD

**Issue by lifejourneyme** [jquery-form/form#73]
Dear Malsup,

thank you for this beautiful plugin. I have set up some forms to be submitted in ajax following the examples in your site. the examples run with jquery 1.4.2 with no problems and I have used that for a long time. When I use jquery 1.4.4 and above (1.5.x ) I get the error where some submitted values of the form become [object Object].

 I use form plugin v2.67
Thank you

**Comment by malsup** [comment]
Please post a link that shows the problem.  Thanks.

**Comment by lifejourneyme** [comment]
Dear Malsup, 

I have updated tinymce from 3.3.9 to 3.4.1 and that solved the issue.

Thank you for your time,
Best Wishes
