### ISSUE TITLE
File Upload Timeouts not working correctly

### ISSUE THREAD

**Issue by kmudrick** [jquery-form/form#74]
If a timeout in a file upload is caused by a hang on the server side, the return on line 326 (inside the "response not received yet" if block) causes the script to wait until a response is eventually returned.

Commenting this line out seems to resolve this behavior for me.  Any reason why it is there?

**Comment by kmudrick** [comment]
Note: the side effect of not returning there, is that the timeout handling setup on line 278, needs to be cancelled inside cb().

**Comment by malsup** [comment]
Fixed.  Thanks!

**Comment by kmudrick** [comment]
I still think the setTimeout:

setTimeout(function() { timedOut = true; cb(); }, s.timeout);

needs to be cancelled (via a clearTimeout.)

The behavior I see: if the first request times out (handled correctly), and then you retry and it succeeds.. after timeout millis later, the "failure" timeout from the original hang kicks in.

I'm explicitly invoking .ajaxSubmit() on the form each time I want to submit (and using a global .ajaxError) if that helps.
