### ISSUE TITLE
Error when using FF4 and adblock.

### ISSUE THREAD

**Issue by andornaut** [jquery-form/form#75]
Environment:
Ubuntu
Firefox 4
Adblock (current version as of this date)
jquery 1.5 (current version as of this date)
jquery.form plugin 2.69

JS Code:

```
$('#form').ajaxSubmit({
        data: {action: 'foo'},
        target: '#bar',
    }
);
```

Firebug console error message:

uncaught exception: [Exception... "Component returned failure code: 0x805e0006 [nsIDOMHTMLFormElement.submit]" nsresult: "0x805e0006 (<unknown>)" location: "JS frame :: /.../jquery.form.js :: doSubmit :: line 296" data: no]

This error does not occur in Google Chrome or in FF4 when adblock is disabled.

**Comment by nookiepl** [comment]
Confirmed by some of our users. Firefox (even 5) + AdBlock = no love. @adronaut, did you manage to workaround this or fix?

**Comment by kevindb** [comment]
Are you still experiencing this issue?
