### ISSUE TITLE
ajaxError raised after upload succeeds when timeout is defined

### ISSUE THREAD

**Issue by jimmysoho** [jquery-form/form#80]
Upgraded from 2.49 (18-OCT-2010) to 2.69 (06-APR-2011) and a new bug seems to be introduced. 

When you upload a file where a timeout is defined (via ajaxSettings or via the options), then the upload works fine, but long after the upload finished when the timeout is reached it will throw an exception resulting in a ajaxError trigger. Previous version worked correctly.

**Comment by malsup** [comment]
Good catch, thanks.  Fixed in v2.72.

**Comment by jimmysoho** [comment]
Fix works for me, thank you!

**Comment by malsup** [comment]
Sure thing.  Thanks for reporting it.
