### ISSUE TITLE
IE9 fails the Test Suite

### ISSUE THREAD

**Issue by GregSawin** [jquery-form/form#82]
IE9 fails 93 or 111 tests from test page from multiple machines I've tested it from:
http://jquery.malsup.com/form/test/

I'm not sure if this is related but in my one of my two real world uses of this plugin I'm seeing simultaneous ajax and normal page post backs, so the form gets submitted twice; only on IE9.  I do have an app that works fine and only submits via ajax but I can't figure out the difference between the two.  The example page http://jquery.malsup.com/form/#ajaxSubmit used to have the same problem, at least with IE9 RC but it seems to be working fine now, has anything changed?

**Comment by malsup** [comment]
Thanks for the heads up, Greg.  The tests were failing because the plugin file was not loading correctly. The test page was trying to load it from github but IE9 was complaining about a mimetype mismatch.  Post a link (or email me) to the page you're having trouble with.

**Comment by GregSawin** [comment]
FYI, I traced the issue down to a web analytics library (HBX).  Including the 3rd party javascript file was causing the problem.  The reason it wasn't impacting my other app was because I wasn't using normal submit buttons, instead it uses <input type="button" and then I have some jquery that does a form.submit on that button.click.  Thanks for fixing the unit test page and allowing me to see that it wasn't this form plugin that was causing the issue.

**Comment by GregSawin** [comment]
Actually it's the interaction with the plugin and the HBX code that causes the issue.  Using normal javascript to block a form submit or do ajax calls didn't have a problem.  I can send some html if you want to figure out why?  Having the work around is good enough for me.
