### ISSUE TITLE
Incompatiblity with jQuery 1.5.2

### ISSUE THREAD

**Issue by yourchoice** [jquery-form/form#83]
Incompatiblity with jQuery 1.5.2

**Comment by malsup** [comment]
Can you explain?

**Comment by yourchoice** [comment]
Just I changed the jQuery JavaScript Library from v1.4.2 to 1.5.2 and no action on submit button...

**Comment by malsup** [comment]
You probably are using an older version of the Form plugin.  Changes were made for 1.5 compatibility.

**Comment by yourchoice** [comment]
I use your version: 2.73 (03-MAY-2011)

When I change jquery library from v1.4.2 to 1.5.2 (or v1.6) I have no action on sumit button.

Please try with: http://code.jquery.com/jquery-1.6.min.js 

Thank's

**Comment by malsup** [comment]
Please post a link. My test page uses jQuery 1.5.2 and works just fine.  http://jquery.malsup.com/form/

**Comment by yourchoice** [comment]
Escuse me! my mistake.

I had  in  my  form the atribute: onsubmit="return false;" With jquery <=v1.4.2 working well . 

With jquery > 1.5 if I have onsubmit="return false;", not working.

I know, onsubmit atribute is not necesare (it's redundant).

Thank's
