### ISSUE TITLE
$.handleError bug is back in latest jquery.form version

### ISSUE THREAD

**Issue by rikbruil** [jquery-form/form#85]
The latest version of jquery.form plugin breaks with jQuery 1.5 and 1.6. It seems an old bug has made a reappearance in the code (https://github.com/malsup/form/issues/56). Version 2.6 works with jQuery 1.5 and 1.6 ($.handleError calls were removed from that version) but the latest version contains calls to the non-existant function $.handleError again.

This breaks file-uploads in our production environment, so we are forced to use version 2.60 for the time being.

**Comment by malsup** [comment]
Huh?  There is no handleError call.

https://github.com/malsup/form/raw/master/jquery.form.js
