### ISSUE TITLE
incompatible with jquery 1.5.2+

### ISSUE THREAD

**Issue by plusjade** [jquery-form/form#86]
So far this funciton seems to be the main problem : `var httpData` as the native jquery code for httpData no longer exists. 
I'm not good enough to troubleshoot it myself but I can certainly try...

**Comment by plusjade** [comment]
seems to work better if you don't explicitly pass a dataType. Errors for me with `dataType : 'json'` but works ok without it (while returning json)

**Comment by malsup** [comment]
Please upgrade to the latest form plugin.  This issue has long since been resolved.
