### ISSUE TITLE
Upload file in IE 8( server side return status 302 ) js error

### ISSUE THREAD

**Issue by tarascv** [jquery-form/form#87]
For example when we upload file and server side returns 302 status we got js error:
328 line: Access is denied.
var doc = io.contentWindow ? io.contentWindow.document : io.contentDocument ? io.contentDocument : io.document;

version: 2.72

Could you please provide any information about this issue?

Thanks in advance

**Comment by malsup** [comment]
Does the temporary URI have a different domain, protocol or port?

**Comment by tarascv** [comment]
No, all are the same.

**Comment by jszoja** [comment]
Sorry, I'm not involved, but I think 302 is returned for redirects, which could be part of mod_rewrite? We used to have external redirects instead of internal ones in .httacces. I hope it is relevant, otherwise, please remove it.

**Comment by kevindb** [comment]
Are you still experiencing this issue?
