### ISSUE TITLE
Automatic detection method of data sending

### ISSUE THREAD

**Issue by alexeyco** [jquery-form/form#88]
By default, your library uses the standard method of sending data jquery. If you want to transfer files, now you want to use iframe. But now there is an opportunity for some browsers use xhr2.

Would not it be correct to do so. By default, when initializing the plugin, it looks for file-type fields. If not - then use the standard transfer method. If they are - then determine whether your browser xhr2. If not - then use the iframe.

Using xhr2 api allows you to display download progress of files... It's great!

**Comment by malsup** [comment]
Yes, this is on my todo list.  Thanks for the reminder.
