### ISSUE TITLE
'multipart/form-data' encrypted forms always use a hidden iframe by default

### ISSUE THREAD

**Issue by mkemmerling** [jquery-form/form#90]
The plugin uses a hidden iframe whenever the iframe option is not false and
- there is any file input field, or
- the iframe option is explicitely set to true, or
- the form is encrypted as 'multipart/form-data'.

In contrast to what the documentation says the default value of the iframe option is undefined, not false. Therefore by default all forms encrypted as 'multipart/form-data' use the hidden iframe. But according to http://www.w3.org/TR/html401/interact/forms.html#h-17.13.4.2 the 'multipart/form-data' content type should not be used for file uploads only, but whenever a form contains non-ASCII or binary data.

I can't see why the content type is checked at all. Up to version 2.43 the check was not active.

**Comment by malsup** [comment]
If your form has enctype of multipart/form-data then it needs to be submitted natively by the browser.  Ajax won't submit the data as multipart.
