### ISSUE TITLE
error: callback does not exist

### ISSUE THREAD

**Issue by jalchr** [jquery-form/form#91]
Please add support for the error: callback in addition to the existing success callback ... I believe this is much of use to everyone ... thanks

**Comment by malsup** [comment]
All the standard ajax callbacks and hooks are supported.

**Comment by jalchr** [comment]
Sorry, but I tried few things and nothing is mentioned in the documentation ... do you have any link to a resource that uses the "error" callback 

var options = {
                            success: function () {
                                location.reload();
                            },
                            beforeSubmit: function (arr, jqform, options) {
                                var form = jqform[0];
                                if (form.fileUpload.value == "") {
                                    alert('Please select an image to upload');
                                    return false;
                                }
                                return true;
                            },
                           error: function () {
                                alert("error !"); // <--------------- never fires even when server return status is 500 ... 
                            }
                        };

```
                    $('#form').ajaxSubmit(options);
```

**Comment by malsup** [comment]
Ah, right.  For file uploads there is no error handling as I don't have any way to access the status codes.

**Comment by jalchr** [comment]
oh, okay ... 
Still any sample of using the "error" callback will help me in other scenarios ... 

Thanks

**Comment by malsup** [comment]
The error callback works _exactly_ like it does with $.ajax.  The form plugin uses $.ajax and passes your options to it.
