### ISSUE TITLE
IE7 file upload when response content-type header is set

### ISSUE THREAD

**Issue by raykolbe** [jquery-form/form#93]
There is a bug when trying to submit a file input field in IE7 when the response's content-type header is set to application/json, or even text/plain. IE asks to open or save the file.

I only know a little bit about how the file upload works (via an iframe positioned out of view) and I can only imagine that IE catches the response before it is loaded in the iframe, trying to handle it accordingly. Since IE doesn't know how to handle application/json, it asks the user if they wish to open/save the file. However, I am not sure why a text/plain header would trigger the same behavior. Is IE expecting the same text/html only to be loaded in an iframe?

I know that not setting the content-type in the response works, but I would rather not do that if this problem can be solved at the JS level.

**Comment by malsup** [comment]
Yeah, that surprising to hear about the text/plain behavior.  Can you post a simplified test page?

**Comment by kcivey** [comment]
IE used to ignore text/plain as a content type and instead look at the file contents and try to guess what it was. I don't know when that incredibly annoying behavior stopped, if it ever did.

**Comment by TwistedLogic** [comment]
I solved this issue forcing the server to respond with content-type: text/html

**Comment by jnimety** [comment]
I am having the same issue with IE 9, setting text/html does not work

**Comment by kamranayub** [comment]
Here's a reproduction: http://jsfiddle.net/kamranayub/FfWnq/embedded/result/

We fixed it by forcing content type to `text/html` (we are using ASP.NET MVC):

``` c#
public ActionResult Upload(...) {
    var result = Json(objectToSerialize);

    result.ContentType = "text/html";

    return result;
}
```

**Comment by 66Ton99** [comment]
It can be reproduced without file input, enough set enctype="multipart/form-data" to form

**Comment by kevindb** [comment]
Are you still experiencing this issue?
