### ISSUE TITLE
TypeError: Cannot call method 'toLowerCase' of undefined

### ISSUE THREAD

**Issue by sorter** [jquery-form/form#94]
When I attempt to upload an image using ajaxSubmit() on a page that previously produced no errors (i.e. with previous versions of jquery.form) the 'success' handler of my request would not be handled. Rather the 'error' handler was being hit but the response is successful as far as the server is considered. 

The error is being caused by toLowerCase being called within the ajaxSubmit library. The reason I'm certain of this is because I make no use of the 'toLowerCase' method. If you require further code to replicate the error or if I have left out any information please let me know. 

The following is the error object that is being passed to ajaxSubmit.

Object
abort: function (status) {
aborted: 0
error: TypeError: Cannot call method 'toLowerCase' of undefined
getAllResponseHeaders: function () {}
getResponseHeader: function (header){
responseText: "{"width": 223, "id": "6bf177a7b37e45bc", "height": 136}"
responseXML: null
setRequestHeader: function () {}
status: 0
statusText: "n/a"
**proto**: Object
add:193error
add:194TypeError: Cannot call method 'toLowerCase' of undefined

**Comment by malsup** [comment]
Fixed.  https://github.com/malsup/form/raw/master/jquery.form.js
https://github.com/malsup/form/raw/master/jquery.form.js
