### ISSUE TITLE
Log with ajaxsubmit in v 2.81

### ISSUE THREAD

**Issue by gtraxx** [jquery-form/form#96]
Hello from the upgrade to version 2.81 and jQuery 1.6.1 I systematically a log message after sending with ajaxsubmit.
I have this bug since the update, none before this change log
Error :

[jquery.form] ajaxSubmit: skipping submit process - no element selected

error description:

fast fail if nothing selected

best regards

**Comment by malsup** [comment]
If you get that message then your jQuery selector is wrong.

**Comment by gtraxx** [comment]
What is curious is that with version 2.64 I did not have this message
By checking, I have the same message using jquery ajax which is very strange

So the log appears even without ajaxsubmit
An idea of the problem

Best regards

**Comment by malsup** [comment]
Can't help you without a test page.  It works perfectly for me.

http://jquery.malsup.com/form/jun7.html

**Comment by gtraxx** [comment]
I found the error that had just jquery validate and an outer class:)

Best regards :D
